// --- utils
import { filter, get, map, uniq } from "lodash-es";

// --- types
import type { UnifiedAddressContext } from "./types";
import type { JsonSchema, UISchemaElement } from "@jsonforms/core";
import { BrandConfigKeys } from "@upmind-automation/types";
import { useClientAddress } from "../../../client/address";
import { useClientCompany } from "../../../client/company";

// Use a conditional element as we only want the field to mount when there is a value
const conditionalElement = (condition: any, element: any) => {
  return condition ? [element] : [];
};

export const useSchema = ({
  country,
  regions,
  baseModel,
  countries,
  config,
}: UnifiedAddressContext) => {
  const schema: JsonSchema = {
    type: "object",
    properties: {
      addressId: {
        type: ["string", "null"],
        default: baseModel.addressId,
        use: useClientAddress,
        update: "updateAddressId",
      } as any,
      companyId: {
        type: ["string", "null"],
        default: baseModel.companyId,
        use: useClientCompany,
        update: "updateCompanyId",
      } as any,
      updateAddressId: {
        type: ["string", "null"],
        default: null,
      },
      updateCompanyId: {
        type: ["string", "null"],
        default: null,
      },
    },
    oneOf: [
      {
        title: "Personal",
        $ref: "#/definitions/personal",
      },
      {
        title: "Business",
        $ref: "#/definitions/business",
      },
    ],
    definitions: {
      company: {
        type: "object",
        title: "Company",
        required: ["companyName"],
        properties: {
          addressId: {
            type: ["string", "null"],
            title: "ID",
            description: "The AutoGenerated ID of the Address.",
            readOnly: true,
          },
          companyName: {
            type: ["string", "null"],
            title: "Company Name",
          },
          regNumber: {
            type: ["string", "null"],
            title: "Company Number",
          },
          vatNumber: {
            type: ["string", "null"],
            title: "Registered Tax ID",
          },
        },
      },
      address: {
        type: "object",
        title: "Address",
        required: ["address1", "city", "postcode", "countryId"],
        properties: {
          address1: {
            type: ["string"],
            title: "Address",
          },

          address2: {
            type: ["string", "null"],
            title: "",
          },

          city: {
            type: ["string"],
            title: "City",
          },

          postcode: {
            type: ["string"],
            title: "Postal / Zip Code",
          },

          regionId: {
            type: ["string", "null"],
            title: "Region",
            oneOf: map(regions || [], item => ({
              const: item.id,
              title: item.name,
            })),
          },

          countryId: {
            type: "string",
            title: "Country",
            oneOf: map(countries || [], item => ({
              const: item.id,
              title: item.name,
            })),
          },
        },
      },
      phone: {
        type: "object",
        title: "Phone number",
        isPhoneNumber: country?.code,
        default: baseModel?.phone,
        required: ["number"],
        properties: {
          number: {
            type: ["string", "null"],
            title: "Phone number ( with dialing code )",
          },

          nationalNumber: {
            type: ["string", "null"],
            title: "Phone number",
          },

          countryCallingCode: {
            type: ["string", "null"],
            title: "Country calling code",
          },

          country: {
            type: ["string", "null"],
            title: "Country",
          },
        },
      } as any,
      personal: {
        type: "object",
        additionalProperties: true,
        required: ["address", "addressId"],
        allOf: [
          {
            if: {
              properties: {
                addressId: { const: null },
              },
            },
            then: {
              properties: {
                address: {
                  required: ["address1", "city", "postcode", "countryId"],
                },
              },
            },
          },
        ],
        properties: {
          type: {
            type: "number",
            default: 1,
          },
          address: {
            $ref: "#/definitions/address",
            default: {
              regionId: baseModel?.address?.regionId,
              countryId: baseModel?.address?.countryId,
            },
          },
          phone: {
            $ref: "#/definitions/phone",
          },
        },
      },
      business: {
        type: "object",
        required: ["company", "address", "companyId"],
        additionalProperties: true,
        allOf: [
          {
            if: {
              properties: {
                addressId: { const: null },
              },
            },
            then: {
              properties: {
                address: {
                  required: ["address1", "city", "postcode", "countryId"],
                },
              },
            },
          },
        ],
        properties: {
          companyId: {
            type: ["string", "null"],
            default: baseModel.companyId,
          },
          type: {
            type: "number",
            default: 4,
          },
          company: {
            $ref: "#/definitions/company",
          },
          address: {
            $ref: "#/definitions/address",
            default: {
              regionId: baseModel?.address?.regionId,
              countryId: baseModel?.address?.countryId,
            },
          },
          phone: {
            $ref: "#/definitions/phone",
          },
        },
      },
    },
  };

  if (get(config, BrandConfigKeys.CHECKOUT_REQUIRE_PHONE)) {
    schema.definitions!.personal!.required!.push("phone");
    schema.definitions!.business!.required!.push("phone");
  }

  if (get(config, BrandConfigKeys.REQUIRE_REGION_IN_ADDRESS)) {
    schema.definitions!.address!.required!.push("regionId");
  }

  if (
    get(config, BrandConfigKeys.REQUIRE_COMPANY_FOR_ORDERS) &&
    !baseModel.addressId
  ) {
    schema.oneOf?.shift();
  }

  return schema as JsonSchema;
};

export const useUischema = ({
  config,
  addresses,
  companies,
  model,
}: UnifiedAddressContext) => {
  const addressUiSchema = {
    type: "Control",
    scope: "#/properties/address",
    options: {
      autoFocus: true,
      autocomplete: "off",
      detail: {
        type: "VerticalLayout",
        elements: [
          {
            type: "Control",
            scope: "#/properties/countryId",
          },
          {
            type: "address",
            options: {
              fields: ["address1", "address2"],
              placeholder: "Start typing your address",
            },
            elements: [
              {
                type: "Group",
                options: {
                  border: false,
                },
                elements: [
                  {
                    type: "Control",
                    scope: "#/properties/address1",
                    options: {
                      placeholder: "House name, apartment number etc.",
                    },
                  },
                  {
                    type: "Control",
                    scope: "#/properties/address2",
                    options: {
                      placeholder: "Road, street name etc.",
                    },
                  },
                ],
              },
              {
                type: "Control",
                scope: "#/properties/city",
                options: {
                  placeholder: "City, town etc.",
                },
              },
              {
                type: "HorizontalLayout",
                elements: [
                  {
                    type: "Control",
                    scope: "#/properties/regionId",
                    options: {
                      placeholder: "Select region",
                    },
                  },
                  {
                    type: "Control",
                    scope: "#/properties/postcode",
                    options: {
                      placeholder: "eg. 10011",
                    },
                  },
                ],
              },
            ],
          },
        ],
      },
    },
    rule: {
      effect: "HIDE",
      condition: {
        scope: "#",
        schema: {
          required: ["addressId"],
          properties: {
            addressId: { not: { const: null } },
          },
        },
      },
    },
  };

  const personalUiSchema = {
    type: "VerticalLayout",
    elements: [
      ...conditionalElement(get(model, "updateAddressId"), {
        type: "Model",
        scope: "#/properties/updateAddressId",
        label: "",
      }),
      {
        type: "AddressList",
        scope: "#/properties/addressId",
        options: {
          label: "Address",
          oneOf: map(
            filter(addresses || [], item => item.type === 1),
            item => ({
              id: item.id,
              title: item.title,
              description: item.description,
              item: item,
            })
          ),
        },
        rule: {
          effect: "SHOW",
          condition: {
            scope: "#",
            schema: {
              required: ["addressId"],
              properties: {
                addressId: { not: { const: null } },
              },
            },
          },
        },
      },
      addressUiSchema,
      {
        type: "Control",
        scope: "#/properties/phone",
      },
    ],
  };

  const businessUiSchema = {
    type: "VerticalLayout",
    elements: [
      ...conditionalElement(get(model, "updateCompanyId"), {
        type: "Model",
        scope: "#/properties/updateCompanyId",
        label: "",
      }),
      {
        type: "AddressList",
        scope: "#/properties/companyId",
        options: {
          label: "Company",
          oneOf: map(companies || [], item => ({
            id: item.id,
            title: item.title,
            description: item.description,
            item: item,
          })),
        },
        rule: {
          effect: "SHOW",
          condition: {
            scope: "#",
            schema: {
              required: ["companyId"],
              properties: {
                companyId: { not: { const: null } },
              },
            },
          },
        },
      },
      {
        type: "Control",
        scope: "#/properties/company",
        options: {
          detail: {
            type: "VerticalLayout",
            elements: [
              {
                type: "Control",
                scope: "#/properties/companyName",
                options: {
                  placeholder: "Company Name",
                },
              },
              {
                type: "HorizontalLayout",
                elements: [
                  {
                    type: "Control",
                    scope: "#/properties/regNumber",
                    options: {
                      placeholder: "Company number",
                    },
                  },
                  {
                    type: "Control",
                    scope: "#/properties/vatNumber",
                    options: {
                      placeholder: "Registered Tax ID",
                    },
                  },
                ],
              },
            ],
          },
        },
        rule: {
          effect: "HIDE",
          condition: {
            scope: "#",
            schema: {
              required: ["addressId"],
              properties: {
                addressId: { not: { const: null } },
              },
            },
          },
        },
      },
      addressUiSchema,
      {
        type: "Control",
        scope: "#/properties/phone",
      },
    ],
  };

  const oneOfUiSchemas = [personalUiSchema, businessUiSchema];

  if (get(config, BrandConfigKeys.REQUIRE_COMPANY_FOR_ORDERS)) {
    oneOfUiSchemas.shift();
  }

  const uiSchema = {
    type: "VerticalLayout",
    elements: [
      {
        type: "Control",
        scope: "#",
        options: {
          toggle: true,
          oneOfUiSchema: oneOfUiSchemas,
        },
      },
    ],
  };

  return uiSchema as UISchemaElement;
};
