// --- utils
import { map, reduce } from "lodash-es";

// --- types
import { AddressTypes } from "../../../client";
import type { UnifiedAddressContext } from "./types";
import type { JsonSchema, UISchemaElement } from "@jsonforms/core";

export const useSchema = ({
  country,
  regions,
  baseModel,
  countries,
}: UnifiedAddressContext) => {
  const schema = {
    type: "object",
    title: "Unified Address Fields",
    required: ["address1", "city", "countryId", "postcode", "type"],
    // --- conditionally required fields
    if: {
      properties: {
        companyDetails: { const: true },
      },
      required: ["companyDetails"],
    },
    then: { required: ["companyName", "email", "regNumber"] },
    // ---
    properties: {
      id: {
        type: ["string", "null"],
        title: "ID",
        description: "The AutoGenerated ID of this Unified Address.",
        readOnly: true,
      },

      companyId: {
        type: ["string", "null"],
        title: "ID",
        description: "The AutoGenerated ID of the Company.",
        readOnly: true,
      },

      addressId: {
        type: ["string", "null"],
        title: "ID",
        description: "The AutoGenerated ID of the Address.",
        readOnly: true,
      },

      name: {
        type: ["string", "null"],
        title: "Address Name",
        default: baseModel?.name,
      },

      address1: {
        type: "string",
        title: "Address Line 1",
      },

      address2: {
        type: ["string", "null"],
        title: "Address Line 2",
      },

      city: {
        type: "string",
        title: "City",
      },

      postcode: {
        type: "string",
        title: "Postcode",
      },

      regionId: {
        type: ["string", "null"],
        title: "Region",
        oneOf: !regions?.length
          ? undefined
          : map(regions, item => {
              return {
                const: item.id,
                title: item.name,
              };
            }),
      },

      // not sure if this is ever used, but it is in the type definition
      state: {
        type: ["string", "null"],
        title: "State",
      },

      countryId: {
        type: "string",
        title: "Country",
        default: baseModel?.countryId,
        oneOf: !countries?.length
          ? undefined
          : map(countries, item => ({
              const: item.id,
              title: item.name,
            })),
      },

      // ---

      companyDetails: {
        type: ["boolean", "null"],
        title: "Add business details",
        default: baseModel?.companyDetails,
      },

      companyName: {
        type: ["string", "null"],
        title: "Name",
      },

      email: {
        type: ["string", "null"],
        title: "Email",
        format: "email",
        default: baseModel.email,
        // lookup: emails?.search,
      },

      phone: {
        type: ["object", "null"],
        title: "Phone",
        isPhoneNumber: country?.code,
        properties: {
          number: {
            type: ["string", "null"],
            title: "Phone number ( with dialing code )",
            default: baseModel?.phone?.number,
          },

          nationalNumber: {
            type: ["string", "null"],
            title: "Phone number",
            default: baseModel?.phone?.nationalNumber,
          },

          countryCallingCode: {
            type: ["string", "null"],
            title: "Country calling code",
            default: baseModel?.phone?.countryCallingCode,
          },

          country: {
            type: ["string", "null"],
            title: "Country",
            default: baseModel?.phone?.country,
          },
        },
      },

      regNumber: {
        type: ["string", "null"],
        title: "Registration number",
      },

      vatNumber: {
        type: ["string", "null"],
        title: "Registered tax/VAT id",
      },

      // vatPercent: {
      //   type: ["string", "null"],
      //   title: "VAT percent",
      // },
      // ---

      default: {
        type: ["boolean", "null"],
        title: "Make this the default address?",
      },

      type: {
        type: "number",
        title: "Address Type",
        default: baseModel?.type,
        oneOf: !AddressTypes?.length
          ? undefined
          : map(AddressTypes, ({ value, key }) => {
              return {
                const: key,
                title: value,
              };
            }),
      },
    },
  };

  return schema as JsonSchema;
};

export const useUischema = ({
  emails,
  phones,
  addresses,
}: UnifiedAddressContext) => {
  const lookups = {
    addresses: reduce(
      addresses,
      (result: any[], item) => {
        // Only return actual addresses, NOT companies
        result.push({
          value: item.id,
          label: [
            item.name,
            item.address1,
            item.address2,
            item.city,
            item.postcode,
          ].join(", "),
        });

        return result;
      },
      []
    ),

    emails: emails,
    phones: phones,
  };

  const schema = {
    type: "VerticalLayout",
    elements: [
      {
        // --- address details
        type: "VerticalLayout",
        elements: [
          {
            type: "Control",
            scope: "#/properties/name",
            options: {
              autoFocus: true,
              autocomplete: "off",
              placeholder: "My home address, etc...",
            },
            rule: {
              effect: "DISABLE",
              condition: {
                scope: "#",
                schema: {
                  anyOf: [
                    {
                      required: ["id", "companyDetails"],
                      properties: { companyDetails: { const: true } },
                    },
                  ],
                },
              },
            },
          },
        ],
        rule: {
          effect: "SHOW",
          condition: {
            scope: "#",
            schema: {
              required: ["id"],
            },
          },
        },
      },

      {
        // --- address details
        type: "VerticalLayout",
        elements: [
          {
            type: "Control",
            scope: "#/properties/address1",
            i18n: "client.unified.form.fields.address1",
            options: {
              autocomplete: "address-line1",
            },
          },
          {
            type: "Control",
            scope: "#/properties/address2",
            i18n: "client.unified.form.fields.address2",
            options: {
              autocomplete: "address-line2",
            },
          },

          // ---
          {
            type: "HorizontalLayout",
            elements: [
              {
                type: "Control",
                scope: "#/properties/city",
                i18n: "client.unified.form.fields.city",
                options: {
                  autocomplete: "address-level2",
                },
              },
              {
                type: "Control",
                scope: "#/properties/postcode",
                i18n: "client.unified.form.fields.postcode",
                options: {
                  autocomplete: "postal-code",
                },
              },
            ],
          },
          // ---
          {
            type: "Control",
            scope: "#/properties/regionId",
            i18n: "client.unified.form.fields.regionId",
            options: {
              autocomplete: "address-level1",
              placeholder: "Please select a Region...",
            },
          },
          {
            type: "Control",
            scope: "#/properties/countryId",
            i18n: "client.unified.form.fields.countryId",
            options: {
              autocomplete: "country",
              placeholder: "Please select a Country...",
            },
          },
        ],
        rule: {
          effect: "HIDE",
          condition: {
            scope: "#",
            schema: {
              anyOf: [
                {
                  required: ["id", "companyDetails"],
                  properties: { companyDetails: { const: true } },
                },
              ],
            },
          },
        },
      },

      // --- company details
      {
        type: "Control",
        scope: "#/properties/companyDetails",
        i18n: "client.unified.form.fields.companyDetails",
        rule: {
          effect: "SHOW",
          condition: {
            scope: "#",
            schema: {
              // properties: { companyDetails: { not: { const: true } } },
              anyOf: [
                {
                  required: ["id"],
                  properties: { companyId: { const: null } },
                },
                {
                  required: ["name"],
                  properties: { companyId: { const: null } },
                },
                {
                  properties: {
                    manualPlace: { const: true },
                    companyId: { const: null },
                  },
                },
              ],
            },
          },
        },
      },

      {
        type: "VerticalLayout",
        elements: [
          {
            type: "Control",
            scope: "#/properties/companyName",
            i18n: "client.unified.form.fields.companyName",
            options: {
              autoFocus: true,
              autocomplete: "organization",
              placeholder: "My Company Name (PTY) LTD",
              label: "Company Name",
            },
          },
          {
            type: "HorizontalLayout",
            elements: [
              {
                type: "Control",
                scope: "#/properties/regNumber",
                i18n: "client.unified.form.fields.regNumber",
                options: {},
              },
              {
                type: "Control",
                scope: "#/properties/vatNumber",
                i18n: "client.unified.form.fields.vatNumber",
                options: {},
              },
            ],
          },
          {
            type: "Control",
            scope: "#/properties/email",
            i18n: "client.unified.form.fields.email",
            options: {
              suggestions: true,
              autocomplete: "email",
              itemLabel: "email",
              itemValue: "email",
              items: lookups.emails,
              align: "start",
              side: "bottom",
            },
          },
          {
            type: "Control",
            scope: "#/properties/phone",
            i18n: "client.unified.form.fields.phone",
            options: {
              autocomplete: "tel",
              suggestions: true,
              itemLabel: "number",
              itemValue: "number",
              items: lookups.phones,
              align: "start",
              side: "bottom",
            },
          },
        ],
        rule: {
          effect: "SHOW",
          condition: {
            scope: "#/properties/companyDetails",
            schema: { const: true },
          },
        },
      },

      // ---
      // We don't ever show this field as it is set by an action
      // {
      //   type: "Control",
      //   scope: "#/properties/default",
      //   options: {
      //     // toggle: true
      //   }
      // }
    ],
  };

  return schema as UISchemaElement;
};
