// --- utils
import { get, map, uniq } from "lodash-es";

// --- types
import { AddressTypes } from "../../../client";
import type { UnifiedAddressContext } from "./types";
import type { JsonSchema, UISchemaElement } from "@jsonforms/core";
import { BrandConfigKeys } from "@upmind-automation/types";

export const useSchema = ({
  country,
  regions,
  baseModel,
  countries,
  config,
}: UnifiedAddressContext) => {
  const schema: JsonSchema = {
    type: "object",
    required: [],
    properties: {
      addressId: {
        type: ["string"],
        const: baseModel.addressId,
      },
      companyId: {
        type: ["string"],
        const: baseModel.companyId,
      },
      phone: {
        type: "object",
        title: "Phone",
        isPhoneNumber: country?.code,
        properties: {
          number: {
            type: ["string", "null"],
            title: "Phone number ( with dialing code )",
          },

          nationalNumber: {
            type: ["string", "null"],
            title: "Phone number",
          },

          countryCallingCode: {
            type: ["string", "null"],
            title: "Country calling code",
          },

          country: {
            type: ["string", "null"],
            title: "Country",
          },
        },
      },
    },
    oneOf: [
      {
        title: "Personal",
        $ref: "#/definitions/personal",
      },
      {
        title: "Business",
        $ref: "#/definitions/business",
      },
    ],
    definitions: {
      company: {
        type: "object",
        title: "Company",
        required: ["companyName"],
        properties: {
          addressId: {
            type: ["string", "null"],
            title: "ID",
            description: "The AutoGenerated ID of the Address.",
            readOnly: true,
          },
          companyName: {
            type: ["string", "null"],
            title: "Company Name",
          },
          regNumber: {
            type: ["string", "null"],
            title: "Company Number",
          },
          vatNumber: {
            type: ["string", "null"],
            title: "Registered Tax ID",
          },
        },
      },
      address: {
        type: "object",
        title: "Address",
        default: {
          regionId: baseModel?.address?.regionId,
          countryId: baseModel?.address?.countryId,
        },
        required: ["address1", "city", "postcode", "countryId"],
        properties: {
          address1: {
            type: "string",
            title: "Address",
          },

          address2: {
            type: ["string", "null"],
            title: "",
          },

          city: {
            type: "string",
            title: "City",
          },

          postcode: {
            type: "string",
            title: "Postal / Zip Code",
          },

          regionId: {
            type: ["string", "null"],
            title: "Region",
            oneOf: map(regions || [], item => ({
              const: item.id,
              title: item.name,
            })),
          },

          countryId: {
            type: "string",
            title: "Country",
            oneOf: map(countries || [], item => ({
              const: item.id,
              title: item.name,
            })),
          },
        },
      },
      personal: {
        type: "object",
        additionalProperties: false,
        properties: {
          type: {
            type: "number",
            default: 1,
          },
          address: {
            $ref: "#/definitions/address",
          },
        },
      },
      business: {
        type: "object",
        properties: {
          type: {
            type: "number",
            default: 4,
          },
          company: {
            $ref: "#/definitions/company",
          },
          address: {
            $ref: "#/definitions/address",
          },
        },
      },
    },
  };

  if (
    get(config, BrandConfigKeys.REQUIRE_ADDRESS_FOR_ORDERS) &&
    !baseModel.addressId
  ) {
    schema.required ??= [];
    schema.required.push("address");
  }

  if (get(config, BrandConfigKeys.REQUIRE_REGION_IN_ADDRESS)) {
    schema.definitions?.address?.required?.push("regionId");
  }

  if (
    get(config, BrandConfigKeys.REQUIRE_COMPANY_FOR_ORDERS) &&
    !baseModel.addressId
  ) {
    schema.oneOf?.shift();
    schema.required ??= [];
    schema.required.push("company", "address");
  }

  if (get(config, BrandConfigKeys.CHECKOUT_REQUIRE_PHONE)) {
    schema.required ??= [];
    schema.required.push("phone");
  }

  schema.required = uniq(schema.required);

  return schema as JsonSchema;
};

export const useUischema = ({ config }: UnifiedAddressContext) => {
  const personalUiSchema = {
    type: "VerticalLayout",
    elements: [
      {
        type: "Control",
        scope: "#/properties/address",
        options: {
          autoFocus: true,
          autocomplete: "off",
          detail: {
            type: "VerticalLayout",
            elements: [
              {
                type: "Control",
                scope: "#/properties/countryId",
              },
              {
                type: "address",
                options: {
                  fields: ["address1", "address2"],
                  placeholder: "Start typing your address",
                },
                elements: [
                  {
                    type: "Group",
                    options: {
                      border: false,
                    },
                    elements: [
                      {
                        type: "Control",
                        scope: "#/properties/address1",
                        options: {
                          placeholder: "House name, apartment number etc.",
                        },
                      },
                      {
                        type: "Control",
                        scope: "#/properties/address2",
                        options: {
                          placeholder: "Road, street name etc.",
                        },
                      },
                    ],
                  },
                  {
                    type: "Control",
                    scope: "#/properties/city",
                    options: {
                      placeholder: "City, town etc.",
                    },
                  },
                  {
                    type: "HorizontalLayout",
                    elements: [
                      {
                        type: "Control",
                        scope: "#/properties/regionId",
                        options: {
                          placeholder: "Select region",
                        },
                      },
                      {
                        type: "Control",
                        scope: "#/properties/postcode",
                        options: {
                          placeholder: "eg. 10011",
                        },
                      },
                    ],
                  },
                ],
              },
            ],
          },
        },
      },
    ],
  };

  const businessUiSchema = {
    type: "VerticalLayout",
    elements: [
      {
        type: "Control",
        scope: "#/properties/company",
        options: {
          detail: {
            type: "VerticalLayout",
            elements: [
              {
                type: "Control",
                scope: "#/properties/companyName",
                options: {
                  placeholder: "Company Name",
                },
              },
              {
                type: "HorizontalLayout",
                elements: [
                  {
                    type: "Control",
                    scope: "#/properties/regNumber",
                    options: {
                      placeholder: "Company number",
                    },
                  },
                  {
                    type: "Control",
                    scope: "#/properties/vatNumber",
                    options: {
                      placeholder: "Registered Tax ID",
                    },
                  },
                ],
              },
            ],
          },
        },
      },
      personalUiSchema,
    ],
  };

  const oneOfUiSchemas = [personalUiSchema, businessUiSchema];

  if (get(config, BrandConfigKeys.REQUIRE_COMPANY_FOR_ORDERS)) {
    oneOfUiSchemas.shift();
  }

  const uiSchema = {
    type: "VerticalLayout",
    elements: [
      {
        type: "Control",
        scope: "#/properties/phone",
        rule: {
          effect: "SHOW",
          condition: {
            scope: "#",
            schema: {
              required: ["addressId", "phone"],
              properties: {
                addressId: { not: { const: null } },
              },
            },
          },
        },
      },
      {
        type: "Control",
        scope: "#",
        options: {
          toggle: true,
          oneOfUiSchema: oneOfUiSchemas,
        },
        rule: {
          effect: "HIDE",
          condition: {
            scope: "#",
            schema: {
              required: ["addressId"],
              properties: {
                addressId: { not: { const: null } },
              },
            },
          },
        },
      },
      {
        type: "Control",
        scope: "#/properties/phone",
        rule: {
          effect: "HIDE",
          condition: {
            scope: "#",
            schema: {
              required: ["addressId", "phone"],
              properties: {
                addressId: { not: { const: null } },
              },
            },
          },
        },
      },
    ],
  };

  return uiSchema as UISchemaElement;
};
