variables:
  NODE_IMAGE: node:20.11.0-alpine3.19
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: true
  # NOTE: Stop Gitlab-CI automatically fetching GitHub repos as we need extra auth
  GIT_SUBMODULE_PATHS: ":(exclude)packages/types :(exclude)packages/ui"
  INTERNAL_NPMRC: |
    @upmind-automation:registry=https://git.upmind.io/api/v4/projects/105/packages/npm/
    //git.upmind.io/api/v4/projects/105/packages/npm/:_authToken=${CI_JOB_TOKEN}
  VITE_APP_WHITELIST_GATEWAY_PROVIDERS: "Offline,BankTransfer,Stripe_PaymentIntents,PayPal_Express,PayPal_Pro,Micropayment"

stages:
  - dependencies
  - test
  - build
  - deploy
  - stop
  - publish internal
  - publish external

include:
  - local: .gitlab-ci/storybook.yml
    rules:
      - changes:
          paths:
            - ./playgrounds/storybook/**

      - if: $CI_FORCE_STORYBOOK == "true"

  - local: .gitlab-ci/vitepress.yml
  - local: .gitlab-ci/headless.yml
  - local: .gitlab-ci/headless-vue.yml

workflow:
  rules:
    # Prefer MR pipelines; fall back to branch pipelines; but no duplicates!
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG

#------------------------------------------------------------------------------
# Shared jobs
#------------------------------------------------------------------------------

dependencies:
  stage: dependencies
  image: ${NODE_IMAGE}

  before_script:
    - corepack enable
    - corepack prepare pnpm@latest --activate
    - pnpm --version

  cache:
    - key:
        files:
          - package.json
          - pnpm-lock.yaml
      paths:
        - node_modules
        - playgrounds/storybook/node_modules
        - playgrounds/velia/node_modules
        - playgrounds/webcentral/node_modules
        - packages/headless/node_modules
        - packages/headless-vue/node_modules
        - packages/client-vue/node_modules

  artifacts:
    when: on_success
    access: all
    expire_in: "1 day"
    paths:
      - node_modules
      - playgrounds/storybook/node_modules
      - playgrounds/velia/node_modules
      - playgrounds/webcentral/node_modules
      - packages/headless/node_modules
      - packages/headless-vue/node_modules
      - packages/client-vue/node_modules
  script:
    - apk --no-cache add git openssh-client
    - |
      mkdir ~/.ssh || true

      echo "${UPMIND_TYPES_DEPLOY_PRIVATE_KEY}" > ~/.ssh/id.upmind-types
      echo "${UPMIND_UI_DEPLOY_PRIVATE_KEY}" > ~/.ssh/id.upmind-ui

      cat <<EOF > ~/.ssh/config
      Host *
        StrictHostKeyChecking no

      Host github-upmind-types
        User git
        Hostname github.com
        Identityfile ~/.ssh/id.upmind-types

      Host github-upmind-ui
        User git
        Hostname github.com
        Identityfile ~/.ssh/id.upmind-ui
      EOF

      cat <<EOF > ~/.gitconfig
      [url "github-upmind-ui:upmind/upmind-ui"]
        insteadOf = git@github.com:upmind/upmind-ui

      [url "github-upmind-types:upmind/types"]
        insteadOf = git@github.com:upmind/types
      EOF

      chmod 700 ~/.ssh
      chmod 600 ~/.ssh/id*

    - git config --global --add safe.directory '*'
    - git submodule update --init --recursive --remote
    - npm clean-install

.check version:
  stage: build
  image: ${NODE_IMAGE}
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - apk add jq
  script: |
    set -u
    cd ${ROOT_DIR}

    package_version=$(jq -r '.version' package.json)
    tag_version=$(echo "${CI_COMMIT_TAG}" | grep -Eow 'v(\d+(\.\d+)*)')

    if [ "v${package_version}" != "${tag_version}" ]; then
      cat <<EOF >&2
      ERROR: Package version and commit tag do not match

      Package version: v${package_version}
      Commit tag: ${tag_version}
    EOF
      exit 1
    fi
