// --- external
import { spawn } from "xstate";

// --- internal
import itemMachine from "../item.machine";
import { ItemActions as actions } from "./actions";
import services from "./services";

// --- utils
import { get, set, reduce, defaultsDeep, uniqueId } from "lodash-es";

// --- types
import type { IEmail } from "./types.d";
import type { JsonSchema, UISchemaElement } from "@jsonforms/core";

// --------------------------------------------------------

export const useSchema = context => {
  const schema = {
    type: "object",
    title: "Address Fields",
    required: ["email"],
    properties: {
      id: {
        type: ["string", "null"],
        title: "ID",
        description: "The AutoGenerated ID of this Email.",
        readOnly: true
      },

      // ---
      type: {
        type: "number",
        const: 1
      },

      email: {
        type: ["string", "null"],
        format: "email",
        title: "Email"
      },

      // ---

      default: {
        type: ["boolean", "null"],
        title: "Make this the default email?"
      }
    }
  };

  return schema as JsonSchema;
};

export const useUischema = () => {
  const schema = {
    type: "VerticalLayout",
    elements: [
      {
        type: "Control",
        scope: "#/properties/email",
        options: {
          focus: true,
          autocomplete: "email",
          placeholder: "name@email.com"
        }
      }

      // ---
      // We dont ever show this field as it is set by an action
      // {
      //   type: "Control",
      //   scope: "#/properties/default",
      //   options: {
      //     // toggle: true
      //   }
      // }
    ]
  };

  return schema as UISchemaElement;
};

export const useModelParser = (schema: JsonSchema, values: IEmail) => {
  const model = reduce(
    schema.properties,
    (result, field, key) => {
      const value = get(values, key, field?.const || field?.default);
      set(result, key, value);
      return result;
    },
    {}
  );

  return defaultsDeep(model, values) as IEmail;
};

// --------------------------------------------------------

export const spawnItem = (model?: IEmail) => {
  try {
    const name = get(model, "id", uniqueId("item_"));
    return spawn(
      itemMachine
        .withConfig({
          actions,
          services
        })
        .withContext({ model }),
      {
        name,
        sync: true
      }
    );
  } catch (err) {
    console.error("EmailListings", "spawnItem", { model });
  }
};
