// --- external
import { computed } from "vue";
import { interpret } from "xstate";
import { useActor } from "@xstate/vue";
import { waitFor } from "xstate/lib/waitFor";

// --- internal
import paymentMachine from "./payment.machine";

// --- utils
import { contextValue, stateMatches, useContext } from "../../utils";

// --- types
export * from "./types";
import { PaymentArgs, PaymentContext } from "./types";

// -----------------------------------------------------------------------------

export const usePayment = (initial: PaymentArgs) => {
  const service = interpret(paymentMachine.withContext(initial), {
    devTools: false
  });
  const { state, send } = useActor(service.start());

  // --- state

  async function isReady(): Promise<boolean> {
    return waitFor(
      service,
      state => !stateMatches(state, ["subscribing", "loading"]),
      { timeout: Infinity }
    ).then(state => {
      if (stateMatches(state, ["error"])) return false;
      return true;
    });
  }

  const meta = computed(() => ({
    isLoading: stateMatches(state, ["loading"]),
    isAvailable: !stateMatches(state, ["loading"]),
    isChecking: stateMatches(state, ["checking"]),
    isValid: stateMatches(state, ["valid"]),
    isProcessing: stateMatches(state, ["processing"]),
    needsApproval: stateMatches(state, ["approving"]),
    hasPaid: stateMatches(state, ["complete"]),
    hasFailed: stateMatches(state, ["error"])
  }));

  // --- context

  const context = useContext<PaymentContext>(state, "context");

  const errors = useContext<PaymentContext["error"]>(state, "error");

  const payment = contextValue<PaymentContext["payment"]>(context, "payment");

  // --- methods

  function pay() {
    send({ type: "PAY" });
  }

  function refresh(context?: PaymentArgs) {
    send({ type: "REFRESH", data: context });
  }

  // -----------------------------------------------------------------------------
  return {
    // --- state

    /**
     * Waits for the payment machine to be ready (in a terminal or available state).
     * @returns {Promise<boolean>} Resolves true if ready, false if error.
     */
    isReady,

    /**
     * Meta information about the payment state.
     * @typedef {Object} PaymentMeta
     * @property {boolean} isLoading - Indicates if the payment is loading.
     * @property {boolean} isAvailable - Indicates if the payment is available.
     * @property {boolean} isChecking - Indicates if the payment is being checked.
     * @property {boolean} isValid - Indicates if the payment is valid.
     * @property {boolean} isProcessing - Indicates if the payment is processing.
     * @property {boolean} needsApproval - Indicates if the payment needs approval.
     * @property {boolean} hasPaid - Indicates if the payment has been completed.
     * @property {boolean} hasFailed - Indicates if the payment has failed.
     */
    meta,

    // --- context
    /**
     * The current context of the payment machine.
     */
    context,

    /**
     * Any error returned by the payment machine.
     */
    errors,

    /**
     * The payment information generated by the payment machine.
     */
    payment,

    // --- methods

    /**
     * The PAY event triggers the machine to process the payment, this may result in an offsite redirect.
     * @returns void
     */
    pay,

    /**
     * Payment machine has a REFRESH event that allows us to update information from the basket/invoice.
     * This is useful if the basket has changed since the initial payment request.
     * @param {PaymentArgs} [context] - Optional new context to update the payment machine.
     * @returns void
     */
    refresh
  };
};

/**
 * The return type of usePayment composable.
 */
export type UsePayment = ReturnType<typeof usePayment>;
