// --- internal

// --- utils
import { get, set, reduce, defaultsDeep } from "lodash-es";

// --- types
import type { ICompany } from "./types.d";
import type { JsonSchema, UISchemaElement } from "@jsonforms/core";

// --------------------------------------------------------

export const useSchema = () => {
  const schema = {
    type: "object",
    title: "Address Fields",
    required: ["address_1", "city", "country_id", "postcode", "type"],
    properties: {
      id: {
        type: ["string", "null"],
        title: "ID",
        description: "The AutoGenerated ID of this Company/Address.",
        readOnly: true
      },

      // ---
      address_1: {
        type: "string",
        title: "Address Line 1"
      },
      address_2: {
        type: ["string", "null"],
        title: "Address Line 2"
      },
      city: {
        type: "string",
        title: "City"
      },
      postcode: {
        type: "string",
        title: "Postcode"
      },

      // not sure this is ever used, but it is in the type definition
      state: {
        type: ["string", "null"],
        title: "State"
      },

      // ---

      default: {
        type: ["boolean", "null"],
        title: "Make this the default address?"
      },

      name: {
        type: ["string", "null"],
        title: "Reference Name"
      }
    }
  };

  // if (id) {
  //   schema.required.push("name");
  //   schema.required.push("type");
  // }

  return schema as JsonSchema;
};

export const useUischema = () => {
  const schema = {
    type: "VerticalLayout",
    elements: [
      {
        type: "HorizontalLayout",
        elements: [
          {
            type: "Control",
            scope: "#/properties/type",
            options: {
              autocomplete: "off",
              companyholder: "Select an address type...s"
            }
          },
          {
            type: "Control",
            scope: "#/properties/name",
            options: {
              focus: true,
              autocomplete: "off",
              companyholder: "My home address, etc..."
            }
          }
        ],
        rule: {
          effect: "SHOW",
          condition: {
            scope: "#",
            schema: {
              required: ["id"]
            }
          }
        }
      },

      // ---
      {
        type: "Control",
        scope: "#/properties/address_1",
        label: "Address", // ensure we  show the title for BOTH address fields
        options: {
          focus: true,
          autocomplete: "address-line1",
          companyholder: "Address first line..."
        }
      },
      {
        type: "Control",
        scope: "#/properties/address_2",
        label: "", // ensure we DON'T show the title
        options: {
          autocomplete: "address-line2",
          companyholder: "Address second line...",
          class: "-mt-8"
        }
      },

      // ---
      {
        type: "HorizontalLayout",
        elements: [
          {
            type: "Control",
            scope: "#/properties/city",
            options: {
              autocomplete: "address-level2",
              companyholder: "City..."
            }
          },
          {
            type: "Control",
            scope: "#/properties/postcode",
            options: {
              autocomplete: "postal-code",
              companyholder: "Postcode..."
            }
          }
        ]
      },
      // ---
      {
        type: "Control",
        scope: "#/properties/region_id",
        options: {
          autocomplete: "address-level1",
          companyholder: "Please select a Region..."
        }
      },
      {
        type: "Control",
        scope: "#/properties/country_id",
        options: {
          autocomplete: "country",
          companyholder: "Please select a Country..."
        }
      }
      // ---
      // We dont ever show this field as it is set by an action
      // {
      //   type: "Control",
      //   scope: "#/properties/default",
      //   options: {
      //     // toggle: true
      //   }
      // }
    ]
  };

  return schema as UISchemaElement;
};

export const useModelParser = (schema: JsonSchema, values: ICompany) => {
  const model = reduce(
    schema.properties,
    (result, field, key) => {
      const value = get(values, key, field?.const || field?.default);
      set(result, key, value);
      return result;
    },
    {}
  );

  return defaultsDeep(model, values) as IAddress;
};
