(headless-vue) test:
  stage: test
  image: ${NODE_IMAGE}
  needs:
    - dependencies
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG =~ /^headless-vue-v\d+(\.\d+)*$/
    - if: $CI_FORCE_HEADLESS_VUE == "true"
  script:
    - npm --workspace packages/headless-vue test

(headless-vue) check version:
  extends: .check version
  variables:
    ROOT_DIR: packages/headless-vue
  rules:
    - if: $CI_COMMIT_TAG =~ /^headless-vue-v\d+(\.\d+)*$/
    - if: $CI_FORCE_HEADLESS_VUE == "true"

(headless-vue) build:
  stage: build
  image: ${NODE_IMAGE}
  needs:
    - dependencies
    - (headless-vue) test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG =~ /^headless-vue-v\d+(\.\d+)*$/
    - if: $CI_FORCE_HEADLESS_VUE == "true"
  artifacts:
    when: on_success
    access: all
    expire_in: "1 day"
    paths:
      - packages/headless-vue/dist/
  script:
    - npm --workspace packages/headless-vue run build

(headless-vue) publish internal:
  stage: publish internal
  image: ${NODE_IMAGE}
  rules:
    - if: $CI_COMMIT_TAG =~ /^headless-vue-v\d+(\.\d+)*$/
  needs:
    - dependencies
    - (headless-vue) build
    - (headless-vue) check version
  dependencies:
    - dependencies
    - (headless-vue) build
  script:
    - echo "${INTERNAL_NPMRC}" > .npmrc
    - npm --workspace packages/headless-vue publish

(headless-vue) publish to npm:
  stage: publish external
  image: ${NODE_IMAGE}
  rules:
    - if: $CI_COMMIT_TAG =~ /^headless-vue-v\d+(\.\d+)*$/
      when: manual
  needs:
    - dependencies
    - (headless-vue) build
    - (headless-vue) publish internal
  dependencies:
    - dependencies
    - (headless-vue) build
  script:
    - npm --workspace packages/headless-vue publish --access public ${NPM_PUBLISH_NPM_EXTRA_ARGS}
