(headless) test:
  extends: .pnpm
  stage: test
  needs:
    - dependencies
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG =~ /^headless-v\d+(\.\d+)*$/
    - if: $CI_FORCE_HEADLESS == "true"
  script:
    - pnpm --filter headless test

(headless) check version:
  extends: .check version
  variables:
    ROOT_DIR: packages/headless
  rules:
    - if: $CI_COMMIT_TAG =~ /^headless-v\d+(\.\d+)*$/
    - if: $CI_FORCE_HEADLESS == "true"

(headless) build:
  extends: .pnpm
  stage: build
  needs:
    - dependencies
    - (headless) test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG =~ /^headless-v\d+(\.\d+)*$/
    - if: $CI_FORCE_HEADLESS == "true"
  artifacts:
    when: on_success
    access: all
    expire_in: "1 day"
    paths:
      - packages/headless/dist/
  script:
    - pnpm --filter headless build

(headless) publish internal:
  extends: .pnpm
  stage: publish internal
  rules:
    - if: $CI_COMMIT_TAG =~ /^headless-v\d+(\.\d+)*$/
  needs:
    - dependencies
    - (headless) build
    - (headless) check version
  dependencies:
    - dependencies
    - (headless) build
  script:
    - echo "${INTERNAL_NPMRC}" > .npmrc
    - pnpm --filter headless publish

(headless) publish to npm:
  extends: .pnpm
  stage: publish external
  rules:
    - if: $CI_COMMIT_TAG =~ /^headless-v\d+(\.\d+)*$/
      when: manual
  needs:
    - dependencies
    - (headless) build
    - (headless) publish internal
  dependencies:
    - dependencies
    - (headless) build
  script:
    - pnpm --filter headless publish --access public ${NPM_PUBLISH_NPM_EXTRA_ARGS}
