variables:
  GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials.json

(storybook) deploy preview:
  extends: .pnpm
  stage: deploy
  interruptible: true
  needs:
    - dependencies
  environment:
    name: storybook/preview/${CI_COMMIT_REF_SLUG}
    action: start
    auto_stop_in: 7 days
    # NOTE: Automatically triggered when an MR pipeline is merged
    on_stop: (storybook) stop preview
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
  script:
    - echo "${GCP_SERVICE_ACCOUNT_JSON}" > ${GOOGLE_APPLICATION_CREDENTIALS}
    - pnpm --filter storybook build-storybook
    - pnpm --filter storybook exec firebase --non-interactive hosting:channel:deploy "${CI_COMMIT_REF_SLUG}" --expires 7d

(storybook) deploy production:
  extends: .pnpm
  stage: deploy
  environment:
    name: storybook/production
    action: start
    url: https://storybook.upmind.dev/
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "${GCP_SERVICE_ACCOUNT_JSON}" > ${GOOGLE_APPLICATION_CREDENTIALS}
    - pnpm --filter storybook build-storybook
    - pnpm --filter storybook exec firebase deploy

(storybook) stop preview:
  extends: .pnpm
  stage: stop
  script:
    - pnpm --filter storybook exec firebase hosting:channel:delete "${CI_COMMIT_REF_SLUG}" --force
  environment:
    name: storybook/preview/${CI_COMMIT_REF_SLUG}
    action: stop
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: manual
