(upflow-vue) test:
  stage: test
  image: ${NODE_IMAGE}
  needs:
    - dependencies
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG =~ /^upflow-vue-v\d+(\.\d+)*$/
    - if: $CI_FORCE_UPFLOW_VUE == "true"
  script:
    - echo "No tests configured!"

(upflow-vue) check version:
  extends: .check version
  variables:
    ROOT_DIR: packages/flow-vue
  rules:
    - if: $CI_COMMIT_TAG =~ /^upflow-vue-v\d+(\.\d+)*$/
    - if: $CI_FORCE_UPFLOW == "true"

(upflow-vue) build:
  stage: build
  image: ${NODE_IMAGE}
  needs:
    - dependencies
    - (upflow-vue) test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG =~ /^upflow-vue-v\d+(\.\d+)*$/
    - if: $CI_FORCE_UPFLOW_VUE == "true"
  artifacts:
    when: on_success
    access: all
    expire_in: "1 day"
    paths:
      - dist/
  script:
    - npm --workspace packages/flow-vue run build

(upflow-vue) publish internal:
  stage: publish internal
  image: ${NODE_IMAGE}
  rules:
    - if: $CI_COMMIT_TAG =~ /^upflow-vue-v\d+(\.\d+)*$/
  needs:
    - dependencies
    - (upflow-vue) build
  script:
    - cd packages/flow-vue
    - export NPM_TOKEN="${CI_JOB_TOKEN}"
    - echo "${INTERNAL_NPMRC}" > .npmrc
    - npm publish

(upflow-vue) publish to npm:
  stage: publish external
  image: ${NODE_IMAGE}
  rules:
    - if: $CI_COMMIT_TAG =~ /^upflow-vue-v\d+(\.\d+)*$/
      when: manual
  needs:
    - dependencies
    - (upflow-vue) build
  script:
    - cd packages/flow-vue
    - npm publish
