variables:
  GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials.json

(docs) build:
  extends: .pnpm
  stage: build
  interruptible: true
  needs:
    - dependencies
  rules:
    - if: $SKIP_BUILD_DOCS == 'true'
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
      allow_failure: true
    - if: $CI_COMMIT_TAG =~ /^docs-v\d+(\.\d+)*$/
    - if: $CI_FORCE_DOCS == "true"
  cache:
    - key:
        files:
          - docs/package.json
          - docs/package-lock.json
      paths:
        - docs/node_modules
  artifacts:
    when: on_success
    access: all
    expire_in: "1 day"
    paths:
      - docs/dist
  script:
    - pnpm --filter docs docs:build

(docs) deploy preview:
  extends: .pnpm
  stage: deploy
  interruptible: true
  needs:
    - dependencies
    - (docs) build
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
  environment:
    name: docs/preview/${CI_COMMIT_REF_SLUG}
    action: start
    auto_stop_in: 7 days
    on_stop: (docs) stop preview
    url: "${FIREBASE_PREVIEW_URL}"
  artifacts:
    reports:
      dotenv: "deploy.env"
  script:
    - apk add jq
    - echo "${DOCS_GCP_SERVICE_ACCOUNT_JSON}" > ${GOOGLE_APPLICATION_CREDENTIALS}
    - pnpm --filter docs exec firebase --non-interactive hosting:channel:deploy "${CI_COMMIT_REF_SLUG}" --expires 7d
  after_script:
    - url=$(pnpm --filter docs exec firebase hosting:channel:list --json | jq -r ".result.channels[] | select(.name | endswith(\"/${CI_COMMIT_REF_SLUG}\")) | .url")
    - echo "FIREBASE_PREVIEW_URL=${url}" > "${CI_PROJECT_DIR}/deploy.env"

(docs) stop preview:
  extends: .pnpm
  stage: stop
  needs:
    - dependencies
  environment:
    name: docs/preview/${CI_COMMIT_REF_SLUG}
    action: stop
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
      when: manual
  script:
    - apk add jq
    - echo "${DOCS_GCP_SERVICE_ACCOUNT_JSON}" > ${GOOGLE_APPLICATION_CREDENTIALS}
    - pnpm --filter docs exec firebase hosting:channel:delete "${CI_COMMIT_REF_SLUG}" --force

(docs) deploy production:
  extends: .pnpm
  stage: deploy
  needs:
    - dependencies
    - (docs) build
  environment:
    name: docs/production
    action: start
    url: https://docs.upmind.dev/
  rules:
    - if: $CI_COMMIT_TAG =~ /^docs-v\d+(\.\d+)*$/
    - if: $CI_FORCE_DOCS == "true"
  script:
    - apk add jq
    - echo "${DOCS_GCP_SERVICE_ACCOUNT_JSON}" > ${GOOGLE_APPLICATION_CREDENTIALS}
    - pnpm --filter docs exec firebase deploy
