export const ukDomain = [
  /* NEW DOMAIN */
  {
    name: ".UK Domain - Billing Cycle - 1 month @webcentral @domains",
    radioSelection: [[0, 0]],
    checkboxSelection: [],
    sldValue: "uktestingdomain",
    registrantName: "Joe Bloggs",
    registrantOrg: "Bloggs Inc",
    registrantEmail: "joebloggs@upmind.com",
    registrantPhone: "+447111111111",
    registrantAddr1: "10 Downing Street",
    registrantCity: "London",
    registrantState: "",
    registrantPostcode: "SW1A",
    registrantCountry: "United Kingdom",
    total: "£2.00",
    billingCycle: "1 month",
    tldValue: ".uk",
  },
  {
    name: ".UK Domain - Billing Cycle - 3 month @webcentral @domains",
    radioSelection: [[0, 1]],
    checkboxSelection: [],
    sldValue: "uktestingdomain",
    registrantName: "Joe Bloggs",
    registrantOrg: "Bloggs Inc",
    registrantEmail: "joebloggs@upmind.com",
    registrantPhone: "+447111111111",
    registrantAddr1: "10 Downing Street",
    registrantCity: "London",
    registrantState: "",
    registrantPostcode: "SW1A",
    registrantCountry: "United Kingdom",
    total: "£2.50",
    billingCycle: "3 month",
    tldValue: ".uk",
  },
  {
    name: ".UK Domain - Billing Cycle - 6 month @webcentral @domains",
    radioSelection: [[0, 2]],
    checkboxSelection: [],
    sldValue: "uktestingdomain",
    registrantName: "Joe Bloggs",
    registrantOrg: "Bloggs Inc",
    registrantEmail: "joebloggs@upmind.com",
    registrantPhone: "+447111111111",
    registrantAddr1: "10 Downing Street",
    registrantCity: "London",
    registrantState: "",
    registrantPostcode: "SW1A",
    registrantCountry: "United Kingdom",
    total: "£4.99",
    billingCycle: "6 month",
    tldValue: ".uk",
  },
  {
    name: ".UK Domain - Billing Cycle - 1 year @webcentral @domains",
    radioSelection: [[0, 3]],
    checkboxSelection: [],
    sldValue: "uktestingdomain",
    registrantName: "Joe Bloggs",
    registrantOrg: "Bloggs Inc",
    registrantEmail: "joebloggs@upmind.com",
    registrantPhone: "+447111111111",
    registrantAddr1: "10 Downing Street",
    registrantCity: "London",
    registrantState: "",
    registrantPostcode: "SW1A",
    registrantCountry: "United Kingdom",
    total: "£9.99",
    billingCycle: "1 year",
    tldValue: ".uk",
  },
  {
    name: ".UK Domain - Billing Cycle - 2 year @webcentral @domains",
    radioSelection: [[0, 4]],
    checkboxSelection: [],
    sldValue: "uktestingdomain",
    registrantName: "Joe Bloggs",
    registrantOrg: "Bloggs Inc",
    registrantEmail: "joebloggs@upmind.com",
    registrantPhone: "+447111111111",
    registrantAddr1: "10 Downing Street",
    registrantCity: "London",
    registrantState: "",
    registrantPostcode: "SW1A",
    registrantCountry: "United Kingdom",
    total: "£19.99",
    billingCycle: "2 year",
    tldValue: ".uk",
  },
  {
    name: ".UK Domain - Billing Cycle - 3 year @webcentral @domains",
    radioSelection: [[0, 5]],
    checkboxSelection: [],
    sldValue: "uktestingdomain",
    registrantName: "Joe Bloggs",
    registrantOrg: "Bloggs Inc",
    registrantEmail: "joebloggs@upmind.com",
    registrantPhone: "+447111111111",
    registrantAddr1: "10 Downing Street",
    registrantCity: "London",
    registrantState: "",
    registrantPostcode: "SW1A",
    registrantCountry: "United Kingdom",
    total: "£29.99",
    billingCycle: "3 year",
    tldValue: ".uk",
  },
  {
    name: ".UK Domain - Billing Cycle - 4 year @webcentral @domains",
    radioSelection: [[0, 6]],
    checkboxSelection: [],
    sldValue: "uktestingdomain",
    registrantName: "Joe Bloggs",
    registrantOrg: "Bloggs Inc",
    registrantEmail: "joebloggs@upmind.com",
    registrantPhone: "+447111111111",
    registrantAddr1: "10 Downing Street",
    registrantCity: "London",
    registrantState: "",
    registrantPostcode: "SW1A",
    registrantCountry: "United Kingdom",
    total: "£39.99",
    billingCycle: "4 year",
    tldValue: ".uk",
  },
  {
    name: ".UK Domain - Billing Cycle - 5 year @webcentral @domains",
    radioSelection: [[0, 7]],
    checkboxSelection: [],
    sldValue: "uktestingdomain",
    registrantName: "Joe Bloggs",
    registrantOrg: "Bloggs Inc",
    registrantEmail: "joebloggs@upmind.com",
    registrantPhone: "+447111111111",
    registrantAddr1: "10 Downing Street",
    registrantCity: "London",
    registrantState: "",
    registrantPostcode: "SW1A",
    registrantCountry: "United Kingdom",
    total: "£49.99",
    billingCycle: "5 year",
    tldValue: ".uk",
  },
  {
    name: ".UK Domain - Billing Cycle - 6 year @webcentral @domains",
    radioSelection: [[0, 8]],
    checkboxSelection: [],
    sldValue: "uktestingdomain",
    registrantName: "Joe Bloggs",
    registrantOrg: "Bloggs Inc",
    registrantEmail: "joebloggs@upmind.com",
    registrantPhone: "+447111111111",
    registrantAddr1: "10 Downing Street",
    registrantCity: "London",
    registrantState: "",
    registrantPostcode: "SW1A",
    registrantCountry: "United Kingdom",
    total: "£59.99",
    billingCycle: "6 year",
    tldValue: ".uk",
  },
  {
    name: ".UK Domain - Billing Cycle - 7 year @webcentral @domains",
    radioSelection: [[0, 9]],
    checkboxSelection: [],
    sldValue: "uktestingdomain",
    registrantName: "Joe Bloggs",
    registrantOrg: "Bloggs Inc",
    registrantEmail: "joebloggs@upmind.com",
    registrantPhone: "+447111111111",
    registrantAddr1: "10 Downing Street",
    registrantCity: "London",
    registrantState: "",
    registrantPostcode: "SW1A",
    registrantCountry: "United Kingdom",
    total: "£69.99",
    billingCycle: "7 year",
    tldValue: ".uk",
  },
  {
    name: ".UK Domain - Billing Cycle - 8 year @webcentral @domains",
    radioSelection: [[0, 10]],
    checkboxSelection: [],
    sldValue: "uktestingdomain",
    registrantName: "Joe Bloggs",
    registrantOrg: "Bloggs Inc",
    registrantEmail: "joebloggs@upmind.com",
    registrantPhone: "+447111111111",
    registrantAddr1: "10 Downing Street",
    registrantCity: "London",
    registrantState: "",
    registrantPostcode: "SW1A",
    registrantCountry: "United Kingdom",
    total: "£79.99",
    billingCycle: "8 year",
    tldValue: ".uk",
  },
  {
    name: ".UK Domain - Billing Cycle - 9 year @webcentral @domains",
    radioSelection: [[0, 11]],
    checkboxSelection: [],
    sldValue: "uktestingdomain",
    registrantName: "Joe Bloggs",
    registrantOrg: "Bloggs Inc",
    registrantEmail: "joebloggs@upmind.com",
    registrantPhone: "+447111111111",
    registrantAddr1: "10 Downing Street",
    registrantCity: "London",
    registrantState: "",
    registrantPostcode: "SW1A",
    registrantCountry: "United Kingdom",
    total: "£89.99",
    billingCycle: "9 year",
    tldValue: ".uk",
  },
  {
    name: ".UK Domain - Billing Cycle - 10 year @webcentral @domains",
    radioSelection: [[0, 12]],
    checkboxSelection: [],
    sldValue: "uktestingdomain",
    registrantName: "Joe Bloggs",
    registrantOrg: "Bloggs Inc",
    registrantEmail: "joebloggs@upmind.com",
    registrantPhone: "+447111111111",
    registrantAddr1: "10 Downing Street",
    registrantCity: "London",
    registrantState: "",
    registrantPostcode: "SW1A",
    registrantCountry: "United Kingdom",
    total: "£99.99",
    billingCycle: "10 year",
    tldValue: ".uk",
  },

  /* TRANSFERRING A DOMAIN */
  {
    name: ".UK Domain - Billing Cycle - 10 year - Domain Transfer @webcentral @domains @domain-transfer",
    radioSelection: [[0, 12]],
    checkboxSelection: [[0, 0]],
    sldValue: "uktestingdomain",
    registrantName: "Joe Bloggs",
    registrantOrg: "Bloggs Inc",
    registrantEmail: "joebloggs@upmind.com",
    registrantPhone: "+447111111111",
    registrantAddr1: "10 Downing Street",
    registrantCity: "London",
    registrantState: "",
    registrantPostcode: "SW1A",
    registrantCountry: "United Kingdom",
    total: "FREE",
    billingCycle: "10 year",
    tldValue: ".uk",
    domainSetup: "Transfer",
  },
];
