//  --- external
import { spawn } from "xstate";

// --- internal
import itemMachine from "../item.machine";
import { ItemActions as actions } from "./actions";
import services from "./services";

// --- utils
import {
  get,
  set,
  map,
  reduce,
  defaultsDeep,
  uniqueId,
  compact,
  isArray,
} from "lodash-es";

// --- types
// @ts-ignore
import type { IAddress, AddressContext } from "./types";
import type { JsonSchema, UISchemaElement } from "@jsonforms/core";

// --------------------------------------------------------

export const useSchema = ({
  country,
  countries,
  regions,
  types,
  baseModel,
  // ---
  places,
  emails,
}: AddressContext) => {
  const schema = {
    type: "object",
    title: "Address Fields",
    required: ["address1", "city", "countryId", "postcode", "type"],
    // --- conditionally required fields
    if: {
      properties: {
        companyDetails: { const: true },
      },
      required: ["companyDetails"],
    },
    then: { required: ["companyName", "email", "regNumber"] },
    // ---
    properties: {
      id: {
        type: ["string", "null"],
        title: "ID",
        description: "The AutoGenerated ID of this Unified Address.",
        readOnly: true,
      },

      companyId: {
        type: ["string", "null"],
        title: "ID",
        description: "The AutoGenerated ID of the Company.",
        readOnly: true,
      },

      addressId: {
        type: ["string", "null"],
        title: "ID",
        description: "The AutoGenerated ID of the Address.",
        readOnly: true,
      },

      // ---

      place: {
        type: ["string", "null"],
        title: "Address",
        lookup: places?.search,
        // default: baseModel?.companyDetails && baseModel?.place,
      },

      manualPlace: {
        type: ["boolean", "null"],
        title: "Can't see your address?",
        default: baseModel?.manualPlace,
        readOnly: true,
      },

      // ---

      name: {
        type: ["string", "null"],
        title: "Address Name",
        default: baseModel?.name,
      },

      address1: {
        type: "string",
        title: "Address Line 1",
      },

      address2: {
        type: ["string", "null"],
        title: "Address Line 2",
      },

      city: {
        type: "string",
        title: "City",
      },

      postcode: {
        type: "string",
        title: "Postcode",
      },

      regionId: {
        type: ["string", "null"],
        title: "Region",
        oneOf: !regions?.length
          ? undefined
          : map(regions, item => {
              return {
                const: item.id,
                title: item.name,
              };
            }),
      },

      // not sure this is ever used, but it is in the type definition
      state: {
        type: ["string", "null"],
        title: "State",
      },

      countryId: {
        type: "string",
        title: "Country",
        default: baseModel?.country_id,
        oneOf: !countries?.length
          ? undefined
          : map(countries, item => {
              return {
                const: item.id,
                title: item.name,
              };
            }),
      },

      // ---

      companyDetails: {
        type: ["boolean", "null"],
        title: "Add business details",
        default: baseModel?.companyDetails,
      },

      companyName: {
        type: ["string", "null"],
        title: "Name",
      },

      email: {
        type: ["string", "null"],
        title: "Email",
        format: "email",
        default: baseModel.email,
        lookup: emails?.search,
      },

      phone: {
        type: ["object", "null"],
        title: "Phone",
        isPhoneNumber: country?.code,
        properties: {
          number: {
            type: ["string", "null"],
            title: "Phone number ( with dailing code )",
            default: baseModel?.phone?.number,
          },

          nationalNumber: {
            type: ["string", "null"],
            title: "Phone number",
            default: baseModel?.phone?.nationalNumber,
          },

          countryCallingCode: {
            type: ["string", "null"],
            title: "Country calling code",
            default: baseModel?.phone?.nationalCallingCode,
          },

          country: {
            type: ["string", "null"],
            title: "Country",
            default: baseModel?.phone?.country,
          },
        },
      },

      regNumber: {
        type: ["string", "null"],
        title: "Registration number",
      },

      vatNumber: {
        type: ["string", "null"],
        title: "Registered tax/VAT id",
      },

      // vatPercent: {
      //   type: ["string", "null"],
      //   title: "VAT percent",
      // },
      // ---

      default: {
        type: ["boolean", "null"],
        title: "Make this the default address?",
      },

      type: {
        type: "number",
        title: "Address Type",
        default: baseModel?.type,
        oneOf: !types?.length
          ? undefined
          : map(types, item => {
              return {
                const: item.key,
                title: item.value,
              };
            }),
      },
    },
  };

  // if (id) {
  //   schema.required.push("name");
  //   schema.required.push("type");
  // }

  return schema as JsonSchema;
};

export const useUischema = ({ addresses, emails, phones }: any) => {
  const lookups = {
    addresses: reduce(
      addresses.getItems(),
      (result, item) => {
        // Only return actual addresses, NOT companies
        if (!item?.companyDetails) {
          // @ts-ignore
          result.push({
            value: item.id,
            label: [
              item.name,
              item.address1,
              item.address2,
              item.city,
              item.postcode,
            ].join(", "),
          });
        }

        return result;
      },
      []
    ),

    emails: emails.getItems(),
    phones: phones.getItems(),
  };

  const schema = {
    type: "VerticalLayout",
    elements: [
      {
        // --- address details
        type: "VerticalLayout",
        elements: [
          {
            type: "Control",
            scope: "#/properties/name",
            options: {
              autoFocus: true,
              autocomplete: "off",
              placeholder: "My home address, etc...",
            },
            rule: {
              effect: "DISABLE",
              condition: {
                scope: "#",
                schema: {
                  anyOf: [
                    {
                      required: ["id", "companyDetails"],
                      properties: { companyDetails: { const: true } },
                    },
                  ],
                },
              },
            },
          },
        ],
        rule: {
          effect: "SHOW",
          condition: {
            scope: "#",
            schema: {
              required: ["id"],
            },
          },
        },
      },

      {
        // --- address details
        type: "VerticalLayout",
        elements: [
          // ---
          {
            type: "Control",
            scope: "#/properties/place",
            i18n: "client.unified.form.fields.place",
            options: {
              autoFocus: true,
              icon: "search",
              autocomplete: "off",
              align: "start",
              side: "bottom",
              placeholder: "Search for address ...",
              items: compact([
                lookups.addresses?.length
                  ? {
                      label: "Your saved addreses",
                      i18n: "client.unified.form.fields.saved",
                      as: "separator",
                    }
                  : null,
                ...lookups.addresses,
                // {
                //   label: "Enter manually",
                //   i18n: "client.unified.form.fields.manual",
                //   value: "manual",
                //   as: "button",
                //   variant: "link",
                //   size: "sm",
                //   persist: true,
                // },
              ]),
            },
            rule: {
              effect: "HIDE",
              condition: {
                scope: "#",
                schema: {
                  anyOf: [
                    { required: ["id"] },
                    {
                      required: ["place"],
                      properties: { place: { const: "manual" } },
                    },
                  ],
                },
              },
            },
          },

          // ---
          {
            type: "VerticalLayout",
            elements: [
              {
                type: "Control",
                scope: "#/properties/address1",
                i18n: "client.unified.form.fields.address1",
                options: {
                  autocomplete: "address-line1",
                },
              },
              {
                type: "Control",
                scope: "#/properties/address2",
                i18n: "client.unified.form.fields.address2",
                options: {
                  autocomplete: "address-line2",
                },
              },

              // ---
              {
                type: "HorizontalLayout",
                elements: [
                  {
                    type: "Control",
                    scope: "#/properties/city",
                    i18n: "client.unified.form.fields.city",
                    options: {
                      autocomplete: "address-level2",
                    },
                  },
                  {
                    type: "Control",
                    scope: "#/properties/postcode",
                    i18n: "client.unified.form.fields.postcode",
                    options: {
                      autocomplete: "postal-code",
                    },
                  },
                ],
              },
              // ---
              {
                type: "Control",
                scope: "#/properties/regionId",
                i18n: "client.unified.form.fields.regionId",
                options: {
                  autocomplete: "address-level1",
                  placeholder: "Please select a Region...",
                },
              },
              {
                type: "Control",
                scope: "#/properties/countryId",
                i18n: "client.unified.form.fields.countryId",
                options: {
                  autocomplete: "country",
                  placeholder: "Please select a Country...",
                },
              },
            ],
            // rule: {
            //   effect: "SHOW",
            //   condition: {
            //     scope: "#/properties/manualPlace",
            //     schema: { const: true },
            //   },
            // },
          },
        ],
        rule: {
          effect: "HIDE",
          condition: {
            scope: "#",
            schema: {
              anyOf: [
                {
                  required: ["id", "companyDetails"],
                  properties: { companyDetails: { const: true } },
                },
              ],
            },
          },
        },
      },

      // --- company details
      {
        type: "Control",
        scope: "#/properties/companyDetails",
        i18n: "client.unified.form.fields.companyDetails",
        rule: {
          effect: "SHOW",
          condition: {
            scope: "#",
            schema: {
              // properties: { companyDetails: { not: { const: true } } },
              anyOf: [
                {
                  required: ["id"],
                  properties: { companyId: { const: null } },
                },
                {
                  required: ["name"],
                  properties: { companyId: { const: null } },
                },
                {
                  properties: {
                    manualPlace: { const: true },
                    companyId: { const: null },
                  },
                },
              ],
            },
          },
        },
      },

      {
        type: "VerticalLayout",
        elements: [
          {
            type: "Control",
            scope: "#/properties/companyName",
            i18n: "client.unified.form.fields.companyName",
            options: {
              autoFocus: true,
              autocomplete: "organization",
              placeholder: "My Company Name (PTY) LTD",
              label: "Company Name",
            },
          },
          {
            type: "HorizontalLayout",
            elements: [
              {
                type: "Control",
                scope: "#/properties/regNumber",
                i18n: "client.unified.form.fields.regNumber",
                options: {},
              },
              {
                type: "Control",
                scope: "#/properties/vatNumber",
                i18n: "client.unified.form.fields.vatNumber",
                options: {},
              },
            ],
          },
          {
            type: "Control",
            scope: "#/properties/email",
            i18n: "client.unified.form.fields.email",
            options: {
              suggestions: true,
              autocomplete: "email",
              itemLabel: "email",
              itemValue: "email",
              items: lookups.emails,
              align: "start",
              side: "bottom",
            },
          },
          {
            type: "Control",
            scope: "#/properties/phone",
            i18n: "client.unified.form.fields.phone",
            options: {
              autocomplete: "tel",
              suggestions: true,
              itemLabel: "number",
              itemValue: "number",
              items: lookups.phones,
              align: "start",
              side: "bottom",
            },
          },
        ],
        rule: {
          effect: "SHOW",
          condition: {
            scope: "#/properties/companyDetails",
            schema: { const: true },
          },
        },
      },

      // ---
      // We dont ever show this field as it is set by an action
      // {
      //   type: "Control",
      //   scope: "#/properties/default",
      //   options: {
      //     // toggle: true
      //   }
      // }
    ],
  };

  return schema as UISchemaElement;
};

export const useModelParser = (
  schema: JsonSchema,
  values: IAddress,
  baseModel?: IAddress
) => {
  const model = reduce(
    schema.properties,
    (result, field, key) => {
      const value =
        field?.const || get(values, key, field?.default || get(baseModel, key));
      set(result, key, value);
      return result;
    },
    {}
  );

  return defaultsDeep(model, values) as IAddress;
};

// --------------------------------------------------------

export const spawnItem = (model?: IAddress) => {
  try {
    const name = get(model, "id", uniqueId("item_"));
    return spawn(
      itemMachine
        .withConfig({
          // @ts-ignore
          actions,
          // @ts-ignore
          services,
        })
        .withContext({ model }),
      {
        name,
        sync: true,
      }
    );
  } catch (err) {
    // console.error("AddressListings", "spawnItem", { model });
  }
};

export const parseAddress = (raw: IAddress | Array<IAddress>) => {
  // we could get a plain address OR a company with and address
  // so we normalize the data to always be an array of addresses
  // this is to allow for a 'unfied' way of handling addresses
  const rawListings = isArray(raw) ? raw : [raw];

  return map(rawListings, rawItem => {
    // 1 check if we have  companyDetails or just an address
    if (rawItem?.address) {
      const mappedItem = {
        id: rawItem?.id,
        clientId: rawItem?.client_id,
        addressId: rawItem?.address.id, // add the address id as the unified id representing the actual address
        companyId: rawItem?.id, // add the company id as the unified id representing the actual address
        companyDetails: true, // our flag to show company details
        companyName: rawItem?.name,
        // ---
        name: rawItem?.address?.name,
        address1: rawItem?.address?.address_1,
        address2: rawItem?.address?.address_2,
        city: rawItem?.address?.city,
        postcode: rawItem?.address?.postcode,
        regionId: rawItem?.address?.region_id,
        countryId: rawItem?.address?.country_id,
        // ---
        email: rawItem?.email?.email,
        phone: {
          number: rawItem?.phone?.number,
          nationalNumber: rawItem?.phone?.national_number,
          countryCallingCode: rawItem?.phone?.country_calling_code,
          country: rawItem?.phone?.country,
        },
        regNumber: rawItem?.reg_number,
        vatNumber: rawItem?.vat_number,
        // ---
        type: rawItem?.type || 4, // default to 4 = company
        default: rawItem?.default,
        canDelete: rawItem?.can_delete,
        verified: rawItem?.verified,

        // vatPercent: item?.vatPercent,
      };
      return mappedItem;
    } else {
      const mappedItem: any = {
        id: rawItem.id,
        clientId: rawItem.client_id,
        addressId: rawItem.id,
        companyId: null,
        companyDetails: false,
        companyName: null,
        // ---
        name: rawItem.name,
        address1: rawItem.address_1,
        address2: rawItem.address_2,
        city: rawItem.city,
        postcode: rawItem.postcode,
        regionId: rawItem.region_id,
        countryId: rawItem.country_id,
        // ---
        default: rawItem.default,
        type: rawItem.type,
        canDelete: rawItem.can_delete,
        verified: rawItem.verified,
      };
      // mappedItem.place = null;
      return mappedItem;
    }
  });
};
