import { compact, get, map, reduce } from "lodash-es";

import { AddressTypes } from "./types";
import type { Address, AddressContext } from "./types";
import type { JsonSchema7, UISchemaElement } from "@jsonforms/core";
import { BrandConfigKeys } from "@upmind-automation/types";
import { title } from "process";

export function useSchemaDefinitions({
  regions,
  baseModel,
  countries,
  config
}: Partial<AddressContext>): JsonSchema7["definitions"] {
  const schema = {
    address: {
      type: "object",
      title: "Address",
      required: ["address1", "city", "postcode", "countryId"],
      properties: {
        address1: {
          type: ["string"],
          title: "Address"
        },

        address2: {
          type: ["string", "null"],
          title: ""
        },

        city: {
          type: "string",
          title: "City"
        },

        postcode: {
          type: "string",
          title: "Postcode"
        },

        regionId: {
          type: ["string", "null"],
          title: "Region",
          oneOf: !regions?.length
            ? undefined
            : map(regions, item => ({
                const: item.id,
                title: item.name
              }))
        },

        countryId: {
          type: "string",
          title: "Country",
          default: baseModel?.countryId,
          oneOf: !countries?.length
            ? undefined
            : map(countries, item => ({
                const: item.id,
                title: item.name
              }))
        }
      }
    }
  };

  // ensure we honor the brand config
  if (get(config, BrandConfigKeys.REQUIRE_REGION_IN_ADDRESS)) {
    schema.address.required.push("regionId");
  }

  return schema;
}

export function useSchema({
  id,
  baseModel,
  config,
  countries,
  regions
}: AddressContext): JsonSchema7 {
  const schema: JsonSchema7 = {
    type: "object",
    title: "Address",
    required: ["address"],
    definitions: useSchemaDefinitions({
      config,
      countries,
      regions,
      baseModel
    }),
    properties: {
      id: {
        type: ["string", "null"],
        title: "ID",
        description: "The AutoGenerated ID of this Address.",
        readOnly: true
      },

      name: {
        type: ["string", "null"],
        title: "Name",
        default: baseModel?.name
      },

      address: { $ref: "#/definitions/address" }

      // --- DEPRECATED
      // type: {
      //   type: "number",
      //   title: "Address Type",
      //   default: baseModel?.type,
      //   oneOf: !AddressTypes?.length
      //     ? undefined
      //     : map(AddressTypes, item => ({
      //         const: item.key,
      //         title: item.value
      //       }))
      // }
    }
  };

  // ensure that id we are editing an existing address, that we require the name
  if (id) {
    schema.required!.push("name");
  }

  return schema;
}

export function useUischemaDefinitions({ id }: Partial<AddressContext> = {}) {
  return {
    type: "Control",
    scope: "#/properties/address",
    options: {
      autoFocus: true,
      autocomplete: "off",
      detail: {
        type: "VerticalLayout",
        elements: [
          {
            type: "Control",
            scope: "#/properties/countryId",
            options: {
              placeholder: "Please select a Country..."
            }
          },
          // ---
          {
            type: id ? "VerticalLayout" : "address",
            options: {
              fields: ["address1", "address2"],
              placeholder: "Start typing your address",
              autoFocus: true
            },
            elements: [
              {
                type: "Group",
                options: {
                  border: false
                },
                elements: [
                  {
                    type: "Control",
                    scope: "#/properties/address1",
                    options: {
                      placeholder: "House name, apartment number etc.",
                      autocomplete: "address-line1",
                      autoFocus: true
                    }
                  },
                  {
                    type: "Control",
                    scope: "#/properties/address2",
                    options: {
                      placeholder: "Road, street name etc.",
                      autocomplete: "address-line2"
                    }
                  }
                ]
              },
              {
                type: "Control",
                scope: "#/properties/city",
                options: {
                  placeholder: "City, town etc.",
                  autocomplete: "address-level2"
                }
              },
              {
                type: "HorizontalLayout",
                elements: [
                  {
                    type: "Control",
                    scope: "#/properties/regionId",
                    options: {
                      placeholder: "Select region",
                      autocomplete: "address-level1"
                    }
                  },
                  {
                    type: "Control",
                    scope: "#/properties/postcode",
                    options: {
                      placeholder: "eg. 10011",
                      autocomplete: "postal-code"
                    }
                  }
                ]
              }
            ]
          }
        ]
      }
    }
  };
}

export function useUischema({
  id
}: Partial<AddressContext> = {}): UISchemaElement {
  const schema = {
    type: "VerticalLayout",
    elements: [useUischemaDefinitions({ id })]
  };

  return schema as UISchemaElement;
}
