import { compact, map, reduce } from "lodash-es";

import type { Address, AddressContext } from "./types";
import type { JsonSchema, UISchemaElement } from "@jsonforms/core";

export function useSchema({
  types,
  regions,
  baseModel,
  countries,
}: AddressContext): JsonSchema {
  const schema = {
    type: "object",
    title: "Address Fields",
    required: ["address1", "city", "countryId", "postcode", "type"],
    properties: {
      id: {
        type: ["string", "null"],
        title: "ID",
        description: "The AutoGenerated ID of this Address.",
        readOnly: true,
      },

      address: {
        type: "object",
        title: "Address",
        default: {},
        properties: {
          address1: {
            type: "string",
            title: "Address Line 1",
          },

          address2: {
            type: ["string", "null"],
            title: "Address Line 2",
          },

          city: {
            type: "string",
            title: "City",
          },

          postcode: {
            type: "string",
            title: "Postcode",
          },

          regionId: {
            type: ["string", "null"],
            title: "Region",
            oneOf: !regions?.length
              ? undefined
              : map(regions, item => ({
                  const: item.id,
                  title: item.name,
                })),
          },

          countryId: {
            type: "string",
            title: "Country",
            default: baseModel?.countryId,
            oneOf: !countries?.length
              ? undefined
              : map(countries, item => ({
                  const: item.id,
                  title: item.name,
                })),
          },
        },
      },

      // ---

      name: {
        type: ["string", "null"],
        title: "Name",
        default: baseModel?.name,
      },

      type: {
        type: "number",
        title: "Address Type",
        default: baseModel?.type,
        oneOf: !types?.length
          ? undefined
          : map(types, item => ({
              const: item.key,
              title: item.value,
            })),
      },
    },
  };

  // if (id) {
  //   schema.required.push("name");
  //   schema.required.push("type");
  // }

  return schema as JsonSchema;
}

export function useUischema(): UISchemaElement {
  const schema = {
    type: "VerticalLayout",
    elements: [
      {
        type: "Control",
        scope: "#/properties/address",
        options: {
          autoFocus: true,
          autocomplete: "off",
          detail: {
            type: "VerticalLayout",
            elements: [
              {
                type: "Control",
                scope: "#/properties/countryId",
              },
              {
                type: "address",
                options: {
                  fields: ["address1", "address2", "city", "postcode"],
                  placeholder: "Search for an address...",
                },
                elements: [
                  {
                    type: "Control",
                    scope: "#/properties/address1",
                  },
                  {
                    type: "Control",
                    scope: "#/properties/address2",
                  },
                  {
                    type: "Control",
                    scope: "#/properties/city",
                  },
                  {
                    type: "Control",
                    scope: "#/properties/postcode",
                  },
                ],
              },
            ],
          },
        },
      },
    ],
  };

  return schema as UISchemaElement;
}
