//  --- external
import { spawn } from "xstate";

// --- internal
import itemMachine from "../item.machine";
import { ItemActions as actions } from "./actions";
import services from "./services";

// --- utils
import {
  get,
  set,
  map,
  reduce,
  defaultsDeep,
  uniqueId,
  compact,
  // pick,
  isArray,
} from "lodash-es";

// --- types
import type { IAddress } from "@upmind-automation/types";
import type { JsonSchema, UISchemaElement } from "@jsonforms/core";
import type { AddressContext } from "./types";

// -----------------------------------------------------------------------------

export function useSchema({
  // TODO: country,
  countries,
  regions,
  types,
  baseModel,
  // ---
  places,
  // }: AddressContext) => {
}: any): JsonSchema {
  const schema = {
    type: "object",
    title: "Address Fields",
    required: ["address1", "city", "countryId", "postcode", "type"],
    properties: {
      id: {
        type: ["string", "null"],
        title: "ID",
        description: "The AutoGenerated ID of this Address.",
        readOnly: true,
      },

      // ---

      place: {
        type: ["string", "null"],
        title: "Address",
        lookup: places?.search,
      },

      manualPlace: {
        type: ["boolean", "null"],
        title: "Can't see your address?",
        default: baseModel?.manualPlace,
        readOnly: true,
      },

      // ---
      address1: {
        type: "string",
        title: "Address Line 1",
      },

      address2: {
        type: ["string", "null"],
        title: "Address Line 2",
      },

      city: {
        type: "string",
        title: "City",
      },

      postcode: {
        type: "string",
        title: "Postcode",
      },

      regionId: {
        type: ["string", "null"],
        title: "Region",
        oneOf: !regions?.length
          ? undefined
          : map(regions, item => {
              return {
                const: item.id,
                title: item.name,
              };
            }),
      },

      // not sure this is ever used, but it is in the type definition
      state: {
        type: ["string", "null"],
        title: "State",
      },

      countryId: {
        type: "string",
        title: "Country",
        default: baseModel?.countryId,
        oneOf: !countries?.length
          ? undefined
          : map(countries, item => {
              return {
                const: item.id,
                title: item.name,
              };
            }),
      },

      // ---

      name: {
        type: ["string", "null"],
        title: "Name",
        default: baseModel?.name,
      },
      // ---

      default: {
        type: ["boolean", "null"],
        title: "Make this the default address?",
      },

      type: {
        type: "number",
        title: "Address Type",
        default: baseModel?.type,
        oneOf: !types?.length
          ? undefined
          : map(types, item => {
              return {
                const: item.key,
                title: item.value,
              };
            }),
      },
    },
  };

  // if (id) {
  //   schema.required.push("name");
  //   schema.required.push("type");
  // }

  return schema as JsonSchema;
}

export function useUischema({ addresses }: AddressContext): UISchemaElement {
  const lookups = {
    addresses: reduce(
      addresses.getItems(),
      (result: any[], item) => {
        // Only return actual addresses, NOT companies
        if (!item?.companyDetails) {
          result.push({
            value: item.id,
            label: [
              item.name,
              item.address1,
              item.address2,
              item.city,
              item.postcode,
            ].join(", "),
          });
        }

        return result;
      },
      []
    ),
  };

  const schema = {
    type: "VerticalLayout",
    elements: [
      {
        type: "Control",
        scope: "#/properties/name",
        options: {
          autoFocus: true,
          autocomplete: "off",
          placeholder: "My home address, etc...",
        },
        rule: {
          effect: "SHOW",
          condition: {
            scope: "#",
            schema: {
              required: ["id"],
            },
          },
        },
      },

      // ---
      {
        type: "Control",
        scope: "#/properties/place",
        i18n: "client.unified.form.fields.place",
        options: {
          autoFocus: true,
          icon: "search",
          autocomplete: "off",
          align: "start",
          side: "bottom",
          placeholder: "Search for address ...",
          items: compact([
            lookups.addresses?.length
              ? {
                  label: "Your saved addreses",
                  i18n: "client.unified.form.fields.saved",
                  as: "separator",
                }
              : null,
            ...lookups.addresses,
            // {
            //   label: "Enter manually",
            //   i18n: "client.unified.form.fields.manual",
            //   value: "manual",
            //   as: "button",
            //   variant: "link",
            //   size: "sm",
            //   persist: true,
            // },
          ]),
        },
        rule: {
          effect: "HIDE",
          condition: {
            scope: "#",
            schema: {
              anyOf: [
                { required: ["id"] },
                {
                  required: ["place"],
                  properties: { place: { const: "manual" } },
                },
              ],
            },
          },
        },
      },

      // ---
      {
        type: "VerticalLayout",
        elements: [
          {
            type: "Control",
            scope: "#/properties/address1",
            label: "Address", // ensure we  show the title for BOTH address fields
            options: {
              autoFocus: true,
              autocomplete: "address-line1",
              placeholder: "Address first line...",
            },
          },
          {
            type: "Control",
            scope: "#/properties/address2",
            label: "", // ensure we DON'T show the title
            options: {
              autocomplete: "address-line2",
              placeholder: "Address second line...",
              class: "-mt-8",
            },
          },

          // ---
          {
            type: "HorizontalLayout",
            elements: [
              {
                type: "Control",
                scope: "#/properties/city",
                options: {
                  autocomplete: "address-level2",
                  placeholder: "City...",
                },
              },
              {
                type: "Control",
                scope: "#/properties/postcode",
                options: {
                  autocomplete: "postal-code",
                  placeholder: "Postcode...",
                },
              },
            ],
          },
          // ---
          {
            type: "Control",
            scope: "#/properties/regionId",
            options: {
              autocomplete: "address-level1",
              placeholder: "Please select a Region...",
            },
          },
          {
            type: "Control",
            scope: "#/properties/countryId",
            options: {
              autocomplete: "country",
              placeholder: "Please select a Country...",
            },
          },
        ],
        rule: {
          effect: "SHOW",
          condition: {
            scope: "#/properties/manualPlace",
            schema: { const: true },
          },
        },
      },

      // ---
      // We dont ever show this field as it is set by an action
      // {
      //   type: "Control",
      //   scope: "#/properties/default",
      //   options: {
      //     // toggle: true
      //   }
      // }
    ],
  };

  return schema as UISchemaElement;
}

export const useModelParser = (
  schema: JsonSchema,
  values: IAddress,
  baseModel?: IAddress
) => {
  const model = reduce(
    schema.properties,
    (result, field, key) => {
      const value =
        field?.const || get(values, key, field?.default || get(baseModel, key));
      set(result, key, value);
      return result;
    },
    {}
  );

  return defaultsDeep(model, values) as IAddress;
};

// -----------------------------------------------------------------------------

export const spawnItem = (model?: IAddress) => {
  try {
    const name = get(model, "id", uniqueId("item_"));
    return spawn(
      itemMachine
        .withConfig({
          actions: actions as any,
          services: services as any,
        })
        .withContext({ model }),
      {
        name,
        sync: true,
      }
    );
  } catch (err) {
    console.error("AddressListings", "spawnItem", { model });
    return null;
  }
};

export const parseAddress = (raw: IAddress | Array<IAddress>) => {
  // we could get a plain address OR a company with and address
  // so we normalize the data to always be an array of addresses
  // this is to allow for a 'unfied' way of handling addresses
  const rawListings = isArray(raw) ? raw : [raw];
  return map(rawListings, rawItem => {
    const mappedItem: any = {
      id: rawItem.id,
      clientId: rawItem.client_id,
      addressId: rawItem.id,
      companyId: null,
      companyDetails: false,
      companyName: null,
      // ---
      name: rawItem.name,
      address1: rawItem.address_1,
      address2: rawItem.address_2,
      city: rawItem.city,
      postcode: rawItem.postcode,
      regionId: rawItem.region_id,
      countryId: rawItem.country_id,
      // ---
      default: rawItem.default,
      type: rawItem.type,
      canDelete: rawItem.can_delete,
      verified: rawItem.verified,
    };
    // mappedItem.place = null;
    return mappedItem;
  });
};
