import type { cva } from "class-variance-authority"; // If you have a type for cva, otherwise use `any`

// -----------------------------------------------------------------------------

/**
 * Represents a configuration value for a UI theme. This can be a direct value
 * (e.g. a string for a CSS class generated by `cva`, or a colour code),
 * or a nested object representing a configuration for a specific component or part of a component.
 *
 * @template T - The type of the configuration value.
 */
export type ThemeConfigValue =
  | ReturnType<typeof cva> // Assumes cva returns an object with a variant property or similar structure.
  | { [component: string]: ThemeConfigValue }; // Allows for nested configurations.

/**
 * Interface representing the overall theme configuration, mapping component names
 * to their respective {@link ThemeConfigValue} settings. This allows for granular
 * styling of different parts of the UI.
 *
 * @example
 * ```ts
 * {
 *   button: {
 *     variants: { intent: 'primary', size: 'medium' },
 *     colour: 'blue'
 *   },
 *   input: {
 *     border: { colorInput: '#CCCCCC' }
 *   }
 * }
 * ```
 */
export interface ThemeConfig {
  /**
   * A key-value map where keys are component identifiers (e.g. "button", "input")
   * and values are their configurations (either direct values or nested objects).
   */
  [component: string]: ThemeConfigValue;
}

/**
 * Interface representing theme tokens, which are the fundamental design system values
 * like colours, typography, spacing, and border radii. These are typically inferred
 * from a `tokens.json` file or a design system definition.
 */
export interface ThemeTokens {
  /** Typography settings for different text styles. */
  fonts?: {
    /** Default sans-serif font. */
    sans?: string;
    /** Primary font for body text. */
    body?: string;
    /** Primary font for headings and display text. */
    display?: string;
  };
  button?: {
    radius: string;
  };
  control?: {
    radius: string;
  };
  badge?: {
    radius: string;
  };
  image?: {
    radius: string;
  };
  card?: {
    radius: string;
  };
  message?: {
    radius: string;
  };
  stroke?: {
    icon: string;
    badge: string;
  };
  color?: {
    primary: string;
    secondary: string;

    primitive: {
      core: {
        canvas: string;
        surface: string;
        base: string;
        display: string;
        faint: string;
        muted: string;
        skeleton: string;
        overlay: string;
      };

      control: {
        default: string;
        defaultDelta: string;
        defaultContrast: string;
        muted: string;
        mutedContrast: string;
        stroke: string;
        strokeDelta: string;
      };

      primary: {
        default: string;
        defaultStop: string;
        defaultDelta: string;
        defaultContrast: string;
        muted: string;
        mutedContrast: string;
      };

      secondary: {
        default: string;
        defaultStop: string;
        defaultDelta: string;
        defaultContrast: string;
      };

      neutral: {
        default: string;
        defaultDelta: string;
        defaultContrast: string;
        muted: string;
        mutedDelta: string;
        mutedContrast: string;
        stroke: string;
        strokeDelta: string;
      };

      promo: {
        default: string;
        defaultContrast: string;
        muted: string;
        mutedContrast: string;
      };

      danger: {
        default: string;
        defaultDelta: string;
        defaultContrast: string;
        muted: string;
        mutedContrast: string;
      };

      warning: {
        default: string;
        defaultContrast: string;
        muted: string;
        mutedContrast: string;
      };

      success: {
        default: string;
        defaultContrast: string;
        muted: string;
        mutedContrast: string;
      };

      info: {
        default: string;
        defaultContrast: string;
        muted: string;
        mutedContrast: string;
      };
    };

    background: {
      canvas: string;
      surface: string;
      surfaceGlass: string;
      skeleton: string;
      overlay: string;

      accent: {
        primary: string;
        primaryMuted: string;
        neutral: string;
        neutralMuted: string;
        promo: string;
        promoMuted: string;
        danger: string;
        dangerMuted: string;
        warning: string;
        warningMuted: string;
        success: string;
        successMuted: string;
        info: string;
        infoMuted: string;
      };

      button: {
        primaryRing: string;
        primary0: string;
        primary1: string;
        primaryHover0: string;
        primaryHover1: string;
        secondaryRing: string;
        secondary0: string;
        secondary1: string;
        secondaryHover0: string;
        secondaryHover1: string;
        neutralRing: string;
        neutral0: string;
        neutral1: string;
        neutralHover0: string;
        neutralHover1: string;
        subtleRing: string;
        subtle0: string;
        subtle1: string;
        subtleHover0: string;
        subtleHover1: string;
        dangerRing: string;
        danger0: string;
        danger1: string;
        dangerHover0: string;
        dangerHover1: string;
        outline: string;
        outlineHover: string;
        outlineRing: string;
        ghost: string;
        ghostHover: string;
        ghostRing: string;
      };

      control: {
        checked: string;
        checkedHover: string;
        checkedContrast: string;
        unchecked: string;
        uncheckedHover: string;
        selected: string;
        surface: string;
        ring: string;
      };
    };

    border: {
      surface: string;

      accent: {
        primary: string;
        secondary: string;
        neutral: string;
        promo: string;
        danger: string;
        warning: string;
        success: string;
        info: string;
      };

      button: {
        outline: string;
        outlineHover: string;
      };

      control: {
        default: string;
        hover: string;
        selected: string;
      };
    };

    icon: {
      primary: string;
      neutral: string;
      subtle: string;
    };

    text: {
      primary: string;
      base: string;
      display: string;
      faint: string;
      muted: string;

      accent: {
        primary: string;
        primaryMutedContrast: string;
        primaryContrast: string;
        neutral: string;
        neutralMutedContrast: string;
        neutralContrast: string;
        promo: string;
        promoMutedContrast: string;
        promoContrast: string;
        danger: string;
        dangerMutedContrast: string;
        dangerContrast: string;
        warning: string;
        warningMutedContrast: string;
        warningContrast: string;
        success: string;
        successMutedContrast: string;
        successContrast: string;
        info: string;
        infoMutedContrast: string;
        infoContrast: string;
      };

      control: {
        selected: string;
      };

      button: {
        primary: string;
        secondary: string;
        neutral: string;
        subtle: string;
        danger: string;
        outline: string;
        ghost: string;
        link: string;
        linkHover: string;
        dangerLink: string;
        dangerLinkHover: string;
        mutedLink: string;
        mutedLinkHover: string;
      };
    };
  };
}

/**
 * Interface representing a complete theme configuration, combining a name,
 * optional icon, and specific UI and token settings.
 */
export interface Theme {
  /** The name of the theme (e.g. "Dark Mode", "High Contrast"). */
  name: string;
  /** The unique identifier for the theme. */
  id: string;
  /** An optional icon to represent the theme. */
  icon?: string;
  /**
   * Specific UI configuration overrides or settings for this theme, using {@link ThemeConfig}.
   */
  uiConfig?: ThemeConfig;
  tokens?: string;
}
