export const AdvancedHosting = [
  /* REGISTER NEW DOMAIN */
  {
    name: "Billing term: 1 Month - Account Domain Name: Register New Domain @webcentral @advanced-hosting @new-domain",
    radioSelection: [[0, 0]],
    accordionSelection: [0],
    total: "$10.00",
    billingCycle: "1 month",
    webHosting: "Advanced Hosting",
    domainName: "wcautotestingjghfjhf.net",
  },
  {
    name: "Billing term: 1 year - Account Domain Name: Register New Domain @webcentral @advanced-hosting @new-domain",
    radioSelection: [[0, 1]],
    accordionSelection: [0],
    total: "$100.00",
    billingCycle: "1 year",
    webHosting: "Advanced Hosting",
    domainName: "wcautotestingjghfjhf.net",
  },
  {
    name: "Billing term: 2 years - Account Domain Name: Register New Domain @webcentral @advanced-hosting @new-domain",
    radioSelection: [[0, 2]],
    accordionSelection: [0],
    total: "$160.00",
    billingCycle: "2 year",
    webHosting: "Advanced Hosting",
    domainName: "wcautotestingjghfjhf.net",
  },
  /* TRANSFER DOMAIN */
  {
    name: "Billing term: 1 Month - Account Domain Name: Transfer Domain @webcentral @advanced-hosting @transfer-domain",
    radioSelection: [[0, 0]],
    accordionSelection: [1],
    total: "$10.00",
    billingCycle: "1 month",
    webHosting: "Advanced Hosting",
    domainName: "wcautotestingjghfjhf.net",
  },
  {
    name: "Billing term: 1 year - Account Domain Name: Transfer Domain @webcentral @advanced-hosting @transfer-domain",
    radioSelection: [[0, 1]],
    accordionSelection: [1],
    total: "$100.00",
    billingCycle: "1 year",
    webHosting: "Advanced Hosting",
    domainName: "wcautotestingjghfjhf.net",
  },
  {
    name: "Billing term: 2 years - Account Domain Name: Transfer Domain @webcentral @advanced-hosting @transfer-domain",
    radioSelection: [[0, 2]],
    accordionSelection: [1],
    total: "$160.00",
    billingCycle: "2 year",
    webHosting: "Advanced Hosting",
    domainName: "wcautotestingjghfjhf.net",
  },
  /* EXISTING DOMAIN */
  {
    name: "Billing term: 1 Month - Account Domain Name: Existing Domain @webcentral @advanced-hosting @existing-domain",
    radioSelection: [[0, 0]],
    accordionSelection: [1],
    total: "$10.00",
    billingCycle: "1 month",
    webHosting: "Advanced Hosting",
    domainName: "wcautotestingjghfjhf.net",
  },
  {
    name: "Billing term: 1 year - Account Domain Name: Existing Domain @webcentral @advanced-hosting @existing-domain",
    radioSelection: [[0, 1]],
    accordionSelection: [1],
    total: "$100.00",
    billingCycle: "1 year",
    webHosting: "Advanced Hosting",
    domainName: "wcautotestingjghfjhf.net",
  },
  {
    name: "Billing term: 2 years - Account Domain Name: Existing Domain @webcentral @advanced-hosting @existing-domain",
    radioSelection: [[0, 2]],
    accordionSelection: [1],
    total: "$160.00",
    billingCycle: "2 year",
    webHosting: "Advanced Hosting",
    domainName: "wcautotestingjghfjhf.net",
  },
];
