export const DevBlocks = [
  {
    name: "Billing term: One-time - Bundle: Easy to implement - Addon: Automation - User Tracking Only @webcentral @dev-blocks",
    radioSelection: [
      [0, 0],
      [1, 0],
      [2, 0],
    ],
    checkboxSelection: [[0, 0]],
    total: "$2,039.99",
    billingCycle: "One-time",
    product: "Dev Blocks",
    bundle: "Easy-to-implement",
    addons: "Automation",
  },
  {
    name: "Billing term: One-time - Bundle: Easy to implement - Addon: Automation - Error Tracking Only @webcentral @dev-blocks",
    radioSelection: [
      [0, 0],
      [1, 0],
      [2, 0],
    ],
    checkboxSelection: [[0, 1]],
    total: "$2,039.99",
    billingCycle: "One-time",
    product: "Dev Blocks",
    bundle: "Easy-to-implement",
    addons: "Automation",
  },
  {
    name: "Billing term: One-time - Bundle: Easy to implement - Addon: Automation - User Tracking & Error Tracking @webcentral @dev-blocks",
    radioSelection: [
      [0, 0],
      [1, 0],
      [2, 0],
    ],
    checkboxSelection: [
      [0, 0],
      [0, 1],
    ],
    total: "$2,079.98",
    billingCycle: "One-time",
    product: "Dev Blocks",
    bundle: "Easy-to-implement",
    addons: "Automation",
  },
  {
    name: "Billing term: One-time - Bundle: Easy to implement - Addon: Automation - No tracking options selected @webcentral @dev-blocks",
    radioSelection: [
      [0, 0],
      [1, 0],
      [2, 0],
    ],
    checkboxSelection: [],
    total: "$2,000.00",
    billingCycle: "One-time",
    product: "Dev Blocks",
    bundle: "Easy-to-implement",
    addons: "Automation",
  },
];
