export const StarterHosting = [
  /* Register New Domain */
  {
    name: "Billing term: 1 Month - Account Domain Name: Register New Domain @webcentral @starter-hosting @new-domain",
    radioSelection: [[0, 0]],
    accordionSelection: [0],
    total: "$5.00",
    billingCycle: "1 month",
    webHosting: "Starter Hosting",
    domainName: "wcautotestingjghfjhf.net",
  },
  {
    name: "Billing term: 1 year - Account Domain Name: Register New Domain @webcentral @starter-hosting @new-domain",
    radioSelection: [[0, 1]],
    accordionSelection: [0],
    total: "$50.00",
    billingCycle: "1 year",
    webHosting: "Starter Hosting",
    domainName: "wcautotestingasdfg.net",
  },
  {
    name: "Billing term: 2 year - Account Domain Name: Register New Domain @webcentral @starter-hosting @new-domain",
    radioSelection: [[0, 2]],
    accordionSelection: [0],
    total: "$80.00",
    billingCycle: "2 year",
    webHosting: "Starter Hosting",
    domainName: "wcautotestingzxa.net",
  },

  /* Transfer Domain */
  {
    name: "Billing term: 1 Month - Account Domain Name: Transfer Domain @webcentral @starter-hosting @transfer-domain",
    radioSelection: [[0, 0]],
    accordionSelection: [1],
    total: "$5.00",
    billingCycle: "1 month",
    webHosting: "Starter Hosting",
    domainName: "wcautotestingjghfjhf.net",
  },
  {
    name: "Billing term: 1 year - Account Domain Name: Transfer Domain @webcentral @starter-hosting @transfer-domain",
    radioSelection: [[0, 1]],
    accordionSelection: [1],
    total: "$50.00",
    billingCycle: "1 year",
    webHosting: "Starter Hosting",
    domainName: "wcautotestingasdfg.net",
  },
  {
    name: "Billing term: 2 year - Account Domain Name: Transfer Domain @webcentral @starter-hosting @transfer-domain",
    radioSelection: [[0, 2]],
    accordionSelection: [1],
    total: "$80.00",
    billingCycle: "2 year",
    webHosting: "Starter Hosting",
    domainName: "wcautotestingzxa.net",
  },

  /* Use Existing Domain */
  {
    name: "Billing term: 1 Month - Account Domain Name: Register New Domain @webcentral @starter-hosting @existing-domain",
    radioSelection: [[0, 0]],
    accordionSelection: [2],
    total: "$5.00",
    billingCycle: "1 month",
    webHosting: "Starter Hosting",
    domainName: "wcautotestingjghfjhf.net",
  },
  {
    name: "Billing term: 1 year - Account Domain Name: Register New Domain @webcentral @starter-hosting @existing-domain",
    radioSelection: [[0, 1]],
    accordionSelection: [2],
    total: "$50.00",
    billingCycle: "1 year",
    webHosting: "Starter Hosting",
    domainName: "wcautotestingasdfg.net",
  },
  {
    name: "Billing term: 2 year - Account Domain Name: Register New Domain @webcentral @starter-hosting @existing-domain",
    radioSelection: [[0, 2]],
    accordionSelection: [2],
    total: "$80.00",
    billingCycle: "2 year",
    webHosting: "Starter Hosting",
    domainName: "wcautotestingzxa.net",
  },
];
