import type { Meta, StoryObj } from "@storybook/vue3-vite";
import {
  RAMP_STEPS,
  bestContrast,
  contextualTokens,
  contrastRatio,
  defineTheme,
  generateRamp,
  ramps,
  themeToCss,
  themes
} from "@upmind/tokens";
import { Button } from "@upmind/ui/components/button/index.ts";
import { scopedTokenStyle, SpecimenInput } from "./foundation-helpers.ts";

/**
 * The Upmind UI brand engine. A brand hands `defineTheme()` a handful of
 * decisions — often just one hex — and receives a complete, WCAG-checked,
 * two-mode token set: ramps, all eight intents, dark mode, gradients,
 * typography slots, radius and density. Three token layers make that possible:
 * primitives feed semantic intents, semantic intents feed the contextual
 * slots components actually consume. Because the whole system is CSS custom
 * properties, switching brands is an attribute, not a rebuild.
 */
const meta: Meta = {
  title: "Theming/Brand Engine",
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
    controls: { disable: true }
  }
};

export default meta;
type Story = StoryObj;

export const ThreeTokenLayers: Story = {
  render: () => ({
    setup() {
      return {
        purple500: ramps.purple[500],
        slotValue:
          contextualTokens["bg-button-primary-0"]?.value ?? "var(--primary)",
        slotDescription:
          contextualTokens["bg-button-primary-0"]?.description ??
          "primary button gradient start"
      };
    },
    template: `
      <div class="max-w-5xl space-y-6">
        <header class="max-w-2xl space-y-2">
          <h2 class="type-display text-2xl text-display">Three token layers</h2>
          <p class="text-sm text-muted">
            Each layer only ever references the one below it, so a change at any
            level cascades cleanly: re-anchor a primitive ramp and every intent
            shifts; re-point a contextual slot and one component family re-skins
            without touching the intents.
          </p>
        </header>
        <div class="grid gap-4 lg:grid-cols-3">
          <article class="rounded-card border border-stroke bg-surface p-5">
            <div class="text-2xs font-medium tracking-wide text-muted uppercase">Layer 0</div>
            <h3 class="type-display mt-1 text-lg text-display">Primitives</h3>
            <div class="mt-3 flex items-center gap-2.5">
              <span class="size-8 rounded-control border border-stroke" :style="{ background: purple500 }"></span>
              <span class="font-mono text-2xs text-muted">purple-500<br />{{ purple500 }}</span>
            </div>
            <p class="mt-3 text-xs text-muted">
              Raw material: eleven-step OKLCH ramps, the hand-tuned type scale, radius
              slots, font stacks. Theme-independent — nothing in an application
              consumes these directly.
            </p>
          </article>
          <article class="rounded-card border border-stroke bg-surface p-5">
            <div class="text-2xs font-medium tracking-wide text-muted uppercase">Layer 1</div>
            <h3 class="type-display mt-1 text-lg text-display">Semantic intents</h3>
            <div class="mt-3 flex items-center gap-2.5">
              <span class="size-8 rounded-control border border-stroke bg-promo"></span>
              <span class="font-mono text-2xs text-muted">--promo<br />resolved per brand &amp; mode</span>
            </div>
            <p class="mt-3 text-xs text-muted">
              Meaning, not color: 8 intents × 7 facets, surfaces, text roles, strokes
              and the decoupled control accent — generated by defineTheme() with
              WCAG-checked contrast pairs for light and dark.
            </p>
          </article>
          <article class="rounded-card border border-stroke bg-surface p-5">
            <div class="text-2xs font-medium tracking-wide text-muted uppercase">Layer 2</div>
            <h3 class="type-display mt-1 text-lg text-display">Contextual slots</h3>
            <div class="mt-3 flex items-center gap-2.5">
              <span class="size-8 rounded-control border border-stroke bg-(--bg-button-primary-0)"></span>
              <span class="font-mono text-2xs text-muted">--bg-button-primary-0<br />{{ slotValue }}</span>
            </div>
            <p class="mt-3 text-xs text-muted">
              What components actually consume — "{{ slotDescription }}". Thin, stable
              indirections (button fills, control borders, radius slots) that a theme
              or product can re-point without redefining the intents.
            </p>
          </article>
        </div>
      </div>
    `
  })
};

export const OneTreeEveryBrand: Story = {
  render: () => ({
    components: { Button, SpecimenInput },
    setup() {
      const panels = themes.map(t => {
        const specifies = [
          typeof t.input.colors?.primary === "string"
            ? `primary ${t.input.colors.primary}`
            : null,
          t.input.colors?.gray ? `gray ${t.input.colors.gray}` : null,
          t.input.gradient ? "gradient: true" : null,
          t.input.fonts?.display ? `display: ${t.input.fonts.display}` : null,
          t.input.typeBase ? `typeBase ${t.input.typeBase}` : null,
          t.input.radiusFactor !== undefined
            ? `radiusFactor ${t.input.radiusFactor}`
            : null
        ]
          .filter(Boolean)
          .join(" · ");
        return {
          name: t.name,
          label: t.label,
          tagline: t.input.brand?.tagline ?? "",
          specifies: specifies || "defaults only"
        };
      });
      return { panels, scopeStyle: scopedTokenStyle() };
    },
    template: `
      <div class="max-w-6xl space-y-4">
        <header class="max-w-2xl space-y-2">
          <h2 class="type-display text-2xl text-display">One component tree, every brand</h2>
          <p class="text-sm text-muted">
            The exact same markup rendered once per shipped brand, each inside its own
            <span class="font-mono text-xs">data-theme</span> scope. No props change,
            no rebuild — only CSS custom properties. Colors, the display face,
            corner radii and even button gradients (Nimbus) all re-skin.
            The dark toggle in the toolbar restyles all four panels too.
          </p>
        </header>
        <div class="grid gap-4 md:grid-cols-2">
          <section
            v-for="p in panels"
            :key="p.name"
            :data-theme="p.name"
            :style="scopeStyle"
            class="rounded-card border border-stroke bg-canvas p-4 shadow-card"
          >
            <div class="flex items-baseline justify-between gap-2 px-1 pb-3">
              <span class="min-w-0">
                <span class="type-display-bold block text-sm text-display">{{ p.label }}</span>
                <span class="block truncate text-2xs text-muted">{{ p.tagline }}</span>
              </span>
              <span class="shrink-0 font-mono text-2xs text-muted">data-theme="{{ p.name }}"</span>
            </div>
            <div class="rounded-card border border-stroke bg-surface p-4 shadow-card">
              <h3 class="type-display text-xl text-display">Billing, beautifully run</h3>
              <p class="mt-1 text-sm text-muted">3 services renew this week. Auto-pay covers all of them.</p>
              <div class="mt-4 flex flex-wrap gap-2">
                <Button size="sm">Pay invoice</Button>
                <Button size="sm" variant="secondary">View services</Button>
              </div>
              <div class="mt-4 flex flex-wrap gap-1.5">
                <span class="rounded-badge bg-success-muted px-2 py-0.5 text-2xs font-medium text-success-muted-contrast">Paid</span>
                <span class="rounded-badge bg-warning-muted px-2 py-0.5 text-2xs font-medium text-warning-muted-contrast">Due soon</span>
                <span class="rounded-badge bg-danger-muted px-2 py-0.5 text-2xs font-medium text-danger-muted-contrast">Overdue</span>
                <span class="rounded-badge bg-info-muted px-2 py-0.5 text-2xs font-medium text-info-muted-contrast">Auto-renew</span>
              </div>
              <div class="mt-4 space-y-1.5">
                <label class="block text-xs font-medium text-display" :for="'domain-' + p.name">Domain</label>
                <SpecimenInput :id="'domain-' + p.name" class="w-full" placeholder="coastalstudio.com" />
              </div>
            </div>
            <p class="truncate px-1 pt-3 font-mono text-2xs text-muted" :title="p.specifies">specifies: {{ p.specifies }}</p>
          </section>
        </div>
      </div>
    `
  })
};

const THEME_INPUT_ROWS = [
  {
    option: "name",
    type: "string · required",
    what: 'Slug used in [data-theme="name"] selectors and theme switchers.'
  },
  {
    option: "label",
    type: "string · required",
    what: "Human-readable brand name shown in pickers and docs."
  },
  {
    option: "description",
    type: "string",
    what: "Short blurb for docs surfaces and the theme gallery."
  },
  {
    option: "colors.primary",
    type: "hex | overrides",
    what: "Anchor for the brand action color. The engine generates an 11-step ramp, derives stop/delta/muted facets and picks a WCAG-checked contrast label, nudging lightness imperceptibly (≤ ΔL 0.05) when needed."
  },
  {
    option: "colors.secondary / neutral",
    type: "hex | overrides",
    what: "Default to gray-derived quiet companions; anchor them to brand these intents explicitly."
  },
  {
    option: "colors.promo / danger / warning / success / info",
    type: "hex | overrides",
    what: "Status intents. They stay flat even in gradient themes — gradients are a brand-expression detail for primary/secondary/promo surfaces."
  },
  {
    option: "colors.gray",
    type: "hex",
    what: "Re-tints the entire neutral ramp: canvas, surfaces, strokes and text roles all shift with it (Nimbus uses slate, Coastal warm stone)."
  },
  {
    option: "colors.control",
    type: "hex | overrides",
    what: "Form-control accent (checkboxes, switches, focus ring), deliberately decoupled from primary so dark-button brands keep usable controls."
  },
  {
    option: "IntentInput overrides",
    type: "{ base?, default?, stop?, delta?, contrast?, muted?, mutedDelta?, mutedContrast? }",
    what: "Any intent accepts a plain hex anchor or an object pinning individual facets; everything unspecified is still derived."
  },
  {
    option: "gradient",
    type: "boolean | { hueShift } · off",
    what: "Renders primary/secondary/promo surfaces as subtle two-stop gradients via the *-stop facets (default hue shift 14°)."
  },
  {
    option: "fonts.sans / display / mono",
    type: "family or full stack",
    what: "Product, heading and monospace faces. A bare family name gets the correct fallback stack appended automatically."
  },
  {
    option: "fonts.displayWeight / displayBoldWeight",
    type: "number · 600 / 700",
    what: "Heading weights behind the type-display / type-display-bold utilities."
  },
  {
    option: "fonts.displayTracking",
    type: "string · '-0.01em'",
    what: "Heading letter-spacing (Vermilion resets it to 0 for its serif)."
  },
  {
    option: "typeBase",
    type: "string · '1rem'",
    what: "Base size the hand-tuned type scale multiplies. The shape of the scale is fixed; this knob only resizes it."
  },
  {
    option: "radiusFactor",
    type: "number · 1",
    what: "Multiplies every component radius slot. 0 = square, 2 = pillowy."
  },
  {
    option: "density",
    type: "number · 1",
    what: "Multiplies the global spacing unit. 0.85 = dense admin, 1.15 = airy customer portal."
  },
  {
    option: "iconStroke",
    type: "number · 1.5",
    what: "Lucide stroke width across the entire system."
  },
  {
    option: "brand.logoText / tagline",
    type: "string",
    what: "Used by docs surfaces and the MCP server when presenting the brand."
  },
  {
    option: "overrides / darkOverrides",
    type: "Record<string, string>",
    what: "Raw CSS-variable escape hatch (no leading --), applied last per mode."
  }
];

export const DefineThemeInputs: Story = {
  render: () => ({
    setup() {
      return { rows: THEME_INPUT_ROWS };
    },
    template: `
      <div class="max-w-5xl space-y-4">
        <header class="max-w-2xl space-y-2">
          <h2 class="type-display text-2xl text-display">defineTheme() inputs</h2>
          <p class="text-sm text-muted">
            Everything a brand can decide. Note how little is required — every option
            except <span class="font-mono text-xs">name</span> and
            <span class="font-mono text-xs">label</span> has a sensible derivation,
            including the entire dark mode.
          </p>
        </header>
        <div class="overflow-x-auto rounded-card border border-stroke bg-surface">
          <table class="w-full text-left text-sm">
            <thead>
              <tr class="border-b border-stroke">
                <th class="px-4 py-2.5 text-2xs font-medium tracking-wide text-muted uppercase">Option</th>
                <th class="px-4 py-2.5 text-2xs font-medium tracking-wide text-muted uppercase">Type · default</th>
                <th class="px-4 py-2.5 text-2xs font-medium tracking-wide text-muted uppercase">What it does</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="row in rows" :key="row.option" class="border-b border-stroke last:border-b-0">
                <td class="px-4 py-2.5 align-top font-mono text-xs whitespace-nowrap text-display">{{ row.option }}</td>
                <td class="px-4 py-2.5 align-top font-mono text-2xs text-muted">{{ row.type }}</td>
                <td class="px-4 py-2.5 align-top text-xs text-body">{{ row.what }}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    `
  })
};

const SAMPLE_BRANDS = [
  { hex: "#6D28D9", name: "violetpeak", label: "Violet Peak Hosting" },
  { hex: "#0E7490", name: "harbourcloud", label: "Harbourcloud" },
  { hex: "#EA580C", name: "emberdomains", label: "Ember Domains" }
];

const DARK_INK = ramps.gray[950];

function pick(record: Record<string, string>, key: string): string {
  return record[key] ?? "transparent";
}

export const OneHexIn: Story = {
  parameters: {
    a11y: {
      // Palette specimen: the generated ramps render every raw step with its
      // hex label, and mid-ramp steps are sub-AA against any ink by
      // definition (the WCAG-checked pairings are shown in the chips below
      // each ramp). Every other axe rule still runs at error severity.
      config: { rules: [{ id: "color-contrast", enabled: false }] }
    }
  },
  render: () => ({
    setup() {
      const brands = SAMPLE_BRANDS.map(s => {
        const ramp = generateRamp(s.hex);
        const theme = defineTheme({
          name: s.name,
          label: s.label,
          colors: { primary: s.hex }
        });
        const light = theme.light;
        const dark = theme.dark;
        return {
          ...s,
          swatches: RAMP_STEPS.map(step => ({
            step,
            hex: ramp[step],
            ink: bestContrast(ramp[step], ["#FFFFFF", DARK_INK])
          })),
          light: {
            bg: pick(light, "primary"),
            fg: pick(light, "primary-contrast"),
            ratio: contrastRatio(
              pick(light, "primary"),
              pick(light, "primary-contrast")
            ).toFixed(1),
            mutedBg: pick(light, "primary-muted"),
            mutedFg: pick(light, "primary-muted-contrast"),
            mutedRatio: contrastRatio(
              pick(light, "primary-muted"),
              pick(light, "primary-muted-contrast")
            ).toFixed(1),
            canvas: pick(light, "canvas")
          },
          dark: {
            bg: pick(dark, "primary"),
            fg: pick(dark, "primary-contrast"),
            ratio: contrastRatio(
              pick(dark, "primary"),
              pick(dark, "primary-contrast")
            ).toFixed(1),
            mutedBg: pick(dark, "primary-muted"),
            mutedFg: pick(dark, "primary-muted-contrast"),
            mutedRatio: contrastRatio(
              pick(dark, "primary-muted"),
              pick(dark, "primary-muted-contrast")
            ).toFixed(1),
            canvas: pick(dark, "canvas")
          }
        };
      });
      return { brands };
    },
    template: `
      <div class="max-w-5xl space-y-8">
        <header class="max-w-2xl space-y-2">
          <h2 class="type-display text-2xl text-display">One hex in, a brand out</h2>
          <p class="text-sm text-muted">
            Three resellers, three signup forms, one field each. Everything below —
            the ramp, the surfaces, the hover deltas, the WCAG-checked labels, the
            dark mode — is computed at runtime by
            <span class="font-mono text-xs">generateRamp()</span> and
            <span class="font-mono text-xs">defineTheme()</span> from the single hex
            shown.
          </p>
        </header>
        <section v-for="b in brands" :key="b.name" class="space-y-3">
          <div class="flex flex-wrap items-center gap-2.5">
            <span class="size-5 rounded-control border border-stroke" :style="{ background: b.hex }"></span>
            <h3 class="text-sm font-medium text-display">{{ b.label }}</h3>
            <span class="font-mono text-2xs text-muted">defineTheme({ colors: { primary: '{{ b.hex }}' } })</span>
          </div>
          <div class="grid grid-cols-11 overflow-hidden rounded-card border border-stroke">
            <div
              v-for="s in b.swatches"
              :key="s.step"
              class="flex h-14 flex-col justify-between px-1.5 py-1"
              :style="{ backgroundColor: s.hex, color: s.ink }"
            >
              <span class="text-2xs font-semibold">{{ s.step }}</span>
              <span class="font-mono text-2xs tracking-tight opacity-80">{{ s.hex }}</span>
            </div>
          </div>
          <div class="grid gap-3 sm:grid-cols-2">
            <div class="flex flex-wrap items-center gap-2 rounded-card border border-stroke p-3" :style="{ background: b.light.canvas }">
              <span class="w-12 font-mono text-2xs" :style="{ color: b.light.mutedFg }">light</span>
              <span class="inline-flex h-8 items-center rounded-button px-3.5 text-xs font-medium" :style="{ background: b.light.bg, color: b.light.fg }">Pay now · {{ b.light.ratio }}:1</span>
              <span class="inline-flex items-center rounded-badge px-2.5 py-1 text-2xs font-medium" :style="{ background: b.light.mutedBg, color: b.light.mutedFg }">Auto-renew · {{ b.light.mutedRatio }}:1</span>
            </div>
            <div class="flex flex-wrap items-center gap-2 rounded-card border border-stroke p-3" :style="{ background: b.dark.canvas }">
              <span class="w-12 font-mono text-2xs" :style="{ color: b.dark.mutedFg }">dark</span>
              <span class="inline-flex h-8 items-center rounded-button px-3.5 text-xs font-medium" :style="{ background: b.dark.bg, color: b.dark.fg }">Pay now · {{ b.dark.ratio }}:1</span>
              <span class="inline-flex items-center rounded-badge px-2.5 py-1 text-2xs font-medium" :style="{ background: b.dark.mutedBg, color: b.dark.mutedFg }">Auto-renew · {{ b.dark.mutedRatio }}:1</span>
            </div>
          </div>
        </section>
      </div>
    `
  })
};

const CSS_SNIPPET = [
  "/* app.css — one stylesheet, every brand */",
  "@import '@upmind/ui/styles';",
  "",
  "/* optional: ship pre-built brands alongside the default */",
  "@import '@upmind/tokens/themes/coastal.css';"
].join("\n");

const HTML_SNIPPET = [
  "<!-- The brand is an attribute; the mode is a class. -->",
  '<html data-theme="coastal">…</html>',
  '<html data-theme="coastal" class="dark">…</html>',
  "",
  "<!-- Scopes nest: preview one brand inside another. -->",
  '<div data-theme="vermilion" class="bg-canvas">…</div>'
].join("\n");

const JS_SNIPPET = [
  "// Runtime switching — no rebuild, no flash of unstyled brand.",
  "document.documentElement.dataset.theme = 'nimbus'",
  "document.documentElement.classList.toggle('dark', prefersDark)"
].join("\n");

const ENGINE_SNIPPET = [
  "import { defineTheme, themeToCss } from '@upmind/tokens'",
  "",
  "// A reseller signs up with one hex — ship them a full theme.",
  "const acme = defineTheme({",
  "  name: 'acme',",
  "  label: 'Acme Hosting',",
  "  colors: { primary: '#0E7490' },",
  "})",
  "",
  "const style = document.createElement('style')",
  "style.textContent = themeToCss(acme) // light + dark blocks",
  "document.head.append(style)",
  "document.documentElement.dataset.theme = 'acme'"
].join("\n");

const GENERATED_CSS = themeToCss(
  defineTheme({
    name: "acme",
    label: "Acme Hosting",
    colors: { primary: "#0E7490" }
  })
);
const GENERATED_LINES = GENERATED_CSS.split("\n");
const GENERATED_EXCERPT =
  GENERATED_LINES.slice(0, 14).join("\n") +
  "\n  /* … " +
  (GENERATED_LINES.length - 14) +
  " more lines, including the full dark block … */";

export const RuntimeSwitching: Story = {
  render: () => ({
    setup() {
      return {
        cssSnippet: CSS_SNIPPET,
        htmlSnippet: HTML_SNIPPET,
        jsSnippet: JS_SNIPPET,
        engineSnippet: ENGINE_SNIPPET,
        excerpt: GENERATED_EXCERPT
      };
    },
    template: `
      <div class="max-w-3xl space-y-6">
        <header class="max-w-2xl space-y-2">
          <h2 class="type-display text-2xl text-display">Runtime switching</h2>
          <p class="text-sm text-muted">
            Theming is runtime-only. Set <span class="font-mono text-xs">data-theme</span>
            for the brand and the <span class="font-mono text-xs">.dark</span> class for
            the mode — on <span class="font-mono text-xs">&lt;html&gt;</span> or any
            subtree — and every component re-skins through the token cascade. The
            toolbar above does exactly this.
          </p>
        </header>
        <div class="space-y-1.5">
          <div class="font-mono text-2xs text-muted">1 · import the system</div>
          <pre class="overflow-x-auto rounded-message border border-stroke bg-surface p-4 font-mono text-xs leading-relaxed text-body">{{ cssSnippet }}</pre>
        </div>
        <div class="space-y-1.5">
          <div class="font-mono text-2xs text-muted">2 · pick brand + mode declaratively</div>
          <pre class="overflow-x-auto rounded-message border border-stroke bg-surface p-4 font-mono text-xs leading-relaxed text-body">{{ htmlSnippet }}</pre>
        </div>
        <div class="space-y-1.5">
          <div class="font-mono text-2xs text-muted">3 · or switch at runtime</div>
          <pre class="overflow-x-auto rounded-message border border-stroke bg-surface p-4 font-mono text-xs leading-relaxed text-body">{{ jsSnippet }}</pre>
        </div>
        <div class="space-y-1.5">
          <div class="font-mono text-2xs text-muted">4 · generate brands on the fly (the engine is browser-safe)</div>
          <pre class="overflow-x-auto rounded-message border border-stroke bg-surface p-4 font-mono text-xs leading-relaxed text-body">{{ engineSnippet }}</pre>
        </div>
        <div class="space-y-1.5">
          <div class="font-mono text-2xs text-muted">what themeToCss(acme) actually emits — generated live by this story</div>
          <pre class="overflow-x-auto rounded-message border border-stroke bg-surface p-4 font-mono text-xs leading-relaxed text-body">{{ excerpt }}</pre>
        </div>
      </div>
    `
  })
};
