// --- utils
import { get, set, map, reduce } from "lodash-es";

// --- types
import type { IAddress, PlaceContext } from "./types.d";
import type { JsonSchema, UISchemaElement } from "@jsonforms/core";

// --------------------------------------------------------

export const usePlaceSchema = ({ countries, regions, types }: PlaceContext) => {
  const schema = {
    type: "object",
    title: "Address Fields",
    required: ["address_1", "city", "country_id", "postcode"],
    properties: {
      id: {
        type: ["integer", "null"],
        title: "ID",
        description: "The AutoGenerated ID of this Place/Address.",
        readOnly: true
      },
      // ---
      address_1: {
        type: ["string", "null"],
        title: "Address Line 1"
      },
      address_2: {
        type: ["string", "null"],
        title: "Address Line 2"
      },

      city: {
        type: ["string", "null"],
        title: "City"
      },

      postcode: {
        type: ["string", "null"],
        title: "Postcode"
      },

      region_id: {
        type: ["string", "null"],
        title: "Region",
        oneOf: !regions?.length
          ? undefined
          : map(regions, item => {
              debugger;
              return {
                const: item.value,
                title: item.label
              };
            })
      },

      // not sure this is ever used, but it is in the type definition
      state: {
        type: ["string", "null"],
        title: "State"
      },

      country_id: {
        type: ["string", "null"],
        title: "Country",
        oneOf: !countries?.length
          ? undefined
          : map(countries, item => {
              debugger;
              return {
                const: item.value,
                title: item.label
              };
            })
      },

      // ---

      default: {
        type: ["boolean", "null"],
        title: "Make this the default address?"
      },

      name: {
        type: ["string", "null"],
        title: "Reference Name"
      },

      type: {
        type: ["number", "null"],
        title: "Reference Type",
        oneOf: !types?.length
          ? undefined
          : map(types, item => {
              debugger;
              return {
                const: item.value,
                title: item.label
              };
            })
      }
    }
  };

  return schema as JsonSchema;
};

export const usePlaceUischema = () => {
  const schema = {
    type: "VerticalLayout",
    elements: [
      {
        type: "HorizontalLayout",
        elements: [
          {
            type: "Control",
            scope: "#/properties/name",
            options: {
              focus: true,
              autocomplete: "off",
              placeholder: "My home address, etc..."
            }
          }
        ],
        rule: {
          effect: "SHOW",
          condition: {
            scope: "#/properties/id",
            schema: { type: "integer", not: { const: 0 } }
          }
        }
      },

      // ---
      {
        type: "Control",
        scope: "#/properties/address_1",
        options: {
          focus: true,
          autocomplete: "address-line1",
          placeholder: "Address first line...",
          title: "Address" // ensure we  show the title for BOTH address fields
        }
      },
      {
        type: "Control",
        scope: "#/properties/address_2",
        options: {
          autocomplete: "address-line2",
          placeholder: "Address second line...",
          title: "" // ensure we DON'T show the title
        }
      },

      // ---
      {
        type: "HorizontalLayout",
        elements: [
          {
            type: "Control",
            scope: "#/properties/city",
            options: {
              autocomplete: "address-level2",
              placeholder: "City..."
            }
          },
          {
            type: "Control",
            scope: "#/properties/postcode",
            options: {
              autocomplete: "postal-code",
              placeholder: "Postcode..."
            }
          }
        ]
      },
      // ---
      {
        type: "Control",
        scope: "#/properties/region_id",
        options: {
          autocomplete: "address-level1",
          placeholder: "Please select a Region..."
        }
      },
      {
        type: "Control",
        scope: "#/properties/country_id",
        options: {
          autocomplete: "country",
          placeholder: "Please select a Country..."
        }
      }
      // ---
      // We dont ever show this field as it is set by an action
      // {
      //   type: "Control",
      //   scope: "#/properties/default",
      //   options: {
      //     // toggle: true
      //   }
      // }
    ]
  };

  return schema as UISchemaElement;
};

export const usePlaceModelParser = (schema: JsonSchema, values: IAddress) => {
  debugger;

  const model = reduce(
    schema.properties,
    (result, field, key) => {
      const value = get(values, key, field?.const || field?.default || null);
      set(result, key, value);
      return result;
    },
    {}
  );
  debugger;
  return model as IAddress;
};
