//  --- external
import { spawn } from "xstate";

// --- internal
import itemMachine from "../item.machine";
import { ItemActions as actions } from "./actions";
import services from "./services";
// --- utils
import {
  get,
  set,
  map,
  reduce,
  defaultsDeep,
  uniqueId,
  compact,
} from "lodash-es";

// --- types
import type { IAddress, AddressContext } from "./types.d";
import type { JsonSchema, UISchemaElement } from "@jsonforms/core";

// --------------------------------------------------------

export const useSchema = ({
  country,
  countries,
  regions,
  types,
  baseModel,
  // ---
  places,
  emails,
}: AddressContext) => {
  const schema = {
    type: "object",
    title: "Address Fields",
    required: ["address_1", "city", "country_id", "postcode", "type"],
    // --- conditionally required fields
    if: {
      properties: {
        companyDetails: { const: true },
      },
      required: ["companyDetails"],
    },
    then: { required: ["name", "email", "reg_number"] },
    // ---
    properties: {
      id: {
        type: ["string", "null"],
        title: "ID",
        description: "The AutoGenerated ID of this Address.",
        readOnly: true,
      },

      place: {
        type: ["string", "null"],
        title: "Address",
        lookup: places.search,
        default: baseModel?.companyDetails && baseModel?.place,
      },

      manualPlace: {
        type: ["boolean", "null"],
        title: "Can't see your address?",
        default: baseModel?.manualPlace,
        readOnly: true,
      },

      // ---
      address_1: {
        type: "string",
        title: "Address Line 1",
      },

      address_2: {
        type: ["string", "null"],
        title: "Address Line 2",
      },

      city: {
        type: "string",
        title: "City",
      },

      postcode: {
        type: "string",
        title: "Postcode",
      },

      region_id: {
        type: ["string", "null"],
        title: "Region",
        oneOf: !regions?.length
          ? undefined
          : map(regions, item => {
              return {
                const: item.id,
                title: item.name,
              };
            }),
      },

      // not sure this is ever used, but it is in the type definition
      state: {
        type: ["string", "null"],
        title: "State",
        default: baseModel?.state,
      },

      country_id: {
        type: "string",
        title: "Country",
        oneOf: !countries?.length
          ? undefined
          : map(countries, item => {
              return {
                const: item.id,
                title: item.name,
              };
            }),
      },

      // ---

      companyDetails: {
        type: ["boolean", "null"],
        title: "Add business details",
        default: baseModel?.companyDetails,
      },

      name: {
        type: "string",
        title: "Name",
      },

      email: {
        type: "string",
        title: "Email",
        default: baseModel.email,
        lookup: emails.search,
      },

      phone: {
        type: "object",
        title: "Phone",
        isPhoneNumber: country?.code,
        properties: {
          number: {
            type: ["string", "null"],
            title: "Phone number ( with dailing code )",
            default: baseModel?.phone?.number,
          },

          nationalNumber: {
            type: ["string", "null"],
            title: "Phone number",
            default: baseModel?.phone?.nationalNumber,
          },

          countryCallingCode: {
            type: ["string", "null"],
            title: "Country calling code",
            default: baseModel?.phone?.nationalCallingCode,
          },

          country: {
            type: ["string", "null"],
            title: "Country",
            default: baseModel?.phone?.country,
          },
        },
      },

      reg_number: {
        type: ["string", "null"],
        title: "Registration number",
      },

      vat_number: {
        type: ["string", "null"],
        title: "Registered tax/VAT id",
      },

      vat_percent: {
        type: ["integer", "null"],
        title: "VAT percent",
      },
      // ---

      default: {
        type: ["boolean", "null"],
        title: "Make this the default address?",
      },

      type: {
        type: "number",
        title: "Address Type",
        default: baseModel?.type,
        oneOf: map(types, item => {
          return {
            const: item.key,
            title: item.value,
          };
        }),
      },
    },
  };

  // if (id) {
  //   schema.required.push("name");
  //   schema.required.push("type");
  // }

  return schema as JsonSchema;
};

export const useUischema = ({ addresses, emails, phones }) => {
  const lookups = {
    addresses: addresses.getItems(),
    emails: emails.getItems(),
    phones: phones.getItems(),
  };

  const schema = {
    type: "VerticalLayout",
    elements: [
      {
        type: "HorizontalLayout",
        elements: [
          // {
          //   type: "Control",
          //   scope: "#/properties/type",
          //   options: {
          //     autocomplete: "off",
          //     placeholder: "Select an address type...",
          //   },
          // },
          {
            type: "Control",
            scope: "#/properties/name",
            options: {
              focus: true,
              autocomplete: "off",
              placeholder: "My home address, etc...",
            },
          },
        ],
        rule: {
          effect: "SHOW",
          condition: {
            scope: "#",
            schema: {
              required: ["id"],
              properties: {
                companyDetails: { const: false },
              },
            },
          },
        },
      },

      // ---
      {
        type: "Control",
        scope: "#/properties/place",
        options: {
          autocomplete: "off",
          placeholder: "Search for address ...",
          items: compact([
            lookups.addresses?.length
              ? {
                  label: "Your saved addreses",
                  as: "separator",
                }
              : null,

            ...map(lookups.addresses, item => {
              return {
                value: item.id,
                label: [
                  item.name,
                  item.address_1,
                  item.address_2,
                  item.city,
                  item.postcode,
                ].join(", "),
              };
            }),
            {
              label: "Enter manually",
              value: "manual",
              as: "button",
              variant: "link",
              size: "sm",
              persist: true,
            },
          ]),
        },
        rule: {
          effect: "HIDE",
          condition: {
            scope: "#",
            schema: {
              anyOf: [
                { required: ["id"] },
                {
                  required: ["place"],
                  properties: { place: { const: "manual" } },
                },
              ],
            },
          },
        },
      },

      // ---
      {
        type: "VerticalLayout",
        elements: [
          {
            type: "Control",
            scope: "#/properties/address_1",
            label: "Address", // ensure we  show the title for BOTH address fields
            options: {
              focus: true,
              autocomplete: "address-line1",
              placeholder: "Address first line...",
            },
          },
          {
            type: "Control",
            scope: "#/properties/address_2",
            label: "", // ensure we DON'T show the title
            options: {
              autocomplete: "address-line2",
              placeholder: "Address second line...",
              class: "-mt-8",
            },
          },

          // ---
          {
            type: "HorizontalLayout",
            elements: [
              {
                type: "Control",
                scope: "#/properties/city",
                options: {
                  autocomplete: "address-level2",
                  placeholder: "City...",
                },
              },
              {
                type: "Control",
                scope: "#/properties/postcode",
                options: {
                  autocomplete: "postal-code",
                  placeholder: "Postcode...",
                },
              },
            ],
          },
          // ---
          {
            type: "Control",
            scope: "#/properties/region_id",
            options: {
              autocomplete: "address-level1",
              placeholder: "Please select a Region...",
            },
          },
          {
            type: "Control",
            scope: "#/properties/country_id",
            options: {
              autocomplete: "country",
              placeholder: "Please select a Country...",
            },
          },
        ],
        rule: {
          effect: "SHOW",
          condition: {
            scope: "#/properties/manualPlace",
            schema: { const: true },
          },
        },
      },
      // --- company details
      {
        type: "Control",
        scope: "#/properties/companyDetails",
        rule: {
          effect: "SHOW",
          condition: {
            scope: "#",
            schema: {
              // properties: { companyDetails: { not: { const: true } } },
              anyOf: [
                { required: ["id"] },
                { required: ["name"] },
                { properties: { manualPlace: { const: true } } },
              ],
            },
          },
        },
      },

      {
        type: "VerticalLayout",
        elements: [
          {
            type: "Control",
            scope: "#/properties/name",
            options: {
              focus: true,
              autocomplete: "organization",
              placeholder: "My Company Name (PTY) LTD",
              label: "Company Name",
            },
          },
          {
            type: "Control",
            scope: "#/properties/reg_number",
            options: {},
          },
          {
            type: "HorizontalLayout",
            elements: [
              {
                type: "Control",
                scope: "#/properties/vat_number",
                options: {},
              },
              {
                type: "Control",
                scope: "#/properties/vat_percent",
                options: {
                  appendText: "%",
                },
              },
            ],
          },
          {
            type: "Control",
            scope: "#/properties/email",
            options: {
              autocomplete: "email",
              itemLabel: "email",
              itemValue: "id",
              items: lookups.emails,
            },
          },
          {
            type: "Control",
            scope: "#/properties/phone",
            options: {
              autocomplete: "tel",
            },
          },
        ],
        rule: {
          effect: "SHOW",
          condition: {
            scope: "#/properties/companyDetails",
            schema: { const: true },
          },
        },
      },

      // ---
      // We dont ever show this field as it is set by an action
      // {
      //   type: "Control",
      //   scope: "#/properties/default",
      //   options: {
      //     // toggle: true
      //   }
      // }
    ],
  };

  return schema as UISchemaElement;
};

export const useModelParser = (
  schema: JsonSchema,
  values: IAddress,
  baseModel?: IAddress
) => {
  const model = reduce(
    schema.properties,
    (result, field, key) => {
      const value =
        field?.const || get(values, key, field?.default || get(baseModel, key));
      set(result, key, value);
      return result;
    },
    {}
  );

  return defaultsDeep(model, values) as IAddress;
};

// --------------------------------------------------------

export const spawnItem = (model?: IAddress) => {
  try {
    const name = get(model, "id", uniqueId("item_"));
    return spawn(
      itemMachine
        .withConfig({
          actions,
          services,
        })
        .withContext({ model }),
      {
        name,
        sync: true,
      }
    );
  } catch (err) {
    console.error("AddressListings", "spawnItem", { model });
  }
};
