//  --- external
import { spawn } from "xstate";

// --- internal
import { useSystem } from "../..";
import addressMachine from "./address.machine";
import services, { AddressTypes } from "./services";

// --- utils
import {
  some,
  get,
  find,
  includes,
  set,
  map,
  reduce,
  defaultsDeep,
  uniqueId
} from "lodash-es";

// --- types
import type { ICountry } from "../../system/types";
import type { IAddress, AddressContext } from "./types";
import type { JsonSchema, UISchemaElement } from "@jsonforms/core";

// --------------------------------------------------------

export const useAutocompleteSchema = choices => {
  const schema = {
    type: "object",
    title: "Address Fields",
    properties: {
      search: {
        type: ["string", "null"],
        title: "Search for an address...",
        minLength: 3
      },
      address: {
        type: ["string", "null"],
        title: "Select an address...",
        oneOf: !choices?.length
          ? undefined
          : map(choices, item => {
              return {
                const: item.place_id,
                title: item.description
              };
            })
      }
    }
  };

  // if (id) {
  //   schema.required.push("name");
  //   schema.required.push("type");
  // }

  return schema as JsonSchema;
};

export const useAutocompleteUischema = choices => {
  const schema = {
    type: "VerticalLayout",
    elements: [
      {
        type: "Control",
        scope: "#/properties/search",
        label: "",
        options: {
          focus: true,
          autocomplete: "street-address",
          placeholder: "Start typing an address..."
        }
      },
      {
        type: "Control",
        scope: "#/properties/address",
        label: "",
        options: {
          type: !choices?.length ? "hidden" : undefined,
          autocomplete: "off",
          placeholder: "Select an address...",
          format: "menu",
          title: "Select an address to use..."
        },
        rule: {
          effect: "SHOW",
          condition: {
            scope: "#",
            schema: {
              required: ["search"]
            }
          }
        }
      }
    ]
  };

  return schema as UISchemaElement;
};

// --------------------------------------------------------

export const useSchema = ({
  countries,
  regions,
  types,
  baseModel
}: AddressContext) => {
  const schema = {
    type: "object",
    title: "Address Fields",
    required: ["address_1", "city", "country_id", "postcode", "type"],
    properties: {
      id: {
        type: ["string", "null"],
        title: "ID",
        description: "The AutoGenerated ID of this Address.",
        readOnly: true
      },

      // ---
      address_1: {
        type: ["string", "null"],
        title: "Address Line 1"
      },
      address_2: {
        type: ["string", "null"],
        title: "Address Line 2"
      },
      city: {
        type: ["string", "null"],
        title: "City"
      },
      postcode: {
        type: ["string", "null"],
        title: "Postcode"
      },
      region_id: {
        type: ["string", "null"],
        title: "Region",
        oneOf: !regions?.length
          ? undefined
          : map(regions, item => {
              return {
                const: item.id,
                title: item.name
              };
            })
      },

      // not sure this is ever used, but it is in the type definition
      state: {
        type: ["string", "null"],
        title: "State"
      },

      country_id: {
        type: ["string", "null"],
        title: "Country",
        default: baseModel?.country_id,
        oneOf: !countries?.length
          ? undefined
          : map(countries, item => {
              return {
                const: item.id,
                title: item.name
              };
            })
      },

      // ---

      default: {
        type: ["boolean", "null"],
        title: "Make this the default address?"
      },

      name: {
        type: ["string", "null"],
        title: "Reference Name",
        default: baseModel?.name
      },

      type: {
        type: ["number", "null"],
        title: "Address Type",
        default: baseModel?.type,
        oneOf: map(AddressTypes, item => {
          return {
            const: item.key,
            title: item.value
          };
        })
      }
    }
  };

  // if (id) {
  //   schema.required.push("name");
  //   schema.required.push("type");
  // }

  return schema as JsonSchema;
};

export const useUischema = () => {
  const schema = {
    type: "VerticalLayout",
    elements: [
      {
        type: "HorizontalLayout",
        elements: [
          {
            type: "Control",
            scope: "#/properties/type",
            options: {
              autocomplete: "off",
              placeholder: "Select an address type..."
            }
          },
          {
            type: "Control",
            scope: "#/properties/name",
            options: {
              focus: true,
              autocomplete: "off",
              placeholder: "My home address, etc..."
            }
          }
        ],
        rule: {
          effect: "SHOW",
          condition: {
            scope: "#",
            schema: {
              required: ["id"]
            }
          }
        }
      },

      // ---
      {
        type: "Control",
        scope: "#/properties/address_1",
        label: "Address", // ensure we  show the title for BOTH address fields
        options: {
          focus: true,
          autocomplete: "address-line1",
          placeholder: "Address first line..."
        }
      },
      {
        type: "Control",
        scope: "#/properties/address_2",
        label: "", // ensure we DON'T show the title
        options: {
          autocomplete: "address-line2",
          placeholder: "Address second line...",
          class: "-mt-8"
        }
      },

      // ---
      {
        type: "HorizontalLayout",
        elements: [
          {
            type: "Control",
            scope: "#/properties/city",
            options: {
              autocomplete: "address-level2",
              placeholder: "City..."
            }
          },
          {
            type: "Control",
            scope: "#/properties/postcode",
            options: {
              autocomplete: "postal-code",
              placeholder: "Postcode..."
            }
          }
        ]
      },
      // ---
      {
        type: "Control",
        scope: "#/properties/region_id",
        options: {
          autocomplete: "address-level1",
          placeholder: "Please select a Region..."
        }
      },
      {
        type: "Control",
        scope: "#/properties/country_id",
        options: {
          autocomplete: "country",
          placeholder: "Please select a Country..."
        }
      }
      // ---
      // We dont ever show this field as it is set by an action
      // {
      //   type: "Control",
      //   scope: "#/properties/default",
      //   options: {
      //     // toggle: true
      //   }
      // }
    ]
  };

  return schema as UISchemaElement;
};

export const useModelParser = (
  schema: JsonSchema,
  values: IAddress,
  baseModel: IAddress
) => {
  const model = reduce(
    schema.properties,
    (result, field, key) => {
      const value = get(
        values,
        key,
        field?.const || field?.default || get(baseModel, key)
      );
      set(result, key, value);
      return result;
    },
    {}
  );

  return defaultsDeep(model, values) as IAddress;
};

// --------------------------------------------------------

function parseCountry(addressComponents: any) {
  const { getCountry } = useSystem();

  const country = find(addressComponents, entry =>
    includes(entry.types, "country")
  );

  return getCountry(get(country, "short_name"));
}

async function parseRegion(
  regionLevel1: string,
  regionLevel2: string,
  country: ICountry
) {
  const { fetchRegions, getRegion } = useSystem();
  await fetchRegions(country);
  return getRegion([regionLevel1, regionLevel2], country);
}

function parseValue(addressComponents: any[], fields: string[]) {
  const value = find(addressComponents, entry =>
    some(entry.types, type => includes(fields, type))
  );

  return get(value, "long_name");
}

export async function usePlaceParser(result: any): Promise<IAddress> {
  const name = get(result, "name");
  const address = get(result, "address_components", []);

  const address_1 = [
    parseValue(address, ["street_number"]),
    parseValue(address, ["route"])
  ];

  const address_2 = [parseValue(address, ["sublocality"])];

  const postcode = parseValue(address, ["postal_code"]);

  const city = parseValue(address, [
    "postal_town",
    "locality",
    "administrative_area_level_2"
  ]);

  const country = parseCountry(address);

  const region = await parseRegion(
    parseValue(address, ["administrative_area_level_1"]),
    parseValue(address, ["administrative_area_level_2"]),
    country
  );

  const value = {
    name,
    address_1: address_1.join(" "),
    address_2: address_2.join(" "),
    postcode,
    city,
    country_id: get(country, "id"),
    region_id: get(region, "id")
  };

  return value;
}

// --------------------------------------------------------

export const spawnItem = (model?: IAddress) => {
  try {
    const name = get(model, "id", uniqueId("item_"));
    return spawn(addressMachine.withContext({ model }), {
      name,
      sync: true
    });
  } catch (err) {
    console.error("CompanyListings", "spawnItem", { model });
  }
};
