/** @internal */
import {
  CLIENT_PHONE_DRY_TYPES,
  DEFAULT_PHONE_TYPE
} from "./client-phone-dry.types";
import { map } from "lodash-es";
import type { JsonSchema7, UISchemaElement } from "@jsonforms/core";
import type { ICountry } from "@upmind-automation/types";

// -----------------------------------------------------------------------------
/**
 * @module client-phone-dry/schemas
 * @description Form schema/uischema parsers for the phone add/edit form.
 * Armless — SAME fields and SAME `required` list for both cells (design.md §7:
 * "no per-actor field/required divergence, so no new-ground schemas arm").
 * @precedent `client-email/client-email.schemas.ts` — the plain-function
 * shape (no per-actor factory) is this variant's real armless convention; the
 * query template's `useSchemaDefinitions()`/`$ref` machinery exists for a
 * module that needs to share definitions with an arm, which this module does
 * not earn (doctrine-vs-template: cite `client-email` for the fact, per
 * `templates/ARMS.md`'s own "cite it for facts, never copy its shape").
 */

export const useSchema = ({ country }: { country?: ICountry }): JsonSchema7 => {
  return {
    type: "object",
    title: "Phone Number",
    // D2 — `type` restored to `required` (baseline dropped it, `client-phone.schemas.ts:9`).
    required: ["phone", "type"],
    properties: {
      id: {
        type: ["string", "null"],
        title: "ID",
        description: "The AutoGenerated ID of this Phone.",
        readOnly: true
      },

      phone: {
        type: "object",
        // @ts-expect-error: 'phone_country_code' is a custom AJV keyword
        phone_country_code: country?.code,
        required: ["number", "nationalNumber", "countryCallingCode", "country"],
        properties: {
          number: {
            type: "string",
            title: "Phone number ( with dialing code )"
          },
          nationalNumber: {
            type: "string",
            title: "Phone number"
          },
          countryCallingCode: {
            type: "string",
            title: "Country calling code"
          },
          country: {
            type: "string",
            title: "Country",
            default: country?.code || null
          }
        }
      },

      // D2 — restored (baseline `client-phone.schemas.ts:47-53` shipped this deprecated/commented-out).
      type: {
        type: "number",
        title: "Type",
        oneOf: map(CLIENT_PHONE_DRY_TYPES, item => ({
          const: item.key,
          title: item.value
        })),
        default: DEFAULT_PHONE_TYPE
      }
    }
  };
};

export const useUischema = (): UISchemaElement => {
  return {
    type: "VerticalLayout",
    elements: [
      {
        type: "Control",
        scope: "#/properties/phone",
        i18n: "form.phone",
        options: {
          autoFocus: true,
          autocomplete: "phone"
        }
      },
      {
        type: "Control",
        scope: "#/properties/type",
        i18n: "form.phone_type"
      }
    ]
  } as UISchemaElement;
};
