/** @internal */

import type { JsonSchema7, UISchemaElement } from "@jsonforms/core";
import type { ICountry } from "@upmind-automation/types";
// -----------------------------------------------------------------------------
/**
 * @module client-phone/client-phone.schemas
 * @description Schema / uischema for the per-phone form. They move as a PAIR:
 * a schema field with no control renders a required-but-invisible input.
 * Content unchanged from pre-conversion (row M3) — including the required
 * `["number","nationalNumber","countryCallingCode","country"]` array and the
 * custom AJV keyword `phone_country_code`.
 *
 * WARNING: Do not import directly. The manager's machine config adopts this
 * pair (`setSchemas`) and consumers read it off
 * `useClientPhoneManager().useContext().schema` / `.uischema` — the barrel
 * exports neither (decision D-4), because a form rendered from a schema the
 * machine has not adopted validates against a different contract than the one
 * that saves. `basket-billing/unified/schemas.ts` reaches this pair by its
 * deep internal path instead (row X2 / task T-6a).
 */

export const useSchema = ({ country }: { country?: ICountry }): JsonSchema7 => {
  const schema: JsonSchema7 = {
    type: "object",
    title: "Phone Number",
    required: ["phone"],
    properties: {
      id: {
        type: ["string", "null"],
        title: "ID",
        description: "The AutoGenerated ID of this Phone.",
        readOnly: true
      },

      phone: {
        type: "object",
        // @ts-expect-error: 'phone_country_code' is a custom AJV keyword
        phone_country_code: country?.code,
        required: ["number", "nationalNumber", "countryCallingCode", "country"],
        properties: {
          number: {
            type: "string",
            title: "Phone number ( with dialing code )"
          },

          nationalNumber: {
            type: "string",
            title: "Phone number"
          },

          countryCallingCode: {
            type: "string",
            title: "Country calling code"
          },

          country: {
            type: "string",
            title: "Country",
            default: country?.code || null
          }
        }
      }

      //  --- deprecated

      // type: {
      //   type: "number",
      //   const: 1,
      //   readOnly: true,
      // },

      // default: {
      //   type: ["boolean", "null"],
      //   title: "Make this the default phone?",
      // },
    }
    // errorMessage: {
    //   properties: {
    //     phone: "must be a valid phone number"
    //   }
    // }
  };

  return schema;
};

export const useUischema = () => {
  const schema = {
    type: "VerticalLayout",
    elements: [
      // {
      //   type: "Control",
      //   scope: "#/properties/id",
      //   rule: {
      //     effect: "HIDE",
      //     condition: { const: true },
      //   },
      // }, // HACK: need to force hide this otherwise the id renders in hte email field?

      {
        type: "Control",
        scope: "#/properties/phone",
        i18n: "form.phone",
        options: {
          autoFocus: true,
          autocomplete: "phone"
        }
      }
    ]
  };

  return schema as UISchemaElement;
};

// -----------------------------------------------------------------------------

/**
 * The collection's QUERY schema — its whole request state (filters · sort ·
 * pagination) as ONE Draft-07 schema over one model. A SELF-CONTAINED JSON
 * literal, so it can be lifted straight into ajv or a test and run standalone.
 *
 * Phones are read whole for the billing surfaces that pick one, so `limit: 0`
 * asks for the unpaged read and no sort is declared. The one declared filter is
 * the free-text search, bound to the `phone` wire column: staging answers
 * `filter[number|like]` with an HTTP 500 and `filter[phone|like]` with a
 * narrowed 200, both recorded in `__tests__/fixtures`.
 */
export function useQuerySchema(): JsonSchema7 {
  return {
    $schema: "http://json-schema.org/draft-07/schema#",
    type: "object",
    additionalProperties: false,
    properties: {
      filters: {
        type: "object",
        additionalProperties: false,
        properties: {
          number: {
            type: "object",
            title: "text.phone",
            // @ts-expect-error: 'column' is the branch's wire-column binding
            column: "phone",
            additionalProperties: false,
            properties: {
              // The bare term — the translator adds the % wildcards.
              like: { type: ["string", "null"], minLength: 1 }
            }
          }
        }
      },
      pagination: {
        type: "object",
        additionalProperties: false,
        properties: {
          limit: { type: "integer", minimum: 0, default: 0 },
          offset: { type: "integer", minimum: 0 }
        }
      }
    }
  } satisfies JsonSchema7;
}
