/** @internal */

import { SortDirection } from "../query/query.types";
import { DEFAULT_SORT } from "./client-phone.types";
import type { QuerySchema } from "./client-phone.types";
import type {
  ControlElement,
  JsonSchema7,
  UISchemaElement
} from "@jsonforms/core";
import type { ICountry } from "@upmind-automation/types";
// -----------------------------------------------------------------------------
/**
 * @module client-phone/client-phone.schemas
 * @description Schema / uischema for the per-phone form. They move as a PAIR:
 * a schema field with no control renders a required-but-invisible input.
 * Content unchanged from pre-conversion (row M3) — including the required
 * `["number","nationalNumber","countryCallingCode","country"]` array and the
 * custom AJV keyword `phone_country_code`.
 *
 * WARNING: Do not import directly. The manager's machine config adopts this
 * pair (`setSchemas`) and consumers read it off
 * `useClientPhoneManager().useContext().schema` / `.uischema` — the barrel
 * exports neither (decision D-4), because a form rendered from a schema the
 * machine has not adopted validates against a different contract than the one
 * that saves. `basket-billing/unified/schemas.ts` reaches this pair by its
 * deep internal path instead (row X2 / task T-6a).
 */

export const useSchema = ({ country }: { country?: ICountry }): JsonSchema7 => {
  const schema: JsonSchema7 = {
    type: "object",
    title: "Phone Number",
    required: ["phone"],
    properties: {
      id: {
        type: ["string", "null"],
        title: "ID",
        description: "The AutoGenerated ID of this Phone.",
        readOnly: true
      },

      phone: {
        type: "object",
        // @ts-expect-error: 'phone_country_code' is a custom AJV keyword
        phone_country_code: country?.code,
        required: ["number", "nationalNumber", "countryCallingCode", "country"],
        properties: {
          number: {
            type: "string",
            title: "Phone number ( with dialing code )"
          },

          nationalNumber: {
            type: "string",
            title: "Phone number"
          },

          countryCallingCode: {
            type: "string",
            title: "Country calling code"
          },

          country: {
            type: "string",
            title: "Country",
            default: country?.code || null
          }
        }
      }

      //  --- deprecated

      // type: {
      //   type: "number",
      //   const: 1,
      //   readOnly: true,
      // },

      // default: {
      //   type: ["boolean", "null"],
      //   title: "Make this the default phone?",
      // },
    }
    // errorMessage: {
    //   properties: {
    //     phone: "must be a valid phone number"
    //   }
    // }
  };

  return schema;
};

export const useUischema = () => {
  const schema = {
    type: "VerticalLayout",
    elements: [
      // {
      //   type: "Control",
      //   scope: "#/properties/id",
      //   rule: {
      //     effect: "HIDE",
      //     condition: { const: true },
      //   },
      // }, // HACK: need to force hide this otherwise the id renders in hte email field?

      {
        type: "Control",
        scope: "#/properties/phone",
        i18n: "form.phone",
        options: {
          autoFocus: true,
          autocomplete: "phone"
        }
      }
    ]
  };

  return schema as UISchemaElement;
};

// -----------------------------------------------------------------------------

/**
 * The collection's QUERY schema — its whole request state (filters · sort ·
 * pagination) as ONE Draft-07 schema over one model. A SELF-CONTAINED JSON
 * literal, so it can be lifted straight into ajv or a test and run standalone.
 *
 * Phones are read whole for the billing surfaces that pick one, so `limit: 0`
 * stays the pagination default (preserve-invariant, `client-address.schemas.ts:393`
 * sibling precedent). The one declared filter is the free-text search, bound
 * to the `phone` wire column: staging answers `filter[number|like]` with an
 * HTTP 500 and `filter[phone|like]` with a narrowed 200, both recorded in
 * `__tests__/fixtures`. The `sort` branch declares exactly `created_at` — the
 * only column either legacy consumer orders on (`clientPhonesList.vue:68-71`
 * ASC boot; `clientPhoneSelect.vue:171` `-created_at`); an unknown `order=`
 * column is an HTTP 500, so declaring beyond the oracle is an unsafe guess.
 */
export function useQuerySchema(): QuerySchema {
  return {
    $schema: "http://json-schema.org/draft-07/schema#",
    type: "object",
    additionalProperties: false,
    properties: {
      filters: {
        type: "object",
        additionalProperties: false,
        properties: {
          number: {
            type: "object",
            title: "text.phone",
            // @ts-expect-error: 'column' is the branch's wire-column binding
            column: "phone",
            additionalProperties: false,
            properties: {
              // The bare term — the translator adds the % wildcards.
              like: { type: ["string", "null"], minLength: 1 }
            }
          },
          default: {
            type: "object",
            title: "Default",
            additionalProperties: false,
            properties: {
              eq: {
                type: ["boolean", "null"],
                enum: [true, false, null]
              }
            }
          }
        }
      },
      sort: {
        type: "array",
        default: DEFAULT_SORT,
        minItems: 1,
        // `uniqueItems` alone de-dupes ENTRIES, not FIELDS: two `created_at`
        // rows with opposite `dir` are two distinct entries, so ajv passed
        // both through to the wire (`order=created_at,-created_at`) even
        // though the declared `field` enum names exactly one legal column.
        maxItems: 1,
        uniqueItems: true,
        items: {
          type: "object",
          additionalProperties: false,
          required: ["field", "dir"],
          properties: {
            field: { enum: ["created_at"] },
            dir: { enum: [SortDirection.ASC, SortDirection.DESC] }
          }
        }
      },
      pagination: {
        type: "object",
        additionalProperties: false,
        properties: {
          limit: { type: "integer", minimum: 0, default: 0 },
          offset: { type: "integer", minimum: 0, default: 0 }
        }
      }
    }
  } satisfies JsonSchema7;
}

/**
 * The module's DEFAULT filter-bar presentation over the one query schema —
 * ONE plain `Control` scoping the free-text search leaf, so the leaf's own
 * write IS the wire shape. Mirrors `client-email.schemas.ts:244-268`.
 */
export function useQueryUischema(): UISchemaElement {
  return {
    type: "FilterBar",
    elements: [
      {
        type: "Control",
        scope: "#/properties/filters/properties/number/properties/like",
        i18n: "form.phone_search",
        options: { format: "search", noLabel: true, optionalText: "" }
      },
      {
        type: "Control",
        scope: "#/properties/filters/properties/default/properties/eq",
        i18n: "form.default_filter",
        options: { format: "button-group", noLabel: true, optionalText: "" }
      }
    ]
  } as UISchemaElement;
}

/**
 * The collection's ORDERING presentation — one element over the query
 * schema's `sort` branch. Mirrors `client-email.schemas.ts:279-285`.
 */
export function useSortUischema(): ControlElement {
  return {
    type: "Control",
    scope: "#/properties/sort",
    i18n: "form.phone_sort"
  };
}
