import { test, expect } from "@playwright/test";
import { URLs } from "../support/constants/urls";
import { Languages as languages } from "../support/constants/languages";
import { setLocale } from "../support/helpers/locale";
import { seedGuestBasket } from "../support/flows/guest-checkout";
import { captureBrandSettings } from "../support/mocks/brand";
import { GuestCheckout } from "../support/page-objects/templates/guest-checkout";

let guest: GuestCheckout;

// -----------------------------------------------------------------------------
/**
 * @fileoverview Guest account menu / upgrade form visual regression (FE-2857).
 *
 * ## Job To Be Done
 * Freeze the two guest-client storefront surfaces that only exist once a
 * visitor has entered guest checkout (establishing an `upm_client_session`):
 * (1) the storefront header account menu OPEN, showing the guest label and the
 * full-account upgrade item; (2) the guest upgrade form served to a guest
 * client on the register page. Both are captured across every supported locale
 * (incl. the RTL locale) so translated/RTL layout regressions are caught.
 *
 * ## Gate dependency
 * `register/guest` is server-enforced, so the guest session cannot be mocked.
 * Each iteration reads the REAL guest-checkout brand flag via
 * `captureBrandSettings` and `test.skip`s when it's off — the shots only render
 * on a guest-checkout-enabled brand.
 *
 * ## What Breaks If These Fail
 * - The guest account menu layout regresses (mislabelled guest, missing upgrade
 *   item, broken RTL mirroring), stranding guests with no visible route to a
 *   full account.
 * - The guest upgrade form's layout regresses across locales, so guests in
 *   non-English / RTL locales get a broken conversion form.
 */

// Brand-config key behind the guest-checkout gate
// (`BrandConfigKeys.GUEST_CHECKOUT_ENABLED`).
const GUEST_CHECKOUT_KEY = "invoices.guest_checkout.enabled";

// Each test seeds a guest basket then enters guest checkout on a shared,
// staging guest-checkout-enabled brand; the sibling describes generated by the
// locale loop would otherwise contend on that shared session, so run serially.
test.describe.configure({ mode: "serial" });

for (const { language, locale } of languages) {
  test.describe(`Guest Account Visual Regression Tests - ${language}`, () => {
    test.beforeEach(async ({ page }) => {
      guest = new GuestCheckout(page);
      await page.addStyleTag({
        content: `
              *,
              *::before,
              *::after {
                  transition: none !important;
                  animation: none !important;
                  caret-color: transparent !important;
              }
              `
      });
    });

    test("Guest Account Menu", async ({ page, context }) => {
      await seedGuestBasket(page);

      const settings = captureBrandSettings(page);
      await page.goto(URLs.register);
      const config = await settings;
      test.skip(
        !config[GUEST_CHECKOUT_KEY],
        `Guest checkout disabled on this brand (${URLs.baseUrl}) — run against a guest-checkout-enabled brand`
      );

      await expect(guest.cta).toBeVisible();
      await guest.enterGuestCheckout();
      await expect
        .poll(
          async () =>
            (await context.cookies()).some(
              c => c.name === "upm_client_session"
            ),
          { timeout: 20000 }
        )
        .toBeTruthy();

      await page.goto(`${URLs.baseUrl}order/shop/`);
      await setLocale(page, locale);
      await expect(guest.avatar).toBeVisible({ timeout: 15000 });
      await expect(page.getByTestId("product-card").first()).toBeVisible({
        timeout: 15000
      });
      await guest.openAccountMenu();
      await expect(guest.accountLabel).toBeVisible();
      await expect(guest.upgradeMenuItem).toBeVisible();

      await expect(page).toHaveScreenshot(`${language}/guest-account-menu`, {
        mask: [page.locator("lord-icon")]
      });
    });

    test("Guest Upgrade Form", async ({ page, context }) => {
      await seedGuestBasket(page);

      const settings = captureBrandSettings(page);
      await page.goto(URLs.register);
      const config = await settings;
      test.skip(
        !config[GUEST_CHECKOUT_KEY],
        `Guest checkout disabled on this brand (${URLs.baseUrl}) — run against a guest-checkout-enabled brand`
      );

      await expect(guest.cta).toBeVisible();
      await guest.enterGuestCheckout();
      await expect
        .poll(
          async () =>
            (await context.cookies()).some(
              c => c.name === "upm_client_session"
            ),
          { timeout: 20000 }
        )
        .toBeTruthy();

      await page.goto(URLs.register);
      await setLocale(page, locale);
      await expect(guest.upgradeForm).toBeVisible({ timeout: 15000 });

      await expect(page).toHaveScreenshot(`${language}/guest-upgrade-form`, {
        mask: [page.locator("lord-icon")]
      });
    });
  });
}
