/**
 * @fileoverview useProductSetup integration — getNextRelated/getNextInvalid
 * routing, apply()/updateMany merge semantics, and reset() lifecycle (FE-2796)
 *
 * ## Job To Be Done
 * FE-2457's product-setup flow is well covered at e2e; the remaining gaps are
 * load-bearing wiring that belongs at integration (ADR 021). Three behaviours:
 *
 *   1. `getNextRelated` / `getNextInvalid` routing — `getNextInvalid` returns
 *      the next product requiring setup, excluding the actor's own; `getNextRelated`
 *      walks the actor's `provisionFields` for a value matching another basket
 *      item's `service_identifier` (that item having errors), and
 *      `getNextRequiringSetup = getNextRelated || getNextInvalid` prefers the
 *      related one.
 *   2. `apply()` / `updateMany` merge semantics (highest silent-data-loss risk)
 *      — the current product receives the full delta merged over its existing
 *      config; selected "similar" products receive `provisionFields` ONLY; the
 *      `updateMany` call is a full-basket REPLACE, so every product must be
 *      re-listed or it is dropped. The contract under test is the OUTGOING
 *      `updateMany` request body, asserted against a real basket.
 *   3. `reset()` singleton lifecycle — the module-level state
 *      (`bpid`/`schema`/`uischema`/`similarProducts`/`selected`) is a singleton;
 *      it must clear on `reset()`.
 *
 * ## Unblocked by the FE-2937 headless generator (this worktree)
 * These were `it.todo` blocked on FE-2784's invalid-basket seeding rails: no
 * recorded basket body carried a product with validation `errors` +
 * `provisionFields`, and integration is fixtures-only (never the real API) and
 * may not fabricate domain data (ADR 021 §Core Principle 3). That fixture now
 * EXISTS — `./fixtures/` was generated by `product-setup.fixtures.ts` driving a
 * REAL guest storefront flow on staging in headless chromium (FE-2937 mode (b)),
 * seating TWO bare configurable domains so the `PATCH …/provision_fields/values/
 * check` returns a 409 whose per-field errors become the basket's `basketErrors`.
 * The tests below drive the REAL `useProductSetup` over that fixture via MSW
 * replay (`setup.integration.ts`); the assertions come from the FE-2796/FE-2457
 * spec, not from reading `useProductSetup.ts`.
 *
 * ## Two captures back these tests
 * 1. The two-BARE-domain basket (above) — invalid domains with NULL
 *    `service_identifier`, driving the apply()/updateMany merge + REPLACE
 *    contract and the reset() clear.
 * 2. A CONFIGURED cross-referenced basket — two invalid domains each given an
 *    `sld` (so each carries a DISTINCT non-null `service_identifier`) plus a
 *    valid hosting product whose `domain` provisionField references DOMAIN_ORG's
 *    service_identifier. This is the seam getNextRelated / getNextRequiringSetup
 *    and the "similar products" propagation need. It lives beside the bare
 *    capture under synthetic `case=` fixture identities (the discrimination
 *    session-store uses), wired onto the live routes by `bootConfiguredBasket`
 *    — the per-product endpoints dispatched by recorded bpid so the id-masked
 *    identity does not collapse them.
 *
 * ## What is now live, and what stays blocked
 * 10 of the 12 are live. Two remain `it.todo`, each with a precise tag:
 *   - `getNextInvalid` actor-exclusion — a headless CORE bug (reject keys on a
 *     top-level `productId` that lives under `.configuration.productId`), NOT a
 *     capture gap. Proof + staged fix live in the lane (c) unit
 *     `useProductSetup.getNextInvalid.test.ts` + `docs/plans/fe2796-getnextinvalid.patch`.
 *   - fresh-DISTINCT-schema on configure() re-entry — needs two invalid products
 *     with DIFFERENT invalid schemas; this capture's two invalid products are
 *     both domains (identical registrant schema). Fresh similarProducts on
 *     re-entry IS proven.
 */

import { join } from "node:path";
import { http, HttpResponse } from "msw";
import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import { getFixtureBody } from "@upmind-automation/test-fixtures";
import { clearSessionCookies } from "../../../__tests__/int-test-helpers";
import { useBasket } from "../../basket";
import {
  basketProductServices,
  type BasketProduct
} from "../../basket-product";
import { useSessionStore } from "../../session-store";
import { useProductSetup } from "../useProductSetup";
import { server } from "./setup.integration";
import type { UseBasket } from "../../basket";

const recordingsDir = join(import.meta.dirname, "fixtures");

// The slds the CONFIGURED cross-referenced capture seats on each domain (see
// product-setup.fixtures.ts). Each becomes the domain's `service_identifier`
// (`<sld>.<tld>`); asserting a similar product keeps its OWN sld proves the
// provisionFields-only propagation never clobbers across products.
const SLD_A = "fixturegenalpha"; // DOMAIN_AU → fixturegenalpha.au
const SLD_B = "fixturegenbeta"; // DOMAIN_ORG → fixturegenbeta.org

// -----------------------------------------------------------------------------

// Fields the 409 provision-check rejected on each bare domain — the invalid
// schema `configure()` captures is scoped to exactly these, so a model that
// fills them produces a non-empty `apply()` delta.
const REGISTRANT_MODEL = {
  provisionFields: {
    sld: "fixturegen-example",
    update_registrant_name: "Fixture Gen",
    update_registrant_organisation: "Fixture Org",
    update_registrant_email: "fixturegen@example.com",
    update_registrant_phone: "+15551234567",
    update_registrant_address_1: "1 Fixture Way",
    update_registrant_address_city: "Testville",
    update_registrant_address_postcode: "TE5 7ER",
    update_registrant_address_country_code: "GB"
  }
} as const;

/**
 * Boot a real guest session and settle the real `useBasket` machine over the
 * replayed invalid basket — the same live-machine drive the pilot journey uses,
 * but seeded from THIS module's own capture (no empty-basket override: the
 * recorded `orders/current` already carries the two invalid domains).
 */
async function bootInvalidBasket(): Promise<UseBasket> {
  await useSessionStore().useActions().isReady();
  const basket = useBasket();
  basket.clear();
  const settled = await basket.isReady();
  if (!settled) {
    throw new Error(
      `bootInvalidBasket: useBasket did not settle (state: ${JSON.stringify(
        basket.state.value.value
      )})`
    );
  }
  return basket;
}

/**
 * The bpids of the three products in the CONFIGURED cross-referenced basket, in
 * captured order: two invalid domains carrying distinct non-null
 * `service_identifier`s (from their slds) and a valid hosting product whose
 * `domain` provisionField references DOMAIN_ORG's service_identifier.
 */
interface ConfiguredIds {
  domainA: string; // .au, service_identifier fixturegenalpha.au, invalid
  domainB: string; // .org, service_identifier fixturegenbeta.org, invalid
  hosting: string; // references domainB's service_identifier, valid
  hostingProduct: string; // the hosting product_id (for its provision-field defs)
  domainBService: string; // fixturegenbeta.org
}

/**
 * Boot the CONFIGURED cross-referenced basket (FE-2796 second capture).
 *
 * The base `orders/current` / `check` / per-product fixtures describe the
 * two-BARE-domain basket; the configured basket lives alongside them under
 * synthetic `case=` fixture identities (the same discrimination session-store
 * uses) so it never collides on disk. This helper wires those `case=` bodies
 * onto the routes the live machines actually call (which carry no `case` param),
 * dispatching the per-product endpoints by the recorded bpid, then settles the
 * REAL `useBasket` machine over them. No domain data is fabricated — every body
 * is a real capture loaded via `getFixtureBody`.
 */
async function bootConfiguredBasket(): Promise<{
  basket: UseBasket;
  ids: ConfiguredIds;
}> {
  const currentBody = getFixtureBody<{
    data: {
      products: Array<{
        id: string;
        product_id: string;
        service_identifier: string;
      }>;
    };
  }>("get-orders-current-case-related", { recordingsDir });
  const products = currentBody.data.products;
  const ids: ConfiguredIds = {
    domainA: products[0].id,
    domainB: products[1].id,
    hosting: products[2].id,
    hostingProduct: products[2].product_id,
    domainBService: products[1].service_identifier
  };

  const checkBody = getFixtureBody(
    "patch-orders-id-provision-fields-values-check-case-related",
    { recordingsDir }
  );
  const valuesA = getFixtureBody(
    "get-orders-id-products-id-provision-fields-values-case-related-a",
    { recordingsDir }
  );
  const valuesB = getFixtureBody(
    "get-orders-id-products-id-provision-fields-values-case-related-b",
    { recordingsDir }
  );
  const valuesHost = getFixtureBody(
    "get-orders-id-products-id-provision-fields-values-case-related-host",
    { recordingsDir }
  );
  const hostingConfig = getFixtureBody(
    "get-basket-id-products-id-basket-id-basket-product-id-case-related-host",
    { recordingsDir }
  );
  const hostingDefs = getFixtureBody(
    "get-basket-products-id-provision-fields-case-related-host",
    { recordingsDir }
  );

  server?.use(
    // the rich basket + its (registrant-only) provision-check failure
    http.get("*/api/orders/current", () =>
      HttpResponse.json(currentBody as object)
    ),
    http.patch("*/api/orders/:oid/provision_fields/values/check", () =>
      HttpResponse.json(checkBody as object, { status: 409 })
    ),
    // each product's provisionFields VALUES — dispatched by the recorded bpid so
    // the hosting product's `domain` cross-reference and each domain's sld land
    // on the right product (the id-masked identity alone would collapse them).
    http.get(
      "*/api/orders/:oid/products/:bpid/provision_fields/values",
      ({ params }) => {
        if (params.bpid === ids.domainA)
          return HttpResponse.json(valuesA as object);
        if (params.bpid === ids.domainB)
          return HttpResponse.json(valuesB as object);
        if (params.bpid === ids.hosting)
          return HttpResponse.json(valuesHost as object);
        return undefined;
      }
    ),
    // the hosting product config + its own field defs, so configure(hosting)
    // resolves against ITS blueprint; the two domains fall through to the base
    // domain config (correct — they ARE domains).
    http.get("*/api/basket/:bid/products/:bpid", ({ params }) =>
      params.bpid === ids.hosting
        ? HttpResponse.json(hostingConfig as object)
        : undefined
    ),
    http.get("*/api/basket/products/:pid/provision_fields", ({ params }) =>
      params.pid === ids.hostingProduct
        ? HttpResponse.json(hostingDefs as object)
        : undefined
    )
  );

  await useSessionStore().useActions().isReady();
  const basket = useBasket();
  basket.clear();
  const settled = await basket.isReady();
  if (!settled) {
    throw new Error(
      `bootConfiguredBasket: useBasket did not settle (state: ${JSON.stringify(
        basket.state.value.value
      )})`
    );
  }
  return { basket, ids };
}

// -----------------------------------------------------------------------------

describe("useProductSetup — invalid-basket integration (FE-2796)", () => {
  beforeEach(() => {
    clearSessionCookies();
    useSessionStore().useActions().clear();
    useProductSetup().reset();
  });

  afterEach(() => {
    vi.restoreAllMocks();
    useProductSetup().reset();
  });

  // --- routing ----------------------------------------------------------------

  describe("getNextRelated / getNextInvalid — routing", () => {
    // Unblocked by the CONFIGURED cross-referenced capture: the hosting product's
    // `domain` provisionField holds DOMAIN_ORG's service_identifier, and that
    // domain is invalid — the exact cross-reference getNextRelated walks.
    it("routes to the basket item whose service_identifier is referenced by the actor's provisionFields AND which itself has errors", async () => {
      const { ids } = await bootConfiguredBasket();
      const setup = useProductSetup();
      await setup.isReady();

      // The ACTOR is the hosting product; its provisionFields reference the
      // .org domain's service_identifier (fixturegenbeta.org).
      const hostingConfig = await setup.configure(ids.hosting);
      const related = setup.getNextRelated(hostingConfig.service);

      expect(related, "a related basket item was found").toBeDefined();
      // getNextRelated returns the DOMAIN whose service_identifier the hosting
      // references — not the hosting product itself.
      expect(related!.id).toBe(ids.domainB);
      expect(related!.serviceIdentifier).toBe(ids.domainBService);
      // and that referenced domain really does still have errors.
      expect(related!.errors, "the referenced domain has errors").not.toEqual(
        []
      );
    });

    // Unblocked by the same capture: getNextRelated resolves the referenced
    // .org domain (products[1]) while getNextInvalid resolves the first
    // setup-requiring product (products[0], the .au domain) — so the two differ,
    // letting us prove getNextRequiringSetup prefers the related one.
    it("getNextRequiringSetup prioritises a related product (getNextRelated) over a merely-invalid one (getNextInvalid)", async () => {
      const { ids } = await bootConfiguredBasket();
      const setup = useProductSetup();
      await setup.isReady();

      const hostingConfig = await setup.configure(ids.hosting);

      const related = setup.getNextRelated(hostingConfig.service);
      const invalid = setup.getNextInvalid(hostingConfig.service);
      const requiring = setup.getNextRequiringSetup(hostingConfig.service);

      // The two routing strategies resolve DIFFERENT products for this actor…
      expect(related!.id).toBe(ids.domainB);
      expect(invalid!.id).toBe(ids.domainA);
      expect(requiring!.id).not.toBe(invalid!.id);
      // …and getNextRequiringSetup prefers the related one.
      expect(requiring!.id).toBe(related!.id);
    });

    // BLOCKED (headless core bug, NOT a capture gap): `getNextInvalid` rejects on
    // a TOP-LEVEL `productId` that `BasketProduct` exposes under
    // `.configuration.productId`, so the reject is inert and it always returns
    // `first(products)` — including the actor's own product. That cannot be
    // asserted green from the test layer without weakening the contract or
    // editing read-only headless source. The actor-exclusion PROOF lives in the
    // lane (c) unit `useProductSetup.getNextInvalid.test.ts` (committed `it.fails`),
    // and the one-line fix is staged at `docs/plans/fe2796-getnextinvalid.patch`.
    // Once that patch lands, drop `.fails` there and promote this integration
    // todo (the configured capture already seats two DISTINCT-productId invalid
    // domains — bpids domainA/domainB above — ready to drive it).
    it.todo(
      "getNextInvalid returns the next product requiring setup, excluding the actor's own product"
    );

    it("getNextRelated returns undefined when the actor's provisionFields reference no other basket item", async () => {
      await bootInvalidBasket();
      const setup = useProductSetup();
      await setup.isReady();

      const actorProduct = setup.products.value[0];
      const config = await setup.configure(actorProduct.id);

      // The actor is a CONFIGURABLE domain: its provisionFields are non-empty
      // (registrant keys) — so this exercises the real matching branch, not the
      // isEmpty early-return. No basket item's service_identifier is referenced,
      // so the result is undefined.
      const related = setup.getNextRelated(config.service);
      expect(related).toBeUndefined();
    });
  });

  // --- apply / updateMany -----------------------------------------------------

  describe("apply — updateMany merge semantics", () => {
    // Unblocked by the CONFIGURED capture: two invalid domains with DISTINCT
    // non-null service_identifiers (their slds) and overlapping registrant error
    // paths — so configuring one selects the other as a "similar" product.
    it("limits selected 'similar' products to provisionFields ONLY — term/quantity/options/attributes never propagate across products", async () => {
      const spy = vi
        .spyOn(basketProductServices, "updateMany")
        .mockResolvedValue({} as never);

      const { basket, ids } = await bootConfiguredBasket();
      const setup = useProductSetup();
      await setup.isReady();

      const current = setup.products.value.find(p => p.id === ids.domainA)!;
      const similarBefore = basket.products.value!.find(
        p => p.id === ids.domainB
      )!;
      const similarTerm = similarBefore.configuration.term;
      const similarQuantity = similarBefore.configuration.quantity;

      await setup.configure(current.id);
      // The other configured domain is captured as similar and auto-selected.
      expect(setup.similarProducts.value.map(p => p.id)).toEqual([ids.domainB]);
      expect(setup.selected.value).toContain(ids.domainB);

      await setup.apply(REGISTRANT_MODEL);

      const payload = spy.mock.calls[0][1] as BasketProduct[];
      const similarPayload = payload.find(p => p.id === ids.domainB);
      expect(similarPayload).toBeDefined();

      // provisionFields the user filled DO propagate to the similar product…
      expect(
        similarPayload!.configuration.provisionFields.update_registrant_name
      ).toBe(REGISTRANT_MODEL.provisionFields.update_registrant_name);
      // …but term / quantity never do — the similar product keeps its own.
      expect(similarPayload!.configuration.term).toBe(similarTerm);
      expect(similarPayload!.configuration.quantity).toBe(similarQuantity);
      // and its OWN sld survives — the current product's sld never leaked across
      // (provisionFields only FILL holes on similars, they never clobber).
      expect(similarPayload!.configuration.provisionFields.sld).toBe(SLD_B);
      expect(similarPayload!.configuration.provisionFields.sld).not.toBe(SLD_A);
    });

    it("merges the current product's delta over its existing config — the user's submitted provision values win", async () => {
      const spy = vi
        .spyOn(basketProductServices, "updateMany")
        .mockResolvedValue({} as never);

      await bootInvalidBasket();
      const setup = useProductSetup();
      await setup.isReady();

      const current = setup.products.value[0];
      await setup.configure(current.id);
      expect(
        setup.schema.value,
        "invalid schema captured at configure"
      ).toBeTruthy();

      await setup.apply(REGISTRANT_MODEL);

      expect(spy).toHaveBeenCalledTimes(1);
      const payload = spy.mock.calls[0][1] as BasketProduct[];
      const currentPayload = payload.find(p => p.id === current.id);
      expect(currentPayload).toBeDefined();
      // The user's submitted registrant values are present on the current product.
      expect(
        currentPayload!.configuration.provisionFields.update_registrant_name
      ).toBe(REGISTRANT_MODEL.provisionFields.update_registrant_name);
      expect(
        currentPayload!.configuration.provisionFields.update_registrant_email
      ).toBe(REGISTRANT_MODEL.provisionFields.update_registrant_email);
    });

    it("calls updateMany with a full-basket REPLACE payload — every basket product is re-listed so none is silently dropped", async () => {
      const spy = vi
        .spyOn(basketProductServices, "updateMany")
        .mockResolvedValue({} as never);

      const basket = await bootInvalidBasket();
      const setup = useProductSetup();
      await setup.isReady();

      const current = setup.products.value[0];
      await setup.configure(current.id);
      await setup.apply(REGISTRANT_MODEL);

      expect(spy).toHaveBeenCalledTimes(1);
      const payload = spy.mock.calls[0][1] as BasketProduct[];
      // REPLACE: the payload re-lists EVERY basket product (not just the edited).
      expect(payload).toHaveLength(basket.products.value!.length);
      const ids = payload.map(p => p.id).sort();
      const basketIds = basket.products.value!.map(p => p.id).sort();
      expect(ids).toEqual(basketIds);
    });

    it("asserts the outgoing updateMany request body against a real basket (contract-level, not merge eyeballed through the browser)", async () => {
      const spy = vi
        .spyOn(basketProductServices, "updateMany")
        .mockResolvedValue({} as never);

      const basket = await bootInvalidBasket();
      const setup = useProductSetup();
      await setup.isReady();

      const current = setup.products.value[0];
      await setup.configure(current.id);
      await setup.apply(REGISTRANT_MODEL);

      // The collaborator seam is called with the live basket id and the full
      // product array — the contract the browser flow depends on.
      const [basketId, payload, models] = spy.mock.calls[0] as [
        string,
        BasketProduct[],
        unknown[]
      ];
      expect(basketId).toBe(basket.basketId.value);
      expect(Array.isArray(payload)).toBe(true);
      expect(payload.length).toBeGreaterThan(0);
      expect(models).toEqual([]);
    });

    it("leaves products that are NOT in [bpid, ...selected] untouched in the updateMany payload", async () => {
      const spy = vi
        .spyOn(basketProductServices, "updateMany")
        .mockResolvedValue({} as never);

      await bootInvalidBasket();
      const setup = useProductSetup();
      await setup.isReady();

      const current = setup.products.value[0];
      const untouched = setup.products.value[1];
      await setup.configure(current.id);
      // No similars for a null-service_identifier domain, so selected is empty:
      expect(setup.selected.value).toEqual([]);

      await setup.apply(REGISTRANT_MODEL);

      const payload = spy.mock.calls[0][1] as BasketProduct[];
      const untouchedPayload = payload.find(p => p.id === untouched.id);
      expect(untouchedPayload).toBeDefined();
      // The untouched product carries none of the current product's submitted
      // registrant values — it passed through verbatim.
      expect(
        untouchedPayload!.configuration.provisionFields?.update_registrant_name
      ).not.toBe(REGISTRANT_MODEL.provisionFields.update_registrant_name);
    });
  });

  // --- reset lifecycle --------------------------------------------------------

  describe("reset — singleton lifecycle", () => {
    it("clears module-level bpid/schema/uischema/similarProducts/selected on reset()", async () => {
      await bootInvalidBasket();
      const setup = useProductSetup();
      await setup.isReady();

      const current = setup.products.value[0];
      await setup.configure(current.id);
      // Populated by configure() on an invalid product.
      expect(setup.schema.value).toBeTruthy();
      expect(setup.uischema.value).toBeTruthy();

      setup.reset();

      expect(setup.schema.value).toBeUndefined();
      expect(setup.uischema.value).toBeUndefined();
      expect(setup.similarProducts.value).toEqual([]);
      expect(setup.selected.value).toEqual([]);
    });

    // STILL BLOCKED (needs a richer capture than this one): proving a fresh
    // *schema* on re-entry needs two invalid products with DIFFERENT invalid
    // schemas. The `case=related-host` fixtures now dispatch the hosting config
    // by bpid (so per-product blueprints no longer collapse to one identity — the
    // original blocker), BUT the two INVALID products in this capture are both
    // domains sharing the identical registrant schema, and the hosting product is
    // VALID (empty invalid schema). So a re-entry between them cannot exhibit a
    // DISTINCT non-empty schema. (Fresh *similarProducts* on re-entry IS now
    // proven — see the sibling "no residual similarProducts" test.)
    // NEXT SEED: two INVALID products of different types with disjoint error
    // field sets (e.g. a domain missing registrant + a hosting product missing a
    // required field), so their invalid schemas differ.
    it.todo(
      "configure() re-entry after reset() captures a fresh schema + similarProducts for the new bpid — no stale state leaks from the previous product"
    );

    // Unblocked by the CONFIGURED capture: two invalid domains that are each
    // other's "similar" product, so a partial cycle leaves a non-empty
    // similarProducts that reset() must clear before the next product.
    it("a partial configure() -> (no apply) -> reset() cycle leaves no residual similarProducts for the next product set up", async () => {
      const { ids } = await bootConfiguredBasket();
      const setup = useProductSetup();
      await setup.isReady();

      // First product: configuring DOMAIN_AU selects DOMAIN_ORG as similar.
      await setup.configure(ids.domainA);
      expect(setup.similarProducts.value.map(p => p.id)).toEqual([ids.domainB]);

      // Abandon without applying.
      setup.reset();
      expect(setup.similarProducts.value).toEqual([]);
      expect(setup.selected.value).toEqual([]);

      // Re-entry for the OTHER product: similarProducts now reflects the NEW
      // product's similars (DOMAIN_AU) with no residual DOMAIN_ORG entry leaking
      // from the abandoned cycle.
      await setup.configure(ids.domainB);
      expect(setup.similarProducts.value.map(p => p.id)).toEqual([ids.domainA]);
      expect(setup.similarProducts.value.map(p => p.id)).not.toContain(
        ids.domainB
      );
    });
  });
});
