export default {
  root: ["relative", "inline-flex"],
  button: {
    root: [
      "py-3",
      "px-4",
      "inline-flex",
      "items-center",
      "gap-x-2",
      "text-sm",
      "font-medium",
      "rounded-lg",
      "border",
      "border-gray-200",
      "bg-white",
      "text-gray-800",
      "shadow-sm",
      "hover:bg-gray-50",
      "disabled:opacity-50",
      "disabled:pointer-events-none",
    ],
    label: ["leading-none"],
    icon: ["size-[1em]", "transition-all", "aria-checked:rotate-180"],
  },
  items: [
    //   "w-56",
    "min-w-60",
    "bg-base",
    "shadow-md",
    "rounded-lg",
    "p-2",

    //   "ring-1",
    //   "ring-black/5",
    //   "focus:outline-none",

    "after:h-4",
    "after:absolute",
    "after:-bottom-4",
    "after:start-0",
    "after:w-full",
    "before:h-4",
    "before:absolute",
    "before:-top-4",
    "before:start-0",
    "before:w-full",
  ],

  group: [],
  item: {
    root: [
      "w-full",
      "flex",
      "items-center",
      "gap-x-3.5",
      "py-2",
      "px-3",
      "rounded-lg",
      "text-sm",
      "text-gray-800",
      "hover:bg-gray-100",
      "focus:outline-none",
      "focus:bg-gray-100",
      "no-underline",
    ],
    icon: ["size-[1.5em]", "flex-shrink-0"],
  },
};
