/** @internal */
import { AddressTypes, DEFAULT_ADDRESS_TYPE } from "./client-address-dry.types";
import { map } from "lodash-es";
import type { Address, AddressModel } from "./client-address-dry.types";
import type { JsonSchema7, UISchemaElement } from "@jsonforms/core";
import type { ICountry, IRegion } from "@upmind-automation/types";

// -----------------------------------------------------------------------------
/**
 * @module client-address-dry/schemas
 * @description Form schema/uischema parsers for the address add/edit form.
 * Armless — SAME fields and SAME `required` list for all three cells
 * (design.md §7: D-ADDR-3's `type` restore + R10-R13 are SHARED;
 * `REQUIRE_REGION_IN_ADDRESS` is brand-config-driven, not actor-driven, so no
 * per-actor field/required divergence -> no schemas arm).
 */

type SchemaLookups = {
  id?: Address["id"];
  baseModel?: AddressModel;
  countries?: ICountry[];
  regions?: IRegion[];
  /** R12 — true when the brand config `REQUIRE_REGION_IN_ADDRESS` is set. */
  requireRegion?: boolean;
};

export function useSchemaDefinitions({
  regions,
  baseModel,
  countries,
  requireRegion
}: Partial<SchemaLookups>): JsonSchema7["definitions"] {
  const schema = {
    address: {
      type: "object",
      title: "Address",
      required: ["address1", "city", "postcode", "countryId"],
      properties: {
        address1: {
          type: "string",
          title: "Address"
        },

        address2: {
          type: ["string", "null"],
          title: ""
        },

        city: {
          type: "string",
          title: "City"
        },

        postcode: {
          type: "string",
          title: "Postcode"
        },

        regionId: {
          type: ["string", "null"],
          title: "Region",
          ...(regions?.length && {
            enum: map(regions, "id"),
            options: regions.map(region => ({
              label: region.name,
              value: region.id
            }))
          })
        },

        countryId: {
          type: "string",
          title: "Country",
          default: baseModel?.address?.countryId,
          ...(countries?.length && {
            enum: map(countries, "id"),
            options: countries.map(country => ({
              label: country.name,
              value: country.id
            }))
          })
        }
      }
    }
  };

  // R12 — regionId required only when the brand demands it (shared, not actor).
  if (requireRegion) {
    schema.address.required.push("regionId");
  }

  return schema;
}

export function useSchema({
  id,
  baseModel,
  countries,
  regions,
  requireRegion
}: SchemaLookups): JsonSchema7 {
  const schema: JsonSchema7 = {
    type: "object",
    title: "Address",
    // D-ADDR-3 — `type` restored to `required` (baseline commented it out,
    // `client-address.schemas.ts:110-121`, and forced `type: 1` on write).
    required: ["address", "type"],
    definitions: useSchemaDefinitions({
      regions,
      baseModel,
      countries,
      requireRegion
    }),
    properties: {
      id: {
        type: ["string", "null"],
        title: "ID",
        description: "The AutoGenerated ID of this Address.",
        readOnly: true
      },

      name: {
        type: ["string", "null"],
        title: "Name",
        default: baseModel?.name
      },

      address: { $ref: "#/definitions/address" },

      type: {
        type: "number",
        title: "Address Type",
        oneOf: map(AddressTypes, item => ({
          const: item.key,
          title: item.value
        })),
        default: baseModel?.type ?? DEFAULT_ADDRESS_TYPE
      }
    }
  };

  // ensure that if we are editing an existing address, that we require the name
  if (id) {
    schema.required!.push("name");
  }

  return schema;
}

export function useUischemaDefinitions({ id }: Pick<SchemaLookups, "id"> = {}) {
  return {
    type: "Control",
    scope: "#/properties/address",
    i18n: "form.address",
    options: {
      autoFocus: true,
      autocomplete: "off",
      detail: {
        type: "VerticalLayout",
        elements: [
          {
            type: "Control",
            scope: "#/properties/countryId",
            i18n: "form.country",
            options: {
              placeholder: "Select a country…"
            }
          },
          {
            type: id ? "VerticalLayout" : "address",
            i18n: "form.address",
            options: {
              fields: ["address1", "address2"],
              placeholder: "Start typing your address",
              autoFocus: true
            },
            elements: [
              {
                type: "Group",
                options: {
                  border: false
                },
                elements: [
                  {
                    type: "Control",
                    scope: "#/properties/address1",
                    i18n: "form.address1",
                    options: {
                      placeholder: "House name, apartment number etc.",
                      autocomplete: "address-line1",
                      autoFocus: true
                    }
                  },
                  {
                    type: "Control",
                    scope: "#/properties/address2",
                    i18n: "form.address2",
                    options: {
                      placeholder: "Road, street name etc.",
                      autocomplete: "address-line2"
                    }
                  }
                ]
              },
              {
                type: "Control",
                scope: "#/properties/city",
                i18n: "form.city",
                options: {
                  placeholder: "City, town etc.",
                  autocomplete: "address-level2"
                }
              },
              {
                type: "HorizontalLayout",
                elements: [
                  {
                    type: "Control",
                    scope: "#/properties/regionId",
                    i18n: "form.region",
                    options: {
                      placeholder: "Select a region…",
                      autocomplete: "address-level1"
                    }
                  },
                  {
                    type: "Control",
                    scope: "#/properties/postcode",
                    i18n: "form.postcode",
                    options: {
                      placeholder: "eg. 10011",
                      autocomplete: "postal-code"
                    }
                  }
                ]
              }
            ]
          }
        ]
      }
    }
  };
}

export function useUischema({
  id
}: Pick<SchemaLookups, "id"> = {}): UISchemaElement {
  const schema = {
    type: "VerticalLayout",
    elements: [
      useUischemaDefinitions({ id }),
      // D-ADDR-3 — restored control (baseline commented this field out
      // entirely alongside its schema counterpart).
      {
        type: "Control",
        scope: "#/properties/type",
        i18n: "form.address_type"
      }
    ]
  };

  return schema as UISchemaElement;
}
