# client-emails — the CANARY spec pair, EXECUTED (ADR-027 Am.2).
#
# Distinct from the sibling `client-email.feature`, which is the module's
# spec-only capability record (ADR-020: no steps file, no runner, read only by
# `client-email.traceability.test.ts`). This file is the executed half: every
# step below resolves in `client-email.canary.steps.ts`, and `playgrounds/labs-nuxt`'s
# Playwright lane drives it through the `world` bridge over the RECORDED corpus.
#
# Declarative only — no selector, URL or UI mechanic appears here, and the steps
# reach the module through the five `World` members and nothing else.
#
# Three AC7 read-backs are NOT here, because the `World` seam cannot express
# them (`world.types.ts` — five members, no page, no wire and no reload): the
# RENDERED row order after a sort, survival across a reload, and the sort field
# the module does not offer never reaching the wire. All three are proven in
# `playgrounds/labs-nuxt/tests/e2e/client-emails-filter-sort.spec.ts`, tagged
# `@AC7`, which the same `--grep "@AC7"` selects.
#
# The FE-2824 watch-point is HALF proven here. The staff scenario proves the
# staff cell boots and reads the named client's collection; it does NOT prove the
# identity TRANSPORT (which token, which acting-as headers), because the recorded
# session pool holds a client capture and a guest capture and no staff one. That
# half stays in the integration lane's `assertClientIdentityTransport`, and a
# staff capture is a recording gap, not a test to fake.

@FE-2977 @canary
Feature: Client email management, generated by the flow factory
  As a developer validating the client-emails module
  I want its whole behaviour driven in a generated UI across every scope
  So that I can prove it works before the real client app exists

  Background:
    Given the client-emails playground is generated for the active client

  @layer-e2e @smoke
  Scenario: A client sees their email collection
    Then the collection holds 3 addresses
    And "mock-email-1@example.com" is listed
    And "mock-email-3@example.com" is listed
    And "mock-email-4@example.com" is listed

  @layer-e2e @smoke
  Scenario: A client adds an email address
    When the client adds the address "mock-email-9@example.com"
    Then the collection reports no failure

  @layer-e2e
  Scenario: A client deletes an email address
    When the client deletes the address the server allows them to delete
    Then the collection reports no failure

  @layer-e2e
  Scenario: A client resends a verification email
    When the client resends the verification for their unverified address
    Then the collection reports no failure

  @layer-e2e
  Scenario: A client sets a default email
    When the client makes their non-default address the default
    Then the collection reports no failure

  @layer-e2e
  Scenario: A client refreshes their collection
    When the client refreshes the collection
    Then the collection holds 3 addresses
    And the collection reports no failure

  @layer-e2e
  Scenario: Asking for a page that is not there is refused, not guessed
    When the client asks for a next page they do not have
    And the client asks for a previous page they do not have
    Then the collection holds 3 addresses
    And the collection reports no failure

  @layer-e2e
  Scenario: Discarding the collection releases it
    When the client discards the collection
    Then the collection reports no failure

  @layer-e2e @AC7
  Scenario: Filtering narrows the collection
    When the client filters to unverified addresses only
    Then the collection holds 2 addresses
    And "mock-email-3@example.com" is listed
    And "mock-email-4@example.com" is listed
    And the collection reports that it is filtered

  @layer-e2e @AC7
  Scenario: Sorting reorders the collection
    When the client sorts the collection by address descending
    Then the collection is sorted by "email" descending
    And the collection reports no failure

  @layer-e2e @fe-2824
  Scenario: Staff acting for a client read that client's collection
    Given a staff member acting for that client
    Then the collection holds 3 addresses
    And "mock-email-1@example.com" is listed
