// --- types
import type { JsonSchema7, UISchemaElement } from "@jsonforms/core";

export const useSchema = (): JsonSchema7 => {
  const schema: JsonSchema7 = {
    type: "object",
    title: "Address Fields",
    required: ["email"],
    properties: {
      id: {
        type: ["string", "null"],
        title: "ID",
        description: "The AutoGenerated ID of this Email.",
        readOnly: true,
      },

      email: {
        type: "string",
        format: "email",
        title: "Email",
      },

      // --- DEPRECATED

      // type: {
      //   type: "number",
      //   const: 1,
      //   readOnly: true,
      // },

      // default: {
      //   type: ["boolean", "null"],
      //   title: "Make this the default email?",
      // },
    },
  };

  return schema;
};

export const useUischema = () => {
  const schema = {
    type: "VerticalLayout",
    elements: [
      {
        type: "Control",
        scope: "#/properties/id",
        rule: {
          effect: "HIDE",
          condition: { const: true },
        },
      }, // HACK: need to force hide this otherwise the id renders in hte email field?

      {
        type: "Control",
        scope: "#/properties/email",
        options: {
          autoFocus: true,
          autocomplete: "email",
          placeholder: "name@email.com",
        },
      },
    ],
  };

  return schema as UISchemaElement;
};
