// --- external

// --- internal

// --- utils
import { map, isArray } from "lodash-es";
export { useModelParser } from "../../../utils";

// --- types
import type { Email } from "./types";
import type { IEmail } from "@upmind-automation/types";
import type { JsonSchema, UISchemaElement } from "@jsonforms/core";

// ---
export const useSchema = () => {
  const schema = {
    type: "object",
    title: "Address Fields",
    required: ["email"],
    properties: {
      id: {
        type: ["string", "null"],
        title: "ID",
        description: "The AutoGenerated ID of this Email.",
        readOnly: true,
      },

      // ---
      type: {
        type: "number",
        const: 1,
      },

      email: {
        type: ["string", "null"],
        format: "email",
        title: "Email",
      },

      // ---

      default: {
        type: ["boolean", "null"],
        title: "Make this the default email?",
      },
    },
  };

  return schema as JsonSchema;
};

export const useUischema = () => {
  const schema = {
    type: "VerticalLayout",
    elements: [
      {
        type: "Control",
        scope: "#/properties/username",
        options: {
          autoFocus: true,
          autocomplete: "email",
          placeholder: "name@email.com",
        },
      },

      // ---
      // We dont ever show this field as it is set by an action
      // {
      //   type: "Control",
      //   scope: "#/properties/default",
      //   options: {
      //     // toggle: true
      //   }
      // }
    ],
  };

  return schema as UISchemaElement;
};

// ---
export const parseEmail = (raw: IEmail | IEmail[]): Email[] => {
  const rawListings = isArray(raw) ? raw : [raw];
  return map(rawListings, rawItem => {
    return {
      id: rawItem.id,
      type: rawItem.type,
      email: rawItem.email,
      title: rawItem.email,
      description: rawItem.verified ? "Verified" : "Unverified",
    };
  });
};
