export const Languages = [
  { language: "English", locale: "en" },
  { language: "English (US)", locale: "en-US" },
  { language: "French", locale: "fr" },
  { language: "German", locale: "de" },
  { language: "Greek", locale: "el" },
  { language: "Danish", locale: "da" },
  { language: "Polish", locale: "pl" },
  { language: "Spanish", locale: "es" },
  { language: "Portuguese", locale: "pt" },
  { language: "Italian", locale: "it" },
  { language: "Bulgarian", locale: "bg" },
  { language: "Azerbaijani", locale: "az" },
  { language: "Dutch", locale: "nl" },
  { language: "Indonesian", locale: "id" },
  { language: "Norwegian Bokmål", locale: "nb" },
  { language: "Turkish", locale: "tr" },
  { language: "Ukranian", locale: "uk" },
  { language: "Urdu", locale: "ur" },
  { language: "Russian", locale: "ru" },
  { language: "French (Canada)", locale: "fr-CA" },
  { language: "Chinese (Taiwan, Traditional)", locale: "zh-TW" },
  { language: "Spanish (Latin America)", locale: "es-419" },
  { language: "Romanian", locale: "ro" },
  { language: "Czech", locale: "cs" },
  { language: "Slovak", locale: "sk" },
  { language: "Portuguese (Brazil)", locale: "pt-BR" },
  { language: "Swedish", locale: "sv" },
  { language: "Hungarian", locale: "hu" }
];
