import type {
  IBasketProduct,
  IBasketPromotion
} from "@upmind-automation/types";
import type { ProductProps, Product } from "../product";
import type { UseBasketProduct } from "./useBasketProduct";
// -----------------------------------------------------------------------------

/**
 * Interface representing the context for a basket helper, which facilitates
 * the conversion and management of products between a generic type `T` and
 * the specific `IBasketProduct` format required by the basket.
 *
 * @template T - The generic type of product model this helper context is designed to manage.
 */
export interface BasketHelperContext<T = unknown> {
  /**
   * Allows for additional dynamic properties on the context.
   * @ignore
   */
  [key: string]: any;
  /**
   * Converts an `IBasketProduct` from the main basket into a specific model type `T` (e.g. from `IBasketProduct` to `DomainProduct`).
   *
   * @param product - The `IBasketProduct` to parse.
   * @param context - Optional additional context for the parsing process.
   * @returns The parsed product model of type `T`, or `undefined` if parsing fails.
   */
  parseBasketProduct: (product: IBasketProduct, context?: any) => T | undefined;
  /**
   * Converts a generic model of type `T` into the correct `ProductProps` model required to be added to the basket.
   *
   * @param model - The model of type `T` to parse.
   * @returns The parsed `ProductProps` model, or `undefined` if parsing fails.
   */
  parseProductModel: (model: T) => ProductProps | undefined;

  /**
   * An array of `IBasketPromotion` objects that apply to the basket.
   */
  promotions?: IBasketPromotion[];
}

/**
 * Interface representing a product that is already in the shopping basket.
 * It extends the base {@link Product} interface and guarantees the presence of an `id`.
 */
export interface BasketProduct extends Product {
  /**
   * Basket Products will always have an ID, unlike pending products.
   * This is the unique identifier for the product *within the basket*.
   */
  id: string;
  /**
   * The service identifier is generated by the basket and is used to uniquely identify
   * the product's associated service in the basket.
   *
   * e.g.
   * - A domain product often has a service identifier of the domain name.
   * - A Hosting product often has a service identifier of the associated domain name.
   */
  serviceIdentifier?: string;
}

/**
 * Interface representing the data model for a subproduct within a basket product.
 * This defines how subproducts (like add-ons or options) are structured when
 * being added or configured in the basket.
 */
export interface IBasketSubproductModel {
  /**
   * The unique identifier of the subproduct.
   */
  product_id: string;
  /**
   * The quantity of the subproduct.
   */
  unit_quantity: number;
  /**
   * The billing cycle duration in months for the subproduct.
   */
  billing_cycle_months: number;
}

/**
 * Interface representing the data model for a product when it's being added
 * to or configured within the shopping basket. It includes core product details
 * and optional configurations for attributes, options, provisioning, and promotions.
 */
export interface IBasketProductModel {
  /**
   * The unique identifier of the main product.
   */
  product_id: string;
  /**
   * The quantity of the main product.
   */
  quantity: number;
  /**
   * The billing cycle duration in months for the main product.
   */
  billing_cycle_months: number;
  // ---
  /**
   * An optional array of {@link IBasketSubproductModel} for product attributes.
   */
  attributes?: IBasketSubproductModel[];
  /**
   * An optional array of {@link IBasketSubproductModel} for product options.
   */
  options?: IBasketSubproductModel[];
  /**
   * Optional key-value pairs for provisioning field values required for the product.
   */
  provision_field_values?: Record<string, any>;

  /**
   * An optional flag indicating whether to validate the provisioning field values when adding the product to the basket.
   */
  provision_field_values_validate?: boolean;
  /**
   * An optional array of promotion codes to apply to this product in the basket.
   */
  promotions?: { promocode: string }[];
  /**
   * An optional flag indicating whether to start a free trial for this product.
   */
  start_trial?: boolean;
}
