import type {
  IBasketProduct,
  IBasketPromotion
} from "@upmind-automation/types";
import type { ProductProps, Product } from "../product";
// -----------------------------------------------------------------------------

export interface BasketHelperContext<T = unknown> {
  [key: string]: any;
  // Converts a basket product to an unknown Typem eg: From BasketProduct to DomainProduct
  parseBasketProduct: (product: IBasketProduct, context?: any) => T | undefined;
  //  Converts an unknown model into the correct product model to be added to the basket
  parseProductModel: (model: T) => ProductProps | undefined;

  promotions?: IBasketPromotion[];
}

export interface BasketProduct extends Product {
  /**
   * Basket Products will always have am ID, unlike the pending products.
   */
  id: string;
  /**
   * The service identifier is generated by the basket and is used to identify the product in the basket.
   * eg:
   * A domain products often has a service identifier of the domain name.
   * A Hosting product often has a service identifier of the assosciated domain name.
   */
  serviceIdentifier?: string;
}

export interface IBasketSubproductModel {
  product_id: string;
  unit_quantity: number;
  billing_cycle_months: number;
}

export interface IBasketProductModel {
  product_id: string;
  quantity: number;
  billing_cycle_months: number;
  // ---
  attributes?: IBasketSubproductModel[];
  options?: IBasketSubproductModel[];
  provision_field_values?: Record<string, any>;
  promotions?: { promocode: string }[];
}
