// --- utils
import { map } from "lodash-es";

// --- internal
import { useClientAddresses } from "../address";
import { useClientAddress } from "../address";

// --- types
import type { CompanyContext } from "./types";
import type { JsonSchema, UISchemaElement } from "@jsonforms/core";
import type { Address } from "../address";

export const useSchema = ({
  baseModel,
  model,
  phones,
  country,
}: CompanyContext) => {
  const schema: JsonSchema = {
    type: "object",
    title: "Company",
    required: ["name"],
    properties: {
      id: {
        type: ["string", "null"],
        title: "ID",
        description: "The AutoGenerated ID of this Company.",
        readOnly: true,
        default: baseModel?.id,
      },
      name: {
        type: "string",
        title: "Company Name",
        default: baseModel?.name,
      },
      regNumber: {
        type: ["string", "null"],
        title: "Company Number",
        default: baseModel?.regNumber,
      },
      vatNumber: {
        type: ["string", "null"],
        title: "Registered Tax ID",
        default: baseModel?.vatNumber,
      },
      addressId: {
        type: ["string", "null"],
        title: "Address",
        default: baseModel?.addressId,
      },
      emailId: {
        type: ["string", "null"],
        title: "Email",
        default: baseModel?.emailId,
      },
    },
    anyOf: [
      {
        properties: {
          addressId: {
            type: "string",
          },
        },
        required: ["addressId"],
      },
      {
        properties: {
          addressId: {
            type: ["null"],
          },
          address: {
            properties: {
              address1: { type: "string" },
              city: { type: "string" },
              postcode: { type: "string" },
              countryId: { type: "string" },
            },
            required: ["address1", "city", "postcode", "countryId"],
          },
        },
        required: ["address"],
      },
    ],
  };

  return schema as JsonSchema;
};

export const useUischema = ({ addresses }: CompanyContext) => {
  const uiSchema = {
    type: "VerticalLayout",
    elements: [
      {
        type: "Control",
        scope: "#/properties/name",
        options: {
          autoFocus: true,
          autocomplete: "off",
          placeholder: "My company name",
        },
      },
      {
        type: "HorizontalLayout",
        elements: [
          {
            type: "Control",
            scope: "#/properties/regNumber",
            options: {
              placeholder: "Registered tax or GST",
            },
          },
          {
            type: "Control",
            scope: "#/properties/vatNumber",
            options: {
              placeholder: "VAT Number",
            },
          },
        ],
      },
      {
        type: "ModelList",
        scope: "#/properties/addressId",
        options: {
          label: "",
          use: useClientAddresses,
          modify: useClientAddress,
        },
      },
    ],
  };

  return uiSchema as UISchemaElement;
};
