// --- utils

// --- internal
import { useClientAddresses, useClientAddress } from "../address";
import { useSchema as useAddressSchema } from "../address/schemas";

// --- types
import type { CompanyContext } from "./types";
import type { JsonSchema7, UISchemaElement } from "@jsonforms/core";

export const useSchema = ({ baseModel }: CompanyContext): JsonSchema7 => {
  const schema: JsonSchema7 = {
    type: "object",
    title: "Company",
    required: ["name"],
    properties: {
      id: {
        type: ["string", "null"],
        title: "ID",
        description: "The AutoGenerated ID of this Company.",
        readOnly: true,
      },
      name: {
        type: "string",
        title: "Company Name",
      },
      regNumber: {
        type: ["string", "null"],
        title: "Company Number",
      },
      vatNumber: {
        type: ["string", "null"],
        title: "Registered Tax ID",
      },
      addressId: {
        type: ["string", "null"],
        title: "Address",
        default: baseModel?.addressId,
      },
      emailId: {
        type: ["string", "null"],
        title: "Email",
        default: baseModel?.emailId,
      },
      phoneId: {
        type: ["string", "null"],
        title: "Phone",
        default: baseModel?.phoneId,
      },
    },
  };

  return schema;
};

export const useUischema = (_context?: CompanyContext) => {
  const uiSchema = {
    type: "VerticalLayout",
    elements: [
      {
        type: "Control",
        scope: "#/properties/name",
        options: {
          autoFocus: true,
          autocomplete: "off",
          placeholder: "My company name",
        },
      },
      {
        type: "HorizontalLayout",
        elements: [
          {
            type: "Control",
            scope: "#/properties/regNumber",
            options: {
              placeholder: "Registered tax or GST",
            },
          },
          {
            type: "Control",
            scope: "#/properties/vatNumber",
            options: {
              placeholder: "VAT Number",
            },
          },
        ],
      },
      {
        type: "ModelList",
        scope: "#/properties/addressId",
        options: {
          label: "",
          list: useClientAddresses,
          mutate: useClientAddress,
        },
      },
    ],
  };

  return uiSchema as UISchemaElement;
};
