// --- external

// --- internal

// --- utils
import { get, map, isArray, compact } from "lodash-es";

// --- types
import type {
  IRegion,
  IAddress,
  ICompany,
  ICountry,
} from "@upmind-automation/types";
import { Company } from "./types";
import type { JsonSchema, UISchemaElement } from "@jsonforms/core";

// ---
// TODO: export const useSchema = ({ addresses, emails, phones, baseModel }) => {
export const useSchema = ({ addresses, emails, phones, baseModel }: any) => {
  const choices = {
    addresses: addresses.getItems(),
    emails: emails.getItems(),
    phones: phones.getItems(),
  };

  const schema = {
    type: "object",
    title: "Address Fields",
    required: ["name", "addressId", "emailId"],
    properties: {
      id: {
        type: ["string", "null"],
        title: "ID",
        description: "The AutoGenerated ID of this Company.",
        readOnly: true,
      },

      // ---
      name: {
        type: "string",
        title: "Name",
      },

      addressId: {
        type: "string",
        title: "Address",
        default: baseModel.addressId,
        oneOf: !choices?.addresses?.length
          ? undefined
          : map(choices.addresses, item => {
              return {
                const: item.id,
                title: item.name,
              };
            }),
        lookup: addresses.search,
      },

      emailId: {
        type: "string",
        title: "Email",
        default: baseModel.emailId,
        oneOf: !choices?.emails?.length
          ? undefined
          : map(choices.emails, item => {
              return {
                const: item.id,
                title: item.email,
              };
            }),
        lookup: emails.search,
      },

      phoneId: {
        type: "string",
        title: "Phone",
        default: baseModel.phoneId,
        oneOf: !choices?.phones?.length
          ? undefined
          : map(choices.phones, item => {
              return {
                const: item.id,
                title: item.full_phone,
              };
            }),
        lookup: phones.search,
      },

      regNumber: {
        type: ["string", "null"],
        title: "Registrration number",
      },
      vatNumber: {
        type: ["string", "null"],
        title: "Registered tax/VAT id",
      },
      // vatPercent: {
      //   type: ["string", "null"],
      //   title: "VAT percent",
      // },

      // ---

      default: {
        type: ["boolean", "null"],
        title: "Make this the default company?",
      },
    },
  };

  // if (id) {
  //   schema.required.push("name");
  //   schema.required.push("type");
  // }

  return schema as JsonSchema;
};

export const useUischema = () => {
  const schema = {
    type: "VerticalLayout",
    elements: [
      {
        type: "Control",
        scope: "#/properties/name",
        options: {
          autoFocus: true,
          autocomplete: "off",
          placeholder: "My company name",
        },
      },
      {
        type: "Control",
        scope: "#/properties/vatNumber",
        options: {
          autocomplete: "off",
          placeholder: "Registered tax/VAT id",
        },
      },
      {
        type: "Control",
        scope: "#/properties/regNumber",
        options: {
          autocomplete: "off",
          placeholder: "Registration number",
        },
      },

      // ---
      {
        type: "Control",
        scope: "#/properties/addressId",
        options: {
          autocomplete: "off",
          placeholder: "Select an Address...",
          itemLabel: "name",
          itemValue: "id",
          align: "start",
          side: "bottom",
        },
      },
      {
        type: "Control",
        scope: "#/properties/emailId",
        options: {
          autocomplete: "off",
          placeholder: "Select an email...",
          itemLabel: "email",
          itemValue: "id",
          align: "start",
          side: "bottom",
        },
      },
      {
        type: "Control",
        scope: "#/properties/phoneId",
        options: {
          autocomplete: "country",
          placeholder: "Please select a Phone Number  ...",
          itemLabel: "full_phone",
          itemValue: "id",
          align: "start",
          side: "bottom",
        },
      },
      // ---
      // We don't ever show this field as it is set by an action
      // {
      //   type: "Control",
      //   scope: "#/properties/default",
      //   options: {
      //     // toggle: true
      //   }
      // }
    ],
  };

  return schema as UISchemaElement;
};

// ---
export interface CompanyWithRelations extends ICompany {
  address: IAddress & { country: ICountry; region: IRegion };
}

export const parseCompany = (
  raw: CompanyWithRelations | CompanyWithRelations[]
): Company[] => {
  const rawListings = isArray(raw) ? raw : [raw];
  return map(rawListings, (rawItem: ICompany) => {
    return {
      id: rawItem.id,
      emailId: rawItem.email_id,
      phoneId: rawItem.phone_id,
      addressId: rawItem.address_id,
      title: rawItem.name,
      description: compact([
        get(rawItem, "address.address1"),
        get(rawItem, "address.address2"),
        get(rawItem, "address.street"),
        get(rawItem, "address.city"),
        get(rawItem, "address.postcode"),
        get(rawItem, "address.region.name"),
        get(rawItem, "address.country.name"),
      ]).join(", "),
      name: rawItem.name,
      default: rawItem.default,
      regNumber: rawItem.reg_number,
      vatNumber: rawItem.vat_percent,
      vatPercent: rawItem.vat_percent,
    };
  });
};
