// --- external
import { spawn } from "xstate";

// --- internal
import itemMachine from "../item.machine";
import { ItemActions as actions } from "./actions";
import services from "./services";

// --- utils
import { get, set, reduce, defaultsDeep, uniqueId, map } from "lodash-es";

// --- types
import type { ICompany } from "./types.d";
import type { JsonSchema, UISchemaElement } from "@jsonforms/core";

// --------------------------------------------------------

export const useSchema = ({ addresses, emails, phones, baseModel }) => {
  const choices = {
    addresses: addresses().getItems(),
    emails: emails().getItems(),
    phones: phones().getItems()
  };

  const schema = {
    type: "object",
    title: "Address Fields",
    required: ["name", "address_id", "email_id"],
    properties: {
      id: {
        type: ["string", "null"],
        title: "ID",
        description: "The AutoGenerated ID of this Company.",
        readOnly: true
      },

      // ---
      name: {
        type: ["string", "null"],
        title: "Name"
      },

      address_id: {
        type: ["string", "null"],
        title: "Address",
        // isLookup: addresses,
        default: baseModel.address_id,
        enum: !choices?.addresses?.length
          ? undefined
          : map(choices?.addresses, "id"),
        lookup: addresses
      },

      email_id: {
        type: ["string", "null"],
        title: "Email",
        // isLookup: emails,
        default: baseModel.email_id,
        enum: !choices?.emails?.length ? undefined : map(choices?.emails, "id"),
        lookup: emails
      },

      phone_id: {
        type: ["string", "null"],
        title: "Phone",
        // isLookup: phones,
        default: baseModel.phone_id,
        enum: !choices?.phones?.length ? undefined : map(choices?.phones, "id"),
        lookup: phones
      },

      reg_number: {
        type: ["string", "null"],
        title: "Registrration number"
      },
      vat_number: {
        type: ["string", "null"],
        title: "Registered tax/VAT id"
      },
      vat_percent: {
        type: ["string", "null"],
        title: "VAT percent"
      },

      // ---

      default: {
        type: ["boolean", "null"],
        title: "Make this the default company?"
      }
    }
  };

  // if (id) {
  //   schema.required.push("name");
  //   schema.required.push("type");
  // }

  return schema as JsonSchema;
};

export const useUischema = ({ addresses, emails, phones }) => {
  const schema = {
    type: "VerticalLayout",
    elements: [
      {
        type: "Control",
        scope: "#/properties/name",
        options: {
          focus: true,
          autocomplete: "off",
          placeholder: "My company name"
        }
      },
      {
        type: "Control",
        scope: "#/properties/vat_number",
        options: {
          autocomplete: "off",
          placeholder: "Registered tax/VAT id"
        }
      },
      {
        type: "Control",
        scope: "#/properties/reg_number",
        options: {
          autocomplete: "off",
          placeholder: "Registration number"
        }
      },

      // ---
      {
        type: "Control",
        scope: "#/properties/address_id",
        options: {
          autocomplete: "off",
          placeholder: "Select an Address...",
          lookup: addresses
        }
      },
      {
        type: "Control",
        scope: "#/properties/email_id",
        options: {
          autocomplete: "off",
          placeholder: "Select an email...",
          lookup: emails
        }
      },
      {
        type: "Control",
        scope: "#/properties/phone_id",
        options: {
          autocomplete: "country",
          placeholder: "Please select a Phone Number  ...",
          lookup: phones
        }
      }
      // ---
      // We dont ever show this field as it is set by an action
      // {
      //   type: "Control",
      //   scope: "#/properties/default",
      //   options: {
      //     // toggle: true
      //   }
      // }
    ]
  };

  return schema as UISchemaElement;
};

export const useModelParser = (schema: JsonSchema, values: ICompany) => {
  const model = reduce(
    schema.properties,
    (result, field, key) => {
      const value = get(values, key, field?.const || field?.default);
      set(result, key, value);
      return result;
    },
    {}
  );

  return defaultsDeep(model, values) as ICompany;
};

// --------------------------------------------------------

export const spawnItem = (model?: ICompany) => {
  try {
    const name = get(model, "id", uniqueId("item_"));
    return spawn(
      itemMachine
        .withConfig({
          actions,
          services
        })
        .withContext({ model }),
      {
        name,
        sync: true
      }
    );
  } catch (err) {
    console.error("CompanyListings", "spawnItem", { model });
  }
};
