// --- external
import { spawn } from "xstate";

// --- internal
import itemMachine from "../item.machine";
import { ItemActions as actions } from "./actions";
import services from "./services";

// --- utils
import { get, set, reduce, defaultsDeep, uniqueId } from "lodash-es";

// --- types
import type { IPhone } from "./types";
import type { JsonSchema, UISchemaElement } from "@jsonforms/core";

// --------------------------------------------------------

export const useSchema = () => {
  const schema = {
    type: "object",
    title: "Address Fields",
    required: ["name", "address_id", "phone_id"],
    properties: {
      id: {
        type: ["string", "null"],
        title: "ID",
        description: "The AutoGenerated ID of this Phone.",
        readOnly: true
      },

      // ---
      name: {
        type: "string",
        title: "Name"
      },

      address_id: {
        type: "string",
        title: "Address"
      },
      phone_id: {
        type: ["string", "null"],
        title: "Phone"
      },
      phone_id: {
        type: ["string", "null"],
        title: "Phone"
      },
      reg_number: {
        type: "string",
        title: "Registrration number"
      },
      vat_number: {
        type: "string",
        title: "Registered tax/VAT id"
      },
      vat_percent: {
        type: "string",
        title: "VAT percent"
      },

      // ---

      default: {
        type: ["boolean", "null"],
        title: "Make this the default phone?"
      }
    }
  };

  // if (id) {
  //   schema.required.push("name");
  //   schema.required.push("type");
  // }

  return schema as JsonSchema;
};

export const useUischema = () => {
  const schema = {
    type: "VerticalLayout",
    elements: [
      {
        type: "Control",
        scope: "#/properties/name",
        options: {
          focus: true,
          autocomplete: "off",
          placeholder: "My phone name"
        }
      },
      {
        type: "Control",
        scope: "#/properties/vat_number",
        options: {
          autocomplete: "off",
          placeholder: "Registered tax/VAT id"
        }
      },
      {
        type: "Control",
        scope: "#/properties/reg_number",
        options: {
          autocomplete: "off",
          placeholder: "Registration number"
        }
      },

      // ---
      {
        type: "Control",
        scope: "#/properties/address_id",
        options: {
          autocomplete: "off",
          placeholder: "Select an Address..."
        }
      },
      {
        type: "Control",
        scope: "#/properties/phone_id",
        options: {
          autocomplete: "off",
          placeholder: "Select an phone..."
        }
      },
      {
        type: "Control",
        scope: "#/properties/phone_id",
        options: {
          autocomplete: "country",
          placeholder: "Please select a Phone Number  ..."
        }
      }
      // ---
      // We dont ever show this field as it is set by an action
      // {
      //   type: "Control",
      //   scope: "#/properties/default",
      //   options: {
      //     // toggle: true
      //   }
      // }
    ]
  };

  return schema as UISchemaElement;
};

export const useModelParser = (schema: JsonSchema, values: IPhone) => {
  const model = reduce(
    schema.properties,
    (result, field, key) => {
      const value = get(values, key, field?.const || field?.default);
      set(result, key, value);
      return result;
    },
    {}
  );

  return defaultsDeep(model, values) as IPhone;
};

// --------------------------------------------------------

export const spawnItem = (model?: IPhone) => {
  try {
    const name = get(model, "id", uniqueId("item_"));
    debugger;
    return spawn(
      itemMachine
        .withConfig({
          actions,
          services
        })
        .withContext({ model }),
      {
        name,
        sync: true
      }
    );
  } catch (err) {
    console.error("PhoneListings", "spawnItem", { model });
  }
};
